### ISSUE TITLE
demo possibly not working   test_with_openai.py

### ISSUE THREAD

**Issue by twobob** [microsoft/autogen#113]
Windows 10
test_with_openai.py

    User_proxy (to chat_manager):
    
    Let's start the game!
    
    --------------------------------------------------------------------------------
    Player (to chat_manager):
    
    ***** Suggested function Call: get_random_number *****
    Arguments:
    {}
    ******************************************************
    
    --------------------------------------------------------------------------------
    Traceback (most recent call last):
      File "C:\REPO\autogen\test\test_with_openai.py", line 77, in <module>
      File "C:\REPO\autogen\test\test_with_openai.py", line 73, in test_function_call_groupchat
        user_proxy.initiate_chat(manager, message="Let's start the game!")

snip

api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Invalid parameter: only messages with role 'assistant' can have a function call.

I tried a few gpt variants. thought I should report

**Comment by sonichi** [comment]
This should have been fixed in the latest version. Could you verify?

**Comment by thinkall** [comment]
Closing this issue due to inactivity. If you have further questions, please open a new issue or join the discussion in AutoGen Discord server: https://discord.com/invite/Yb5gwGVkE5
