### ISSUE TITLE
[Issue]: Autogenstudio not working with opensource LLM Qwen (openai.PermissionDeniedError)

### ISSUE THREAD

**Issue by Haxeebraja** [microsoft/autogen#1259]
### Describe the issue

I have started Qwen API locally using openai_api.py. [https://github.com/QwenLM/Qwen/blob/main/openai_api.py](url)
It works fine in notebook with autogen but is not working in Autogenstudio.

openai.PermissionDeniedError: 
< !DOCTYPE html>
< html xmlns="http://www.w3.org/1999/xhtml">
< body>
< /body>
< /html>

### Screenshots and logs

userproxy (to primary_assistant):

print number 1 to 10

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autogenstudio/web/app.py", line 68, in add_message
    response_message: Message = chatmanager.chat(
  File "/usr/local/lib/python3.10/dist-packages/autogenstudio/chatmanager.py", line 29, in chat
    flow.run(message=f"{message_text}", clear_history=False)
  File "/usr/local/lib/python3.10/dist-packages/autogenstudio/workflowmanager.py", line 191, in run
    self.sender.initiate_chat(
  File "/usr/local/lib/python3.10/dist-packages/autogen/agentchat/conversable_agent.py", line 550, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/usr/local/lib/python3.10/dist-packages/autogen/agentchat/conversable_agent.py", line 348, in send
    recipient.receive(message, self, request_reply, silent)
  File "/usr/local/lib/python3.10/dist-packages/autogen/agentchat/conversable_agent.py", line 481, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "/usr/local/lib/python3.10/dist-packages/autogen/agentchat/conversable_agent.py", line 906, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/usr/local/lib/python3.10/dist-packages/autogen/agentchat/conversable_agent.py", line 625, in generate_oai_reply
    response = client.create(
  File "/usr/local/lib/python3.10/dist-packages/autogen/oai/client.py", line 247, in create
    response = self._completions_create(client, params)
  File "/usr/local/lib/python3.10/dist-packages/autogen/oai/client.py", line 327, in _completions_create
    response = completions.create(**params)
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 272, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 645, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1088, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 853, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 930, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.PermissionDeniedError: < !DOCTYPE html >
...
INFO:     172.17.0.1:58078 - "POST /messages HTTP/1.1" 200 OK

**Comment by ekzhu** [comment]
Thanks for the issue. Would you share your example of AutoGen + LLM Qwen? How did you set it up etc.

**Comment by ekzhu** [comment]
@victordibia

**Comment by Haxeebraja** [comment]
> Thanks for the issue. Would you share your example of AutoGen + LLM Qwen? How did you set it up etc.

Qwen API running locally using openai_api.py. [https://github.com/QwenLM/Qwen/blob/main/openai_api.py](https://github.com/microsoft/autogen/issues/url)
python openai_api.py -c Qwen-72B-Chat --server-name 0.0.0.0 --server-port=8787

Code to run autogen powered by Qwen:
config_list = [
        {
            "model": "Qwen",
            "base_url": "http://localhost:8787/v1",
            "api_key": "NULL", 
        }
]

llm_config = {
    "config_list": config_list,
    "temperature": 0,
    #"max_tokens": -1
}

Then creating assistant agent, usery proxy and initiating chat. This is working fine. 
Issue is with autogen studio.

**Comment by ekzhu** [comment]
Thanks @Haxeebraja would you like to join our discord server? Would love to hear more about what you are experimenting/building

**Comment by Haxeebraja** [comment]
Facing the same issue while using chainlit. 
However, following works fine in chainlit but get the same error above in user_proxy.intitiate_chat:

client = OpenAIWrapper(config_list=config_list)
response = client.create(messages=[{"role": "user", "content": "2+9="}])
print(client.extract_text_or_completion_object(response))

**Comment by ekzhu** [comment]
It looks like you are using the OpenAIWrapper directly, can you post your code regarding initiate_chat?

**Comment by Haxeebraja** [comment]
Not using assistant/initiate_chat with OpenAIWrapper. I shared it to show that this is working fine with Qwen and chainlit UI with the same config_list.
However, following does not work with agents and errors out at initiate_chat:
https://github.com/Chainlit/cookbook/tree/main/pyautogen

**Comment by Haxeebraja** [comment]
@ekzhu After openai permission denied I get the following the traceback. I have a closed network and can't access internet unless a url has been whitelisted by security team. Is it possible that autogenstudio is trying to access this URL from openai: http://www.w3.org/1999/xhtml

<! DOCTYPE html >
< html xmlns="http://www.w3.org/1999/xhtml" >
< body >
< /body >
< /html >

**Comment by Haxeebraja** [comment]
Fixed this issue after serving the model with FastChat.
