### ISSUE TITLE
[Bug]: Connection refused error on WSL2

### ISSUE THREAD

**Issue by shittiidavincii** [microsoft/autogen#1272]
### Describe the bug

Running WSL2 with Ubuntu. Installed autogenstudio via pip. Ran it with the standard `autogenstudio ui --port 8081` command.

The web ui works fine, but when I try to chat, I get a connection refused with a lengthy error message.

Here is the error message:

```bash
jynx@TJ-Desktop:~$ autogenstudio ui --port 8081
INFO:     Started server process [414]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)
INFO:     127.0.0.1:43710 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43710 - "GET /images/svgs/welcome.svg HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43710 - "GET /app-0b19e7b3b3630760e904.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43710 - "GET /framework-0e118549f33203964972.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43710 - "GET /webpack-runtime-d26758facd302421ecb4.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43710 - "GET /page-data/app-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43710 - "GET /page-data/index/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43710 - "GET /favicon-32x32.png?v=46131b614287332146ea078703a67d38 HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43710 - "GET /318ce576f236b79fd96f75904c13f6e55c3eee57-8feabdf57edb2a6eecc8.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43710 - "GET /6c05b3ab656a8bfc225a64b3d73a36a92f83c05e-6dce912a9a9b963cded5.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43710 - "GET /component---src-pages-index-tsx-3209e5a7b17734fbd11c.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43764 - "GET /manifest.webmanifest HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43710 - "GET /api/sessions?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:43710 - "GET /api/sessions?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:43710 - "GET /api/messages?user_id=guestuser@gmail.com&session_id=2204c1e6-01fc-4ff5-a487-eb881ff1d18d HTTP/1.1" 200 OK
INFO:     127.0.0.1:43710 - "GET /api/messages?user_id=guestuser@gmail.com&session_id=2204c1e6-01fc-4ff5-a487-eb881ff1d18d HTTP/1.1" 200 OK
INFO:     127.0.0.1:43726 - "GET /page-data/gallery/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43742 - "GET /page-data/build/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43742 - "GET /page-data/gallery/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43726 - "GET /page-data/build/page-data.json HTTP/1.1" 304 Not Modified
userproxy (to primary_assistant):

i'm writing to you from autogen studio. can you give me an overview of what kiund of thigns i can use autogen for? what's a good starting project for it?

--------------------------------------------------------------------------------
userproxy (to primary_assistant):

test

--------------------------------------------------------------------------------
userproxy (to primary_assistant):

Write a python script to plot a sine wave and save it to disc as a png file sine_wave.png

--------------------------------------------------------------------------------
userproxy (to primary_assistant):

test

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jynx/.local/lib/python3.10/site-packages/openai/_base_client.py", line 887, in _request
    response = self._client.send(
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 230, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jynx/.local/lib/python3.10/site-packages/openai/_base_client.py", line 887, in _request
    response = self._client.send(
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 230, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jynx/.local/lib/python3.10/site-packages/openai/_base_client.py", line 887, in _request
    response = self._client.send(
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 230, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/jynx/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jynx/.local/lib/python3.10/site-packages/autogenstudio/web/app.py", line 68, in add_message
    response_message: Message = chatmanager.chat(
  File "/home/jynx/.local/lib/python3.10/site-packages/autogenstudio/chatmanager.py", line 29, in chat
    flow.run(message=f"{message_text}", clear_history=False)
  File "/home/jynx/.local/lib/python3.10/site-packages/autogenstudio/workflowmanager.py", line 191, in run
    self.sender.initiate_chat(
  File "/home/jynx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 621, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/home/jynx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 398, in send
    recipient.receive(message, self, request_reply, silent)
  File "/home/jynx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 551, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "/home/jynx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 1193, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/home/jynx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 708, in generate_oai_reply
    response = client.create(
  File "/home/jynx/.local/lib/python3.10/site-packages/autogen/oai/client.py", line 278, in create
    response = self._completions_create(client, params)
  File "/home/jynx/.local/lib/python3.10/site-packages/autogen/oai/client.py", line 543, in _completions_create
    response = completions.create(**params)
  File "/home/jynx/.local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
  File "/home/jynx/.local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 643, in create
    return self._post(
  File "/home/jynx/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1112, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/jynx/.local/lib/python3.10/site-packages/openai/_base_client.py", line 859, in request
    return self._request(
  File "/home/jynx/.local/lib/python3.10/site-packages/openai/_base_client.py", line 911, in _request
    return self._retry_request(
  File "/home/jynx/.local/lib/python3.10/site-packages/openai/_base_client.py", line 982, in _retry_request
    return self._request(
  File "/home/jynx/.local/lib/python3.10/site-packages/openai/_base_client.py", line 911, in _request
    return self._retry_request(
  File "/home/jynx/.local/lib/python3.10/site-packages/openai/_base_client.py", line 982, in _retry_request
    return self._request(
  File "/home/jynx/.local/lib/python3.10/site-packages/openai/_base_client.py", line 921, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

INFO:     127.0.0.1:43710 - "POST /api/messages HTTP/1.1" 200 OK
INFO:     127.0.0.1:43726 - "GET /component---src-pages-gallery-index-tsx-f78f5f06ef65ea97e302.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:43742 - "GET /component---src-pages-build-tsx-10ec7cd0147b32ec3a0b.js HTTP/1.1" 304 Not Modified

```

### Steps to reproduce

see above

### Expected Behavior

not a connection refused error when trying to talk to the model

**Comment by victordibia** [comment]
Hi

What model are you using?
You must also specify the model you intend to use in the workflow config UI (and remove all others)

**Comment by shittiidavincii** [comment]
<img width="396" alt="image" src="https://github.com/microsoft/autogen/assets/33853262/bbbfce95-7f36-45b8-abe9-dc5a09bdee23">

using OpenAI GPT4. Is this the right configuration?

**Comment by victordibia** [comment]
Under models … can you confirm you have an api key? Eg when you select gpt-4-1106-preview … can you ensure you have your api key setup there also.

**Comment by shittiidavincii** [comment]
It wasn't set there before (I set it via an environment variable before). 

I added that and the model base url but the issue persists 

<img width="272" alt="image" src="https://github.com/microsoft/autogen/assets/33853262/d62c10cd-5285-40f7-96eb-32c603a51dde">

**Comment by victordibia** [comment]
Your key seems long. Is this Azure Open AI or OpenAI? 
Note:

- For azure openai, you will need to fill in all the fields (see below)
- For openai you only need to provide model name and api key 


For azure openai you will need to set the following

- model - which is the deployment id or engine 
- api key .. from azure
- base url .. from azure
- model type ..  -  "azure" 
- api version ... which must be what you get from azure.

Also note that you should only have this model in your list of models.

![Image](https://github.com/microsoft/autogen/assets/1547007/60a42e46-d692-4e4d-93f0-e415bd295315)

**Comment by Ludecan** [comment]
I'm having the same issue on WSL2 Ubuntu 22.04 under Windows 11.

In my case there weren't any models set for the `userproxy` agent, but they were set for `primary_assistant`.
I've added `gpt-4-1106-preview` to the `userproxy` agent, the same as it was set for `primary_assistant`.
I've also set my `OPENAI_API_KEY` envvar and added the API key to the models of both agents but still getting the connection error.

Is there anything useful I can send you to help you debug this?

![imagen](https://github.com/microsoft/autogen/assets/17169248/61220eb2-d56a-4368-847b-88f07cad34ae)
![imagen](https://github.com/microsoft/autogen/assets/17169248/e2681d1a-c79a-446f-8a3c-0f4d644ee1e9)
![imagen](https://github.com/microsoft/autogen/assets/17169248/1fc34697-3b21-4266-8e87-e8d2045d3567)

**Comment by Ludecan** [comment]
Hmmm, I'm getting the same error using a native Windows install with Miniconda. WSL2 doesn't seem to be the culprit. Maybe there's something missing in the `userproxy` agent config?

**Comment by shittiidavincii** [comment]
Yes, I have an API key setup there, as well as an environment variable set. I've also put the base url in as https://api.openai.com/v1

<img width="277" alt="image" src="https://github.com/microsoft/autogen/assets/33853262/f5456b34-7f56-49dc-bc55-9d8afa0358f2">

**Comment by xamox** [comment]
I've tried with WSL2, Miniconda, as well as docker in a ubuntu 22.04 image and seem to be getting the same error. I am also on windows 11.  I also tried it on another ubuntu 22.04 physical server I had.  After digging a little bit I see the default model is `gpt-4-1106-preview`, when looking at my rate limits on my account I do not see that available.  After some digging it appears that you had to have a certain amount of money spent using API keys when OpenAI released it.  I'm not sure if that is the issue, I tried removing that model from the primary agent but still getting the OpenAI connection error. I saw the other default model was `gpt-3.5-turbo-16k`, I tried just setting the agent to use this as it appears I do have access to that model in my openai settings page.    Is there a more in depth guide in setting it up than the blog post?  I see the blog post mentions config and it seems to save that info but I don't see any hidden folder or anything from the directory I'm running it in, nor anything in the home directory like `~/.autogen` or anything of that nature.

**Comment by radman-x** [comment]
Getting same error here -- just running native Windows 10.

**Comment by xamox** [comment]
Can people on this error confirm my above suspicion by going to:
https://platform.openai.com/playground?assistant=new

![image](https://github.com/microsoft/autogen/assets/492564/dd6c661a-e1e1-42f0-8243-76392848f4cf)

And check in the models drop down if you have `gpt-4-1106-preview`, that may rule out if that's the underlying issue

**Comment by aleatorydialogue** [comment]
I believe I have configured correctly, I have active API key entered and I did check on my playground, I do have gpt-4-1106-preview available, still getting connection error as well. Wasn't able to set it up for a local model through text-generation-webui either. I am able to use autogen without studio UI

**Comment by radman-x** [comment]
> Can people on this error confirm my above suspicion by going to: https://platform.openai.com/playground?assistant=new
> 
> ![image](https://private-user-images.githubusercontent.com/492564/297792708-dd6c661a-e1e1-42f0-8243-76392848f4cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2ODQ2NTQsIm5iZiI6MTcwNTY4NDM1NCwicGF0aCI6Ii80OTI1NjQvMjk3NzkyNzA4LWRkNmM2NjFhLWUxZTEtNDJmMC04MjQzLTc2MzkyODQ4ZjRjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNzEyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGZhYTJjYTNhMjI4MzUwYTNjZTVlMDIxZmEyYTAzYWFjNzFmN2Q3NDQ4Zjg4NDEwZjdjZjEwZGM3ZThlNWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Iu7JEoWtcUkb8o-bGTk-NIGosefd3w5zZsfIJARuO0A)
> 
> And check in the models drop down if you have `gpt-4-1106-preview`, that may rule out if that's the underlying issue

Yes, gpt-4-1106-preview exists in the model drop down.

**Comment by vannestn** [comment]
<img width="373" alt="Screenshot 2024-01-19 at 6 49 53 PM" src="https://github.com/microsoft/autogen/assets/22547210/3cf6f9c2-7e86-4a72-bcb1-1638c3215d99">
I'm seeing an error as well. As you can see it is letting me use the `gpt-4-1106-preview` agent on the OpenAI website. Also, when I modify my autogen agents to only use GPT-3.5 the error persists.

**Comment by xamox** [comment]
@vannestn thanks for confirming.  I also tested this in the playground and got the same error even with gpt-3.5.  I dug into it a little it and looked at my limits and some articles.

<img width="903" alt="image" src="https://github.com/microsoft/autogen/assets/492564/5b5c385a-7f5a-4b65-9584-305fca23fdc3">


Looked like I was in the free tier usage.  I bought $10 worth of credits to jump me to tier 1.
<img width="965" alt="image" src="https://github.com/microsoft/autogen/assets/492564/494fe718-bff4-42e7-9cc6-934e22e74ca1">


After that I was able to use the playground with that model:
<img width="1600" alt="image" src="https://github.com/microsoft/autogen/assets/492564/5920f22c-82aa-49d6-b46d-de6b514d6bb3">


I tried upgrading autogen ui via (pip install -U autogen), and creating a new API key and running the UI again but still getting the same connection error.  I'm not sure if I should wait a little bit, like it takes a few minutes to propagate my tier upgrade, but at least I figured out the OpenAI issue now with the error.  Maybe if I get some more time later I will test some more.

**Comment by vannestn** [comment]
When I bought new credits with Open AI, their own playground UI wasn’t able
to use the credits until a day later. Maybe it’s a fraud prevention
measure. After a day had passed, the playground was able to run an agent
for me. Haven’t run the Autogen program yet but I’ll let you know how it
goes.
