### ISSUE TITLE
[Bug]: unsupported protocal http:localhost

### ISSUE THREAD

**Issue by iplayfast** [microsoft/autogen#1300]
### Describe the bug
YOU HAVE TO DELETE THE AGENT/WORKSPACE IN ORDER TO CHANGE THE URL when using localhost

Using ollama and litellm to set up local llm. 
playground gets error, switching to console show:
```
 File "/home/chris/anaconda3/envs/autogen2/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 219, in handle_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL has an unsupported protocol 'localhost://'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chris/anaconda3/envs/autogen2/lib/python3.11/site-packages/openai/_base_client.py", line 887, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen2/lib/python3.11/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen2/lib/python3.11/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen2/lib/python3.11/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen2/lib/python3.11/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chris/anaconda3/envs/autogen2/lib/python3.11/site-packages/httpx/_transports/default.py", line 230, in handle_request
    with map_httpcore_exceptions():
  File "/home/chris/anaconda3/envs/autogen2/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/chris/anaconda3/envs/autogen2/lib/python3.11/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL has an unsupported protocol 'localhost://'.
```

### Steps to reproduce

I first created agents and workflows using localhost:9000 localhost:9001 and localhost9002
I then tried out the playground and got the unsupported protocal http:localhost error.

So I then went back and changed them all to 127:0.0.1:9000,127:0.0.1:9001 and 127:0.0.1:9002
The problem persists, (no mention of 127.0.0.1 just localhost)
So then I went back and added the http: in front. Still not working.

YOU HAVE TO DELETE THE AGENT/WORKSPACE IN ORDER TO CHANGE THE URL

**Comment by iplayfast** [comment]
Sorry for the late reply, was out of country. 
```
autogenstudio version
AutoGen Studio  CLI version: 0.0.44a
```
installed with pip -U autogenstudio
