### ISSUE TITLE
[Issue]: AutoGen Studio  | Error with Azure OpenAI key

### ISSUE THREAD

**Issue by iokinpardo** [microsoft/autogen#1325]
### Describe the issue

Hi team many thanks for your Azure setting suggestions.

I have followed @victordibia suggestions and set all Azure setings for both "**User Proxy**" and "**Primary**" agents . Also removed all models from the list and just set this Azure model created. If I try wih OpenAI everything runs fine. I have set the code "**export AZURE_OPENAI_API_KEY=zzzzzzzz**" previous to launching AutoGen Studio.

As soon as I try sending the mesage "Hello" in a new PlayGround session, Im getting this error. AttributeError: '**NoneType**' object has no attribute '**model_dump**'.

Maybe Im missing something? Thanks in advance.

```
az_userproxy (to az_primary_assistant):

hello

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogenstudio/web/app.py", line 68, in add_message
    response_message: Message = chatmanager.chat(
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogenstudio/chatmanager.py", line 29, in chat
    flow.run(message=f"{message_text}", clear_history=False)
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogenstudio/workflowmanager.py", line 196, in run
    self.sender.initiate_chat(
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 621, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 398, in send
    recipient.receive(message, self, request_reply, silent)
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 551, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 1193, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 716, in generate_oai_reply
    extracted_response = model_dump(extracted_response)
  File "/home/xxxx/.local/lib/python3.10/site-packages/autogen/_pydantic.py", line 37, in model_dump
    return model.model_dump()
AttributeError: '**NoneType**' object has no attribute '**model_dump**'

```

**Comment by ekzhu** [comment]
It looks like the Azure OpenAI returns a None value in the response message. Can you post your pyautogen version, openai version. Thanks!

@yenif @maxim-saplin @sonichi for awareness

**Comment by victordibia** [comment]
@iokinpardo ,

Can you confirm if you are able to use your Azure endpoint from python with AutoGen? 
This way we can triangulate if the issue is with your credentials, autogen or the autogenstudio implementation.

**Comment by maxim-saplin** [comment]
JIC, I also tried using Autigen Studio running it locally from sources (it was quite a challenge). I added Azure models to both clients and one of the workflows (General Agent Workflow) and I am getting `Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}`.

Happy to diagnose the issue yet I am out of my reverse engineering capacity today :) Can someone point at a complete instruction explaining how to run and debug the solution?

P.S.: here's my draft of my steps that made the UI open:
```
cd samples/apps/autogen-studio/frontend
npm install -g gatsby-cli
npm install -g yarn
yarn install yarn build
cd ..
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python -m autogenstudio.cli ui --port 8081
```

There was also an error of `scratch` folder non existing, had to manually open user/{GUID} and make directory there

**Comment by iokinpardo** [comment]
Thanks @victordibia . 

How can I check AutoGen case with my Azure Keys? Btm I have just beeing runing with AG Studio, so don't know very much how to launch "Autogen Engine". Is it already installed with AG Studio or should I install it? What are the steps to follow to cofirm the correct performance with Azure keys?

Thanks in advance.

**Comment by iokinpardo** [comment]
Thanks @victordibia .

Finally I have been able to update the latest AutoGen Studio version where Models are configured individually and I have been able to set Azure based ones properly. Many thanks.

Now I have couple of doubts:

- Is it possible for Agents to set "**Max Consecutive Auto Reply" to 1** as this could let us run more eficiently during testing process? And in cases where Agents are able to answer accurately in 1 unique step too.

- Which configuration prevails? The ones set under **Workflows for internal Agents**? Or the ones **configured on Agents**, and then being **used on Workflows**? Because it seems that we can have some configurations predefined for Agents, but just will be used the ones set on Agents inside Workflows, right?

**Comment by victordibia** [comment]
@ekzhu .. I just had a session where we encounted the same None Type error with AOAI models. 
Some inputs were fine, others had the issue. Specifically, when the input is "hello" in a two agent setup, we see that error.
