### ISSUE TITLE
[Bug]: Couldn't use Azure openai with autogenstudio

### ISSUE THREAD

**Issue by hellangleZ** [microsoft/autogen#1338]
### Describe the bug

Hi experts:

I have also face this problem by using Azure Openai

INFO: 127.0.0.1:49858 - "GET /page-data/build/page-data.json HTTP/1.1" 200 OK
INFO: 127.0.0.1:49856 - "GET /page-data/gallery/page-data.json HTTP/1.1" 200 OK
INFO: 127.0.0.1:49858 - "GET /component---src-pages-gallery-index-tsx-25eaa0ea2f26f1c4361f.js HTTP/1.1" 200 OK
INFO: 127.0.0.1:49856 - "GET /component---src-pages-build-tsx-3bd5608467a276d90ea7.js HTTP/1.1" 200 OK
Traceback (most recent call last):
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\web\app.py", line 68, in add_message
response_message: Message = chatmanager.chat(
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\chatmanager.py", line 22, in chat
flow = AutoGenWorkFlowManager(config=flow_config, history=history, work_dir=scratch_dir)
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 37, in init
self.receiver = self.load(config.receiver)
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 158, in load
agent = self.load_agent_config(agent_spec.config, agent_spec.type)
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 173, in load_agent_config
agent = autogen.AssistantAgent(**agent_config.dict())
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\agentchat\assistant_agent.py", line 61, in init
super().init(
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\agentchat\conversable_agent.py", line 126, in init
self.client = OpenAIWrapper(**self.llm_config)
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 108, in init
self._clients: List[OpenAI] = [
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 109, in
self._client(config, openai_config) for config in config_list
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 149, in _client
client = OpenAI(**openai_config)
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai_client.py", line 93, in init
raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

INFO: 127.0.0.1:49856 - "POST /api/messages HTTP/1.1" 200 OK

even I delete all other model in my model list, I still face this problem
![image](https://github.com/microsoft/autogen/assets/15274284/e01d851e-54c3-4fe9-97c5-a9693a9dc038)
![image](https://github.com/microsoft/autogen/assets/15274284/aa30b91b-1eb0-4be8-8c79-c5219ddd8b03)

How can I sovle this problem ?

Thanks

### Steps to reproduce

pip install autogenstudio
use Azure openAI configuration to config 

### Screenshots and logs

INFO: 127.0.0.1:49858 - "GET /page-data/build/page-data.json HTTP/1.1" 200 OK
INFO: 127.0.0.1:49856 - "GET /page-data/gallery/page-data.json HTTP/1.1" 200 OK
INFO: 127.0.0.1:49858 - "GET /component---src-pages-gallery-index-tsx-25eaa0ea2f26f1c4361f.js HTTP/1.1" 200 OK
INFO: 127.0.0.1:49856 - "GET /component---src-pages-build-tsx-3bd5608467a276d90ea7.js HTTP/1.1" 200 OK
Traceback (most recent call last):
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\web\app.py", line 68, in add_message
response_message: Message = chatmanager.chat(
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\chatmanager.py", line 22, in chat
flow = AutoGenWorkFlowManager(config=flow_config, history=history, work_dir=scratch_dir)
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 37, in init
self.receiver = self.load(config.receiver)
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 158, in load
agent = self.load_agent_config(agent_spec.config, agent_spec.type)
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogenstudio\workflowmanager.py", line 173, in load_agent_config
agent = autogen.AssistantAgent(**agent_config.dict())
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\agentchat\assistant_agent.py", line 61, in init
super().init(
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\agentchat\conversable_agent.py", line 126, in init
self.client = OpenAIWrapper(**self.llm_config)
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 108, in init
self._clients: List[OpenAI] = [
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 109, in
self._client(config, openai_config) for config in config_list
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\autogen\oai\client.py", line 149, in _client
client = OpenAI(**openai_config)
File "C:\Users\bozho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openai_client.py", line 93, in init
raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

**Comment by hellangleZ** [comment]
![image](https://github.com/microsoft/autogen/assets/15274284/28c385d6-ef7a-43fd-8e55-d2461b7d3d99)
only one model

**Comment by cheng-tan** [comment]
> ![image](https://private-user-images.githubusercontent.com/15274284/298074673-28c385d6-ef7a-43fd-8e55-d2461b7d3d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2OTAxNDcsIm5iZiI6MTcwNTY4OTg0NywicGF0aCI6Ii8xNTI3NDI4NC8yOTgwNzQ2NzMtMjhjMzg1ZDYtZWY3YS00M2ZkLThlNTUtZDI0NjFiN2QzZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE4NDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNWI4NDNlYzU0MDE1MTk3ZjM2MGJiOWM2YWFjZTgwNGYxNzExYTM0Yjc4ZmNiYjRlNmExNTVjNjFmYmI2OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D_e0nSWh8Ti7RQ-K-4sIL4hWxo06GHDfpP8abGwVfGA) only one model

1) For this screen shot, which agent is it? 
2) Can you go to Azure OpenAI studio(the page in your first screenshot), select the `gpt-35` model, then click on "Open in Playground". On the playground page, middle panel click on "View code", you should see the settings of the model look like this:
```
openai.api_type = "azure"
openai.api_base = "https://xxxxxxx.openai.azure.com/"
openai.api_version = "xxxxxx"
openai.api_key = ......
```
Can you confirm they are the same as what you put in the second screenshot?

3) Still in "View code", line 14, there's "engine" which should match the name you put in the second screenshot. Can you also confirm that?

**Comment by hellangleZ** [comment]
Hi @cheng-tan 


Really strong issue, I see if I use 2023-07-01-preview API, it works, but when I use 2023-05-15 api version, it couldnot work

2023-07-01-preview is in the code playground

![image](https://github.com/microsoft/autogen/assets/15274284/96311d3d-5d03-46ce-b38f-4f14c0ddb218)

But if I use 2023-05-15 in other project , it works....





> > ![image](https://private-user-images.githubusercontent.com/15274284/298074673-28c385d6-ef7a-43fd-8e55-d2461b7d3d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2OTAxNDcsIm5iZiI6MTcwNTY4OTg0NywicGF0aCI6Ii8xNTI3NDI4NC8yOTgwNzQ2NzMtMjhjMzg1ZDYtZWY3YS00M2ZkLThlNTUtZDI0NjFiN2QzZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE4NDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNWI4NDNlYzU0MDE1MTk3ZjM2MGJiOWM2YWFjZTgwNGYxNzExYTM0Yjc4ZmNiYjRlNmExNTVjNjFmYmI2OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D_e0nSWh8Ti7RQ-K-4sIL4hWxo06GHDfpP8abGwVfGA) only one model
> 
> 1. For this screen shot, which agent is it?
> 2. Can you go to Azure OpenAI studio(the page in your first screenshot), select the `gpt-35` model, then click on "Open in Playground". On the playground page, middle panel click on "View code", you should see the settings of the model look like this:
> 
> ```
> openai.api_type = "azure"
> openai.api_base = "https://xxxxxxx.openai.azure.com/"
> openai.api_version = "xxxxxx"
> openai.api_key = ......
> ```
> 
> Can you confirm they are the same as what you put in the second screenshot?
> 
> 3. Still in "View code", line 14, there's "engine" which should match the name you put in the second screenshot. Can you also confirm that?

**Comment by sunxingrong33** [comment]
Do you face this? Try many times, but I still don't know how to solve.
Thank you very much.

my another error is ：

"Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore_exceptions.py", line 10, in map_exceptions
yield
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore_backends\sync.py", line 206, in connect_tcp
sock = socket.create_connection(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\socket.py", line 851, in create_connection
raise exceptions[0]
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\socket.py", line 836, in create_connection
sock.connect(sa)
TimeoutError: [WinError 10060] 。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx_transports\default.py", line 67, in map_httpcore_exceptions
yield
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx_transports\default.py", line 231, in handle_request
resp = self._pool.handle_request(req)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore_sync\connection_pool.py", line 268, in handle_request
raise exc
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore_sync\connection_pool.py", line 251, in handle_request
response = connection.handle_request(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore_sync\connection.py", line 99, in handle_request
raise exc
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore_sync\connection.py", line 76, in handle_request
stream = self._connect(request)
^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore_sync\connection.py", line 124, in _connect
stream = self._network_backend.connect_tcp(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore_backends\sync.py", line 205, in connect_tcp
with map_exceptions(exc_map):
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\contextlib.py", line 158, in exit
self.gen.throw(typ, value, traceback)
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpcore_exceptions.py", line 14, in map_exceptions
raise to_exc(exc) from exc
httpcore.ConnectTimeout: [WinError 10060]。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\openai_base_client.py", line 885, in _request
response = self._client.send(
^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx_client.py", line 915, in send
response = self._send_handling_auth(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx_client.py", line 943, in _send_handling_auth
response = self._send_handling_redirects(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx_client.py", line 980, in _send_handling_redirects
response = self._send_single_request(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx_client.py", line 1016, in _send_single_request
response = transport.handle_request(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx_transports\default.py", line 230, in handle_request
with map_httpcore_exceptions():
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\contextlib.py", line 158, in exit
self.gen.throw(typ, value, traceback)
File "C:\ProgramData\Anaconda3\envs\autogen\Lib\site-packages\httpx_transports\default.py", line 84, in map_httpcore_exceptions
raise mapped_exc(message) from exc
httpx.ConnectTimeout: [WinError 10060]。
"

**Comment by lz-chen** [comment]
Also facing the same issue here. When I look at the log it seems that the models are not being updated according to the new information I set UI? 
```
INFO:     127.0.0.1:51138 - "POST /api/messages HTTP/1.1" 200 OK
INFO:     127.0.0.1:51146 - "GET /api/workflows?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:51146 - "GET /api/models?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:51209 - "POST /api/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:51225 - "POST /api/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:51257 - "POST /api/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:51257 - "GET /build HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:51257 - "GET /build/ HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51257 - "GET /app-e668c2f8516018ac0a1c.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51262 - "GET /framework-0e118549f33203964972.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51263 - "GET /webpack-runtime-5d7173c472e7866cdb8d.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51263 - "GET /page-data/app-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51262 - "GET /page-data/build/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51263 - "GET /favicon-32x32.png?v=46131b614287332146ea078703a67d38 HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51265 - "GET /manifest.webmanifest HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51263 - "GET /318ce576f236b79fd96f75904c13f6e55c3eee57-bf26f3994740657e0089.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51262 - "GET /component---src-pages-build-tsx-327ca1b88cf4c2d6fc61.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51262 - "GET /api/workflows?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:51262 - "GET /api/models?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:51262 - "GET /page-data/gallery/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51263 - "GET /page-data/index/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51263 - "GET /page-data/index/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51263 - "GET /page-data/gallery/page-data.json HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51262 - "GET /component---src-pages-index-tsx-2342fef3effa18a4d864.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51263 - "GET /component---src-pages-gallery-index-tsx-25eaa0ea2f26f1c4361f.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51272 - "GET /api/agents?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:51272 - "GET /api/models?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:51283 - "POST /api/agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:51283 - "GET /api/models?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:51285 - "POST /api/agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:51285 - "GET /api/models?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:51285 - "POST /api/agents HTTP/1.1" 200 OK
INFO:     127.0.0.1:51285 - "GET /6c05b3ab656a8bfc225a64b3d73a36a92f83c05e-6a87df80060a5da491fc.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51285 - "GET /api/sessions?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:51288 - "GET /api/sessions?user_id=guestuser@gmail.com HTTP/1.1" 200 OK
INFO:     127.0.0.1:51285 - "GET /images/svgs/welcome.svg HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51285 - "GET /api/messages?user_id=guestuser@gmail.com&session_id=763b6ac8-73c8-45b4-8c91-7f5980e5a683 HTTP/1.1" 200 OK
INFO:     127.0.0.1:51285 - "GET /api/messages?user_id=guestuser@gmail.com&session_id=763b6ac8-73c8-45b4-8c91-7f5980e5a683 HTTP/1.1" 200 OK
agent_spec.config  LLMConfig(config_list=[{'model': 'gpt-4-1106-preview'}, {'model': 'gpt-3.5-turbo-16k'}, {'model': 'TheBloke/zephyr-7B-alpha-AWQ', 'base_url': 'http://localhost:8000/v1'}], temperature=0.1, cache_seed=None, timeout=600)
```

The `LLMConfig` still shows the default list of models, but I updated it in UI:
![Screenshot 2024-01-20 at 17 25 28](https://github.com/microsoft/autogen/assets/38908263/c734ca18-1e42-43a5-be28-5d2ae484de65)

**Comment by monuminu** [comment]
remember the deployment name should be same as model. It should be working

**Comment by lz-chen** [comment]
@monuminu Do you mean the name in green in the screenshot above should be the same as model name in Azure OpenAI deployment, or? These are the deployments I have:
![Screenshot 2024-01-22 at 20 42 09](https://github.com/microsoft/autogen/assets/38908263/79cf58ee-3356-4034-b292-3641f08833bd)

Why In the log it shows these three model  `gpt-4-1106-preview`, `gpt-3.5-turbo-16k` and `TheBloke/zephyr-7B-alpha-AWQ` while I have different models setup (as shown in previous screenshot). Shouldn't it be `gpt-4`, `gpt-3.5-turbo-16k` and `dall-e-3`? 
```
INFO:     127.0.0.1:51285 - "GET /api/messages?user_id=guestuser@gmail.com&session_id=763b6ac8-73c8-45b4-8c91-7f5980e5a683 HTTP/1.1" 200 OK
agent_spec.config  LLMConfig(config_list=[{'model': 'gpt-4-1106-preview'}, {'model': 'gpt-3.5-turbo-16k'}, {'model': 'TheBloke/zephyr-7B-alpha-AWQ', 'base_url': 'http://localhost:8000/v1'}], temperature=0.1, cache_seed=None, timeout=600)
```

**Comment by cheng-tan** [comment]
> > ![image](https://private-user-images.githubusercontent.com/15274284/298074673-28c385d6-ef7a-43fd-8e55-d2461b7d3d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2OTAxNDcsIm5iZiI6MTcwNTY4OTg0NywicGF0aCI6Ii8xNTI3NDI4NC8yOTgwNzQ2NzMtMjhjMzg1ZDYtZWY3YS00M2ZkLThlNTUtZDI0NjFiN2QzZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDE4NDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNWI4NDNlYzU0MDE1MTk3ZjM2MGJiOWM2YWFjZTgwNGYxNzExYTM0Yjc4ZmNiYjRlNmExNTVjNjFmYmI2OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D_e0nSWh8Ti7RQ-K-4sIL4hWxo06GHDfpP8abGwVfGA) only one model
> 
> 1. For this screen shot, which agent is it?
> 2. Can you go to Azure OpenAI studio(the page in your first screenshot), select the `gpt-35` model, then click on "Open in Playground". On the playground page, middle panel click on "View code", you should see the settings of the model look like this:
> 
> ```
> openai.api_type = "azure"
> openai.api_base = "https://xxxxxxx.openai.azure.com/"
> openai.api_version = "xxxxxx"
> openai.api_key = ......
> ```
> 
> Can you confirm they are the same as what you put in the second screenshot?
> 
> 3. Still in "View code", line 14, there's "engine" which should match the name you put in the second screenshot. Can you also confirm that?

@lz-chen Can you try deleting the default models and add your new model? Are you able to follow step 2 and 3 in this comment to verify your configs are correct?
