### ISSUE TITLE
[AutoGen Studio]: I have installed AutoGen Studio on Windows machine, but samples are not working

### ISSUE THREAD

**Issue by ashbhati** [microsoft/autogen#1350]
### Describe the issue

userproxy (to visualization_assistant):

paint a picture of a glass of ethiopian coffee, freshly brewed in a tall glass cup, on a table right in front of a lush green forest scenery

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_backends\sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\socket.py", line 844, in create_connection
    raise err
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_transports\default.py", line 67, in map_httpcore_exceptions
    yield
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_transports\default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection_pool.py", line 268, in handle_request
    raise exc
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_backends\sync.py", line 213, in connect_tcp
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\openai\_base_client.py", line 885, in _request
    response = self._client.send(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_client.py", line 915, in send
    response = self._send_handling_auth(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_transports\default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_transports\default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_backends\sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\socket.py", line 844, in create_connection
    raise err
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_transports\default.py", line 67, in map_httpcore_exceptions
    yield
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_transports\default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection_pool.py", line 268, in handle_request
    raise exc
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_backends\sync.py", line 213, in connect_tcp
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\openai\_base_client.py", line 885, in _request
    response = self._client.send(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_client.py", line 915, in send
    response = self._send_handling_auth(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_transports\default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_transports\default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_backends\sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\socket.py", line 844, in create_connection
    raise err
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_transports\default.py", line 67, in map_httpcore_exceptions
    yield
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_transports\default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection_pool.py", line 268, in handle_request
    raise exc
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection.py", line 99, in handle_request
    raise exc
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_sync\connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_backends\sync.py", line 213, in connect_tcp
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\openai\_base_client.py", line 885, in _request
    response = self._client.send(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_client.py", line 915, in send
    response = self._send_handling_auth(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_transports\default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\httpx\_transports\default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\autogenstudio\web\app.py", line 68, in add_message
    response_message: Message = chatmanager.chat(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\autogenstudio\chatmanager.py", line 29, in chat
    flow.run(message=f"{message_text}", clear_history=False)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\autogenstudio\workflowmanager.py", line 191, in run
    self.sender.initiate_chat(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\autogen\agentchat\conversable_agent.py", line 672, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\autogen\agentchat\conversable_agent.py", line 420, in send
    recipient.receive(message, self, request_reply, silent)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\autogen\agentchat\conversable_agent.py", line 578, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\autogen\agentchat\conversable_agent.py", line 1241, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\autogen\agentchat\conversable_agent.py", line 761, in generate_oai_reply
    response = client.create(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\autogen\oai\client.py", line 266, in create
    response = self._completions_create(client, params)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\autogen\oai\client.py", line 531, in _completions_create
    response = completions.create(**params)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\openai\_utils\_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\openai\resources\chat\completions.py", line 648, in create
    return self._post(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\openai\_base_client.py", line 1167, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\openai\_base_client.py", line 856, in request
    return self._request(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\openai\_base_client.py", line 909, in _request
    return self._retry_request(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\openai\_base_client.py", line 980, in _retry_request
    return self._request(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\openai\_base_client.py", line 909, in _request
    return self._retry_request(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\openai\_base_client.py", line 980, in _retry_request
    return self._request(
  File "C:\Users\ashbhati\AppData\Local\anaconda3\envs\autogen\lib\site-packages\openai\_base_client.py", line 919, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

INFO:     127.0.0.1:54846 - "POST /api/messages HTTP/1.1" 200 OK

### Steps to reproduce

I have installed AutoGen Studio on a windows machine and the installation went fine. I assigned OPENAI_API_KEY as well. The AutoGen launches successfully, but I fail to run any samples. Logs from the Anaconda Prompt attached.

### Additional Information

Python 3.9

**Comment by ekzhu** [comment]
Looks like you have error connecting to OpenAI. Can you check if your api key is correct?

**Comment by victordibia** [comment]
@ashbhati, 
You can either set your key as an env variable or add it in the UI. 
Can you confirm that you have added your api key to the agents in your workflow?

**Comment by cavs1010** [comment]
Hi @victordibia,
I am having the same issue. I can confirm that I have set the key as an env variable and added it to the UI, in case that was the error. I also tried turning off the firewall, but I am still getting the same error.

**Comment by e404nothing** [comment]
I am also getting this error

**Comment by NuWattHQ** [comment]
Same issue here

**Comment by cavs1010** [comment]
Hi,
I solved the error, but I forgot to post it back. The error was simple; I didn't have enough balance in my ChatGPT API. I charged it with $10, and now it's working again. :)
