### ISSUE TITLE
[Issue]: AttributeError: module 'autogen' has no attribute 'Agent'

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [microsoft/autogen#1398]
### Describe the issue

I attempted to uninstall or reinstall to ensure it is updated and now getting the error listed in this ticket

### Steps to reproduce

delete the enviroment
setup new enviroment
using python 3.11
install autogen pip
install autogenstudio pip

same issue

was working just find

### Screenshots and logs

![image](https://github.com/microsoft/autogen/assets/77267159/2aeccb12-6c37-4e4e-b446-43f849a77fa4)

(N3XUS) PS C:\Users\MindExpander> autogenstudio ui --port 8081
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\MindExpander\.conda\envs\N3XUS\Scripts\autogenstudio.exe\__main__.py", line 4, in <module>
  File "C:\Users\MindExpander\AppData\Roaming\Python\Python311\site-packages\autogenstudio\__init__.py", line 1, in <module>
    from .chatmanager import *
  File "C:\Users\MindExpander\AppData\Roaming\Python\Python311\site-packages\autogenstudio\chatmanager.py", line 6, in <module>
    from .workflowmanager import AutoGenWorkFlowManager
  File "C:\Users\MindExpander\AppData\Roaming\Python\Python311\site-packages\autogenstudio\workflowmanager.py", line 9, in <module>
    class AutoGenWorkFlowManager:
  File "C:\Users\MindExpander\AppData\Roaming\Python\Python311\site-packages\autogenstudio\workflowmanager.py", line 141, in AutoGenWorkFlowManager
    def load(self, agent_spec: AgentFlowSpec) -> autogen.Agent:
                                                 ^^^^^^^^^^^^^
AttributeError: module 'autogen' has no attribute 'Agent'
(N3XUS) PS C:\Users\MindExpander>

### Additional Information

Please let me know any more information you need it is windows 10 python 3.11

**Comment by TheMindExpansionNetwork** [comment]
(base) PS C:\Users\MindExpander> autogenstudio ui --port 8081
autogenstudio : The term 'autogenstudio' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ autogenstudio ui --port 8081
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (autogenstudio:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

(base) PS C:\Users\MindExpander>

Get this to if it helps

**Comment by TheMindExpansionNetwork** [comment]
FIXXXXED: DELETED AND REINSTALL PYTHON 3.11
