### ISSUE TITLE
Use appropriate wait time for retry based on the error message. 

### ISSUE THREAD

**Issue by ekzhu** [microsoft/autogen#14]
```
[flaml.autogen.oai.completion: 05-11 00:50:35] {217} INFO - retrying in 10 seconds...
Traceback (most recent call last):
  File "[...\.venv\Lib\site-packages\flaml\autogen\oai\completion.py]", line 193, in _get_response
    response = openai_completion.create(request_timeout=request_timeout, **config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...\.venv\Lib\site-packages\openai\api_resources\completion.py]", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...\.venv\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py]", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "[...\.venv\Lib\site-packages\openai\api_requestor.py]", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...\.venv\Lib\site-packages\openai\api_requestor.py]", line 620, in _interpret_response
    self._interpret_response_line(
  File "[...\.venv\Lib\site-packages\openai\api_requestor.py]", line 683, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Requests to the Completions_Create Operation under Azure OpenAI API version 2022-12-01 have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 59 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.
[flaml.autogen.oai.completion: 05-11 00:50:45] {217} INFO - retrying in 10 seconds...
```

The error message says "Please retry after 59 seconds", but FLAML keeps retrying in 10-second intervals.

**Comment by Pavel-hb** [comment]
I also get this error:

--------------------------------------------------------------------------------
[autogen.oai.completion: 09-27 12:50:43] {236} INFO - retrying in 10 seconds...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autogen/oai/completion.py", line 206, in _get_response
    response = openai_completion.create(**config)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-6oXqS68sE8UL8MSONa3w2IpY on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.
INFO:autogen.oai.completion:retrying in 10 seconds...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autogen/oai/completion.py", line 206, in _get_response
    response = openai_completion.create(**config)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: Rate limit reached for default-gpt-3.5-turbo in organization org-6oXqS68sE8UL8MSONa3w2IpY on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.

**Comment by RobertWeaver** [comment]
Is there a configuration to set the max numbers of requests that can be made per minute? This would help to avoid hitting rate limits for Requests Per Minute. 😅

**Comment by sonichi** [comment]
@Pavel-hb @RobertWeaver I added some answers in #53 . Could you take a look and let me know if it answers your question?

**Comment by raghavgrover13** [comment]
I also observed the same behavior that retry occurs with 10 seconds, it definitely should retry based on the time in the error message.
Also is there a way to dynamically reduce max token limit? I have seen in some instances with GPT 3.5 Turbo 16k that the output in one chat goes beyond the token limit- one should calculate the token count in system and user prompt and then set max token based on the model - max token limit- the token used in user prompt and system prompt?

**Comment by kevin666aa** [comment]
> The retry time behavior has been changed in v0.2. https://microsoft.github.io/autogen/docs/Installation#python Dynamically reducing max tokens is an idea @kevin666aa may want to take a note.

The "dynamic reducing max tokens", "calculate the token count in system and user prompt" are already the features of CompressibeAgent. @raghavgrover13 Can you check out https://github.com/microsoft/autogen/blob/main/notebook/agentchat_compression.ipynb to see if it addresses your issue?
