### ISSUE TITLE
[Feature Request]: "Test" button for Models

### ISSUE THREAD

**Issue by gwsii** [microsoft/autogen#1404]
### Is your feature request related to a problem? Please describe.

I'd like to be able to validate my model configuration without the extra work of creating an agent or workflow.

### Describe the solution you'd like

While editing or creating a new Model, there's a "Test" button that takes the current configuration as entered and sends a test message to the model to validate that the configuration is working.

**Comment by victordibia** [comment]
@gwsii 

Agreed. I think this will help improve the UX. 
Adding this to the autogenstudio roadmap #737

**Comment by victordibia** [comment]
Addressed in the autogenstudio dev branch. 

You can update autogenstudio to test out this feature.

- pip uninstall autogenstudio 
- pip install -U autogenstudio 
- autogenstudio ui --appdir newdir 

the last command tells autogenstudio to use `newdir` to store files including creating a new db.

https://github.com/microsoft/autogen/assets/1547007/54bf4cb7-67c3-475b-b52c-3f640dcc2de5

**Comment by victordibia** [comment]
Closing as this has been addressed.
Feel free to reopen as needed @gwsii

**Comment by airtonix** [comment]
> autogenstudio ui --appdir newdir

You guys should totes write this as **the.first.thing.** that users are shown in the getting started documentation.

**Comment by airtonix** [comment]
btw, after running: 

```console
cd /mnt/Store/Applications
mkdir myautogenstudio
poetry init
poetry shell
poetry add autogenstudio
OPENAI_API_KEY=sk-XXXXXXXXXXXXXX autogenstudio --appdir ./data
```

- run with my openai key
- the app server starts
- i load the ui in the browser
- goto build > models
- "lets test a model?"

this happens: I just get 500 errors

[Kooha-2024-02-04-10-44-12.webm](https://github.com/microsoft/autogen/assets/61225/af3c8acf-754c-4041-8040-28122c7b8c7f)

- i try without apikey there (but rely on the api key i defined as ENVVAR)
- i then try pasting the same apikey. same result.


error is 
```console
INFO:     127.0.0.1:50804 - "POST /api/models/test HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 485, in handle
    await self.app(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 315, in app
    content = await serialize_response(
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 180, in serialize_response
    return jsonable_encoder(response_content)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/fastapi/encoders.py", line 223, in jsonable_encoder
    obj_dict = _model_dump(
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/fastapi/_compat.py", line 177, in _model_dump
    return model.model_dump(mode=mode, **kwargs)
  File "/home/zenobius/.cache/pypoetry/virtualenvs/autogenstudio-uq9iOOK3-py3.10/lib/python3.10/site-packages/pydantic/main.py", line 314, in model_dump
    return self.__pydantic_serializer__.to_python(
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'method'>
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
```

**Comment by victordibia** [comment]
Taking a look. 
Will update shortly.

**Comment by victordibia** [comment]
It looks like a validation issue with the response type returned by pydantic (an error I have not seen before). 
Any chance you are running pydantic in strict mode? That will help with debugging on this end.
Also, I am adding a fix to ensure the response from /models/test has objects that serialize correctly.

**Comment by victordibia** [comment]
Edit: I pushed an update to the library .. upgrade - v0.0.43a to address this.

```bash
pip install -U autogenstudio
```

Let me know if you are still seeing that error.
