### ISSUE TITLE
[Bug]:  Running local OpenAI comaptible LLM server

### ISSUE THREAD

**Issue by NeoTech** [microsoft/autogen#1413]
### Describe the bug

Connecting to a local server like LM Studio running a openai compatible server with no API key definition you run into an error saying: TypeError: Completions.create() got an unexpected keyword argument 'api_type'

### Steps to reproduce

Install LM studio
Start LM Studios webserver
Create new model in Autogen studio
Associate workflow with new model
Goto playground, ask it to tell a joke

### Expected Behavior

Should connect

### Screenshots and logs

 >> llm config {'id': '1c05a93d-a963-4ab4-a732-af5ea1b18a07', 'user_id': 'guestuser@gmail.com', 'timestamp': '2024-01-26T14:48:09.426357', 'model': 'Zephyr', 'api_key': 'None', 'base_url': 'http://localhost:1234/v1', 'api_type': 'openai', 'api_version': None, 'description': 'Sample model'}
 >> llm config {'id': '1c05a93d-a963-4ab4-a732-af5ea1b18a07', 'user_id': 'guestuser@gmail.com', 'timestamp': '2024-01-26T14:48:09.426357', 'model': 'Zephyr', 'api_key': 'None', 'base_url': 'http://localhost:1234/v1', 'api_type': 'openai', 'api_version': None, 'description': 'Sample model'}
userproxy (to primary_assistant):

Tell me a joke

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "K:\LLM\autogen\venv\lib\site-packages\autogenstudio\web\app.py", line 69, in add_message
    response_message: Message = chatmanager.chat(
  File "K:\LLM\autogen\venv\lib\site-packages\autogenstudio\chatmanager.py", line 30, in chat
    flow.run(message=f"{message_text}", clear_history=False)
  File "K:\LLM\autogen\venv\lib\site-packages\autogenstudio\workflowmanager.py", line 210, in run
    self.sender.initiate_chat(
  File "K:\LLM\autogen\venv\lib\site-packages\autogen\agentchat\conversable_agent.py", line 621, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "K:\LLM\autogen\venv\lib\site-packages\autogen\agentchat\conversable_agent.py", line 398, in send
    recipient.receive(message, self, request_reply, silent)
  File "K:\LLM\autogen\venv\lib\site-packages\autogen\agentchat\conversable_agent.py", line 551, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "K:\LLM\autogen\venv\lib\site-packages\autogen\agentchat\conversable_agent.py", line 1191, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "K:\LLM\autogen\venv\lib\site-packages\autogen\agentchat\conversable_agent.py", line 708, in generate_oai_reply
    response = client.create(
  File "K:\LLM\autogen\venv\lib\site-packages\autogen\oai\client.py", line 261, in create
    response = self._completions_create(client, params)
  File "K:\LLM\autogen\venv\lib\site-packages\autogen\oai\client.py", line 359, in _completions_create
    response = completions.create(**params)
  File "K:\LLM\autogen\venv\lib\site-packages\openai\_utils\_utils.py", line 272, in wrapper
    return func(*args, **kwargs)
TypeError: Completions.create() got an unexpected keyword argument 'api_type'

INFO:     127.0.0.1:56719 - "POST /api/messages HTTP/1.1" 200 OK

### Additional Information

Latest updated all of em  as of today 2024-01-26

**Comment by victordibia** [comment]
@NeoTech ,

Thanks for this. 
AutoGen standardizes on the openai api format. It also assumes the model provided is an openai model and will attempt to fetch an OAI key from the env if not is specified in llm config. 

From AutoGen Studio, will it be helpful if we add a warning letting users know that the openai api key will be used if they provide none?

**Comment by qingyun-wu** [comment]
Closing this issue due to inactivity. @NeoTech  If you have further questions, please open a new issue or join the discussion in AutoGen Discord server: https://discord.com/invite/Yb5gwGVkE5
