### ISSUE TITLE
[Issue]: cannot import name 'OpenAIWrapper' from 'autogen

### ISSUE THREAD

**Issue by SynTia-OI** [microsoft/autogen#1498]
### Describe the issue

I can not locate the OpenAiWrapper in Autogen.

I am currently experiencing an issue with the autogen package (version 1.0.16). Despite successful installation, I am unable to locate the OpenAIWrapper class within the package structure. My attempts to find it in the GitHub repository also returned no results. I believe this class is critical for my project's integration with the OpenAI API.

Could you please provide guidance on where I can find OpenAIWrapper, or confirm if it is included in the current version of the package? If it has been moved or renamed, could you please direct me to the correct module or provide the updated usage

**Comment by victordibia** [comment]
Can you share some of your code and full error log?
- OpenAIWrapper is defined [here](https://github.com/microsoft/autogen/blob/8dc5c77702f8b222072df317f20b721edc1d76f6/autogen/oai/client.py#L55).
- Docs [here](https://microsoft.github.io/autogen/docs/reference/oai/client#openaiwrapper-objects)

**Comment by AkashKulkarni4444** [comment]
I think the import statement is incorrect.
In conversable_agent.py
instead of 
from .. import OpenAIWrapper
there should be
from ..oai.client import OpenAIWrapper

**Comment by AkashKulkarni4444** [comment]
### Update: 
I tried it after changing the import statement and it is working.

### Error logs that were shown earlier:
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/testApp/main.py", line 3, in <module>
    from chatBot import main as chatBotMain
  File "/testApp/chatBot/main.py", line 17, in <module>
    import autogen.agentchat as autogenAgent
  File "/usr/local/lib/python3.11/site-packages/autogen/agentchat/__init__.py", line 2, in <module>
    from .assistant_agent import AssistantAgent
  File "/usr/local/lib/python3.11/site-packages/autogen/agentchat/assistant_agent.py", line 3, in <module>
    from .conversable_agent import ConversableAgent
  File "/usr/local/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 11, in <module>
    from .. import OpenAIWrapper
ImportError: cannot import name 'OpenAIWrapper' from 'autogen' (/usr/local/lib/python3.11/site-packages/autogen/__init__.py)

@SynTia-OI please respond and confirm that you are facing the same problem ?

@victordibia please change the import statement as mentioned in the above comment.

**Comment by ekzhu** [comment]
> I am currently experiencing an issue with the autogen package (version 1.0.16)

our package is pyautogen and our current version is 0.2.9

**Comment by AkashKulkarni4444** [comment]
@ekzhu 
I am also facing the same issue with pyautogen 0.2.9

> > I am currently experiencing an issue with the autogen package (version 1.0.16)
> 
> our package is pyautogen and our current version is 0.2.9

**Comment by AkashKulkarni4444** [comment]
I have given the solution for this in my 1st comment .
I don't know how long it will take for autogen to update this but you can use it as a fix for now. 
Just go to wherever you have your autogen installed .
Then follow this:

> I think the import statement is incorrect. 
>In conversable_agent.py instead of 
>from .. import OpenAIWrapper 
>there should be 
>from ..oai.client import OpenAIWrapper

**Comment by SynTia-OI** [comment]
Thank you, I updated the import statement to this and it is working.

from ..oai.client import OpenAIWrapper
