### ISSUE TITLE
[Bug]: Unable to Build the Website in Codespaces

### ISSUE THREAD

**Issue by gagb** [microsoft/autogen#1502]
### Describe the bug

If I open the repo in Codespaces and build the website using the instructions in `Contribute.md`, I get the following error:

```console

[INFO] Starting the development server...
[ERROR] Loading of version failed for version current

Error: Invalid sidebar file at "sidebars.js".
These sidebar document ids do not exist:
- llm_endpoint_configuration

Available document ids are:
- Contribute
- Ecosystem
- Examples
- FAQ
- Gallery
- Getting-Started
- Migration-Guide
- Research
- Use-Cases/agent_chat
- Use-Cases/enhanced_inference
- installation/Docker
- installation/Installation
- installation/Optional-Dependencies
- reference/agent_utils
- reference/agentchat/agent
- reference/agentchat/assistant_agent
- reference/agentchat/contrib/agent_builder
- reference/agentchat/contrib/capabilities/agent_capability
- reference/agentchat/contrib/capabilities/teachability
- reference/agentchat/contrib/compressible_agent
- reference/agentchat/contrib/gpt_assistant_agent
- reference/agentchat/contrib/img_utils
- reference/agentchat/contrib/llava_agent
- reference/agentchat/contrib/math_user_proxy_agent
- reference/agentchat/contrib/multimodal_conversable_agent
- reference/agentchat/contrib/qdrant_retrieve_user_proxy_agent
- reference/agentchat/contrib/retrieve_assistant_agent
- reference/agentchat/contrib/retrieve_user_proxy_agent
- reference/agentchat/contrib/society_of_mind_agent
- reference/agentchat/contrib/text_analyzer_agent
- reference/agentchat/contrib/web_surfer
- reference/agentchat/conversable_agent
- reference/agentchat/groupchat
- reference/agentchat/user_proxy_agent
- reference/browser_utils
- reference/cache/abstract_cache_base
- reference/cache/cache
- reference/cache/cache_factory
- reference/cache/disk_cache
- reference/cache/redis_cache
- reference/code_utils
- reference/function_utils
- reference/math_utils
- reference/oai/client
- reference/oai/completion
- reference/oai/openai_utils
- reference/retrieve_utils
- reference/token_count_utils

    at Object.checkSidebarsDocIds (/workspaces/autogen/website/node_modules/@docusaurus/plugin-content-docs/lib/sidebars/utils.js:243:19)
    at doLoadVersion (/workspaces/autogen/website/node_modules/@docusaurus/plugin-content-docs/lib/index.js:112:31)
    at async loadVersion (/workspaces/autogen/website/node_modules/@docusaurus/plugin-content-docs/lib/index.js:129:28)
    at async Promise.all (index 0)
    at async Object.loadContent (/workspaces/autogen/website/node_modules/@docusaurus/plugin-content-docs/lib/index.js:137:33)
    at async /workspaces/autogen/website/node_modules/@docusaurus/core/lib/server/plugins/index.js:35:25
    at async Promise.all (index 0)
    at async loadPlugins (/workspaces/autogen/website/node_modules/@docusaurus/core/lib/server/plugins/index.js:34:27)
    at async load (/workspaces/autogen/website/node_modules/@docusaurus/core/lib/server/index.js:76:58)
    at async Command.start (/workspaces/autogen/website/node_modules/@docusaurus/core/lib/commands/start.js:44:19)

[INFO] Docusaurus version: 3.1.0
Node version: v18.19.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to reproduce

1. Open the repo on main in Codespaces
2. Run the following code
```console
npm install --global yarn  # skip if you use the dev container we provided
pip install pydoc-markdown  # skip if you use the dev container we provided
cd website
yarn install --frozen-lockfile --ignore-engines
pydoc-markdown
yarn start
```

**Comment by gagb** [comment]
cc. @jackgerrits & @ekzhu

**Comment by victordibia** [comment]
I am looking at the documenation 

```
pydoc-markdown
quarto render ./docs
yarn start
``` 

@gagb Can you confirm if you ran `quarto render ./docs` ?



![Image](https://github.com/microsoft/autogen/assets/1547007/29b0c6f6-2bee-4141-8c7f-d6c55aa2ad5b)

**Comment by gagb** [comment]
Yes I followed the instructions in Contribute.md for building. Ty for fixing it @victordibia

**Comment by gagb** [comment]
Instructions for installing quarto are missing in Contribute.md @jackgerrits @victordibia  -- I am still not able to use our base container to build the website :/

Ran instructions from here:

```
npm install --global yarn  # skip if you use the dev container we provided
pip install pydoc-markdown  # skip if you use the dev container we provided
cd website
yarn install --frozen-lockfile --ignore-engines
pydoc-markdown
quarto render ./docs
yarn start
```

**Comment by jackgerrits** [comment]
ill submit a fix!

**Comment by gagb** [comment]
> ill submit a fix!

@jackgerrits can we add quarto to the base container? Its otherwise really slow to review any website related PRs.

**Comment by victordibia** [comment]
Yes Gagan, go ahead and add it if you are blocked! 
I can review.

**Comment by jackgerrits** [comment]
Sorry dropped the ball on that one - just open a quick little bandaid for contribute.md. #1585
