### ISSUE TITLE
[Bug]: Error with Pydantic 2.6 when using open source models

### ISSUE THREAD

**Issue by alew3** [microsoft/autogen#1527]
### Describe the bug

I get an error 
**"pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'method'>"**

 when trying to test an open source model.

Using the latest versions:
- autogenstudio             0.0.42a0
- pyautogen                 0.2.10
-  pydatinc 2.6.0

But works when downgrading to pydantic 1.10.14!

### Screenshots and logs

<img width="1002" alt="image" src="https://github.com/microsoft/autogen/assets/500714/680240b0-94a8-4d62-9562-c1900a644201">

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/routing.py", line 443, in handle
    await self.app(scope, receive, send)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/fastapi/routing.py", line 292, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/fastapi/routing.py", line 180, in serialize_response
    return jsonable_encoder(response_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/fastapi/encoders.py", line 287, in jsonable_encoder
    encoded_value = jsonable_encoder(
                    ^^^^^^^^^^^^^^^^^
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/fastapi/encoders.py", line 223, in jsonable_encoder
    obj_dict = _model_dump(
               ^^^^^^^^^^^^
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/fastapi/_compat.py", line 177, in _model_dump
    return model.model_dump(mode=mode, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ale/anaconda3/envs/python311/lib/python3.11/site-packages/pydantic/main.py", line 308, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'method'>

**Comment by victordibia** [comment]
Hi @alew3 ,

Thanks for adding this. The error seems to be related to pydantic not being able to correctly serialize response object from the model endpoint (when in strict mode)
I just pushed a fix that simplifies the returned object. Please upgrade you autogenstudio and let me know if you are still facing that issue.

```bash
pip install -U autogenstudio
```

**Comment by alew3** [comment]
Thanks @victordibia , just tested and it is working fine!

**Comment by victordibia** [comment]
@alew3 
Thanks for following up and closing this out!
