### ISSUE TITLE
[Bug]: Traceback (most recent call last):   File "/root/autodl-tmp/autogen.py", line 4, in <module>     import autogen   File "/root/autodl-tmp/autogen.py", line 5, in <module>     from autogen.agentchat.contrib.qdrant_retrieve_user_proxy_agent import QdrantRetrieveUserProxyAgent ModuleNotFoundError: No module named 'autogen.agentchat'; 'autogen' is not a package

### ISSUE THREAD

**Issue by Lux0926** [microsoft/autogen#1679]
### Describe the bug

Traceback (most recent call last):
  File "/root/autodl-tmp/autogen.py", line 4, in <module>
    import autogen
  File "/root/autodl-tmp/autogen.py", line 5, in <module>
    from autogen.agentchat.contrib.qdrant_retrieve_user_proxy_agent import QdrantRetrieveUserProxyAgent
ModuleNotFoundError: No module named 'autogen.agentchat'; 'autogen' is not a package

**Comment by Qausts** [comment]
Traceback (most recent call last):
  File "/root/autodl-tmp/ChatGLM-6B-main/cli_demo.py", line 58, in <module>
    main()
  File "/root/autodl-tmp/ChatGLM-6B-main/cli_demo.py", line 51, in main
    print(build_prompt(history), flush=True)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/ChatGLM-6B-main/cli_demo.py", line 18, in build_prompt
    for query, response in history:
        ^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
这种问题该怎样处理呢
