### ISSUE TITLE
Getting error while trying to run against Azure OpenAI Deployments

### ISSUE THREAD

**Issue by faizanbashir** [microsoft/autogen#171]
I am getting the below error when running the `twoagent.py` test file. I am using Azure OpenAI, and my `OAI_CONFIG_LIST` looks something like this:

```json
[
    {
        "model": "gpt-3.5-turbo",
        "api_type": "azure",
        "api_key": "<azure_oai_api_key>",
        "api_base": "https://<azure_oai_resource>.openai.azure.com/openai/deployments/<azure_oai_deployment_name>/",
        "api_version": "2023-08-01-preview"
    }
]
```
I have installed the required packages and get the below error when trying to run:

```python
$ python test/twoagent.py
user_proxy (to assistant):

Plot a chart of NVDA and TESLA stock price change YTD.

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/telifaizan/Code/honeywell/global/genai/autogen/test/twoagent.py", line 9, in <module>
    user_proxy.initiate_chat(assistant, message="Plot a chart of NVDA and TESLA stock price change YTD.")
  File "/usr/local/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 531, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/usr/local/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "/usr/local/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 462, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 779, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 606, in generate_oai_reply
    response = oai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/autogen/oai/completion.py", line 781, in create
    response = cls.create(
               ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/autogen/oai/completion.py", line 812, in create
    return cls._get_response(params, raise_on_ratelimit_or_timeout=raise_on_ratelimit_or_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/autogen/oai/completion.py", line 209, in _get_response
    response = openai_completion.create(request_timeout=request_timeout, **config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: Resource not found
```

The same works fine when I try to run a `curl` command against the Azure OpenAI deployment using the `api_key` and `api_base`.

```shell
$ curl https://<azure_oai_resource>.openai.azure.com/openai/deployments/<azure_oai_deployment_name>/completions?api-version=2023-08-01-preview \
 -H "Content-Type: application/json" \
 -H "api-key: <azure_oai_api_key>" \
 -d "{ \"prompt\": \"Once upon a time\", \"max_tokens\": 5 }"
```

**Comment by thinkall** [comment]
Hi @faizanbashir , please try replace model name with your azure_oai_deployment_name, maybe `gpt-35-turbo`. Or replace `model` with `engine`.
```
[
    {
        "model": "gpt-3.5-turbo",
        "api_type": "azure",
        "api_key": "<azure_oai_api_key>",
        "api_base": "https://<azure_oai_resource>.openai.azure.com/openai/deployments/<azure_oai_deployment_name>/",
        "api_version": "2023-08-01-preview"
    }
]
```

**Comment by faizanbashir** [comment]
> Hi @faizanbashir , please try replace model name with your azure_oai_deployment_name, maybe `gpt-35-turbo`. Or replace `model` with `engine`.
> 
> ```
> [
>     {
>         "model": "gpt-3.5-turbo",
>         "api_type": "azure",
>         "api_key": "<azure_oai_api_key>",
>         "api_base": "https://<azure_oai_resource>.openai.azure.com/openai/deployments/<azure_oai_deployment_name>/",
>         "api_version": "2023-08-01-preview"
>     }
> ]
> ```

Thanks for the suggestion. The below two steps fixed the problem:

1. Updating the `model` value to the `<azure_oai_deployment_name>`.
2. Updating the `api_base` to `https://<azure_oai_resource>.openai.azure.com/`

The final `OAI_CONFIG_LIST` looks like below:

```json
[
    {
        "model": "<azure_oai_deployment_name>",
        "api_type": "azure",
        "api_key": "<azure_oai_api_key>",
        "api_base": "https://<azure_oai_resource>.openai.azure.com/",
        "api_version": "2023-08-01-preview"
    }
]
```
