### ISSUE TITLE
[Bug]: tools execution gets an error after a while - tool_responses was unexpected

### ISSUE THREAD

**Issue by AsafEitani** [microsoft/autogen#1719]
### Describe the bug

I'm executing a multi agent group chat with autogen, giving some of the agents specific tools.
When I execute the tool execution works a few times but then I receive the following error:
```
***** Suggested tool Call (call_6ogwDmVI1mXUcWwlMBDn3gnw): build_docker_image *****
Arguments: 
{
  "dockerfile_path": "Dockerfile",
  "image_name": "image",
  "tag": "latest"
}
***********************************************************************************

--------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/eitani/projects/deepsea/main.py", line 43, in <module>
    user_proxy.initiate_chat(
  File "/home/eitani/.local/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py", line 747, in initiate_chat
    summary = self._summarize_chat(
  File "/home/eitani/.local/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py", line 836, in _summarize_chat
    summary = self._llm_response_preparer(prompt, msg_list, llm_agent=agent, cache=cache)
  File "/home/eitani/.local/lib/python3.8/site-packages/autogen/agentchat/conversable_agent.py", line 876, in _llm_response_preparer
    response = llm_client.create(context=None, messages=_messages, cache=cache)
  File "/home/eitani/.local/lib/python3.8/site-packages/autogen/oai/client.py", line 583, in create
    response = client.create(params)
  File "/home/eitani/.local/lib/python3.8/site-packages/autogen/oai/client.py", line 267, in create
    response = completions.create(**params)
  File "/home/eitani/.local/lib/python3.8/site-packages/openai/_utils/_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
  File "/home/eitani/.local/lib/python3.8/site-packages/openai/resources/chat/completions.py", line 659, in create
    return self._post(
  File "/home/eitani/.local/lib/python3.8/site-packages/openai/_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/eitani/.local/lib/python3.8/site-packages/openai/_base_client.py", line 889, in request
    return self._request(
  File "/home/eitani/.local/lib/python3.8/site-packages/openai/_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Additional properties are not allowed ('tool_responses' was unexpected) - 'messages.6'", 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

That same tool worked a few messages ago.

### Steps to reproduce

I have no clue, it just happens after about 5 tool usages.

### Expected Behavior

Tool successful execution

### Screenshots and logs

provided above.

**Comment by sonichi** [comment]
Do you have an endpoint in any agent's `llm_config` which doesn't allow tool use?

**Comment by AsafEitani** [comment]
I'm using OpenAI `gpt-4` ,model

**Comment by sonichi** [comment]
No obvious reason I can think of. Would you like to share a reproducible example for others to try?

**Comment by AsafEitani** [comment]
Well it fixed itself and I can't reproduce.
If it will happen again I'll reopen.
Thanks for the replies!
