### ISSUE TITLE
[Bug]: PowerShell existence test broken on Mac

### ISSUE THREAD

**Issue by lestan** [microsoft/autogen#1947]
### Describe the bug

Autogen 0.2.17 breaks on Mac due to failure in test that verifies existence of PowerShell.  The issue seems to be that Python throws a **NotADirectoryError**, but the try block is only testing for a **FileNotFoundError**

Code error is in autogen/code_utils.py, line 218 in get_powershell_command:

```python
def get_powershell_command():
    try:
        result = subprocess.run(["powershell", "$PSVersionTable.PSVersion.Major"], capture_output=True, text=True)
        if result.returncode == 0:
            return "powershell"

    except FileNotFoundError:
        # This means that 'powershell' command is not found so now we try looking for 'pwsh'
        try:
            result = subprocess.run(
                ["pwsh", "-Command", "$PSVersionTable.PSVersion.Major"], capture_output=True, text=True
            )
            if result.returncode == 0:
                return "pwsh"

        except FileNotFoundError:
            if WIN32:
                logging.warning("Neither powershell nor pwsh is installed but it is a Windows OS")
            return None
```

Error from Python is:

```bash
Traceback (most recent call last):
  File "/Users/lestan/Projects/Python/learn-autogen/learn_autogen/basic_agent.py", line 2, in <module>
    from autogen import AssistantAgent, UserProxyAgent
  File "/Users/lestan/Projects/Python/learn-autogen/.venv/lib/python3.11/site-packages/autogen/__init__.py", line 4, in <module>
    from .agentchat import *
  File "/Users/lestan/Projects/Python/learn-autogen/.venv/lib/python3.11/site-packages/autogen/agentchat/__init__.py", line 2, in <module>
    from .assistant_agent import AssistantAgent
  File "/Users/lestan/Projects/Python/learn-autogen/.venv/lib/python3.11/site-packages/autogen/agentchat/assistant_agent.py", line 3, in <module>
    from .conversable_agent import ConversableAgent
  File "/Users/lestan/Projects/Python/learn-autogen/.venv/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 14, in <module>
    from ..coding.base import CodeExecutor
  File "/Users/lestan/Projects/Python/learn-autogen/.venv/lib/python3.11/site-packages/autogen/coding/__init__.py", line 3, in <module>
    from .markdown_code_extractor import MarkdownCodeExtractor
  File "/Users/lestan/Projects/Python/learn-autogen/.venv/lib/python3.11/site-packages/autogen/coding/markdown_code_extractor.py", line 4, in <module>
    from ..code_utils import CODE_BLOCK_PATTERN, UNKNOWN, content_str, infer_lang
  File "/Users/lestan/Projects/Python/learn-autogen/.venv/lib/python3.11/site-packages/autogen/code_utils.py", line 237, in <module>
    powershell_command = get_powershell_command()
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lestan/Projects/Python/learn-autogen/.venv/lib/python3.11/site-packages/autogen/code_utils.py", line 218, in get_powershell_command
    result = subprocess.run(["powershell", "$PSVersionTable.PSVersion.Major"], capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lestan/.pyenv/versions/3.11.7/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lestan/.pyenv/versions/3.11.7/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/lestan/.pyenv/versions/3.11.7/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'powershell'
```

### Steps to reproduce

To reproduce, run a python shell in a MacOS Terminal or VSCode Terminal and execute the same command as line 218 of autogen/code_utils.py:

```bash
Python 3.11.7 (main, Dec 22 2023, 20:31:58) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.run(["powershell", "$PSVersionTable.PSVersion.Major"], capture_output=True, text=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lestan/.pyenv/versions/3.11.7/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lestan/.pyenv/versions/3.11.7/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/lestan/.pyenv/versions/3.11.7/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'powershell'
```

### Expected Behavior

Not sure exactly, but my expectation is that line autogen/code_utils.py:237 should return a meaningful return value that indicates that powershell does not exist on the Mac platform.

Also, get_powershell_command() should catch error NotADirectoryError as that is what python is throwing, not FileNotFoundError

### Additional Information

AutoGen Version: 0.2.17
Operating System: Sonoma 14.2.1 
Python Version: 3.11.7

**Comment by sonichi** [comment]
@jackgerrits fyi

**Comment by abhaymathur21** [comment]
I'll make a PR to fix this right away

**Comment by abhaymathur21** [comment]
> Also, get_powershell_command() should catch error NotADirectoryError as that is what python is throwing, not FileNotFoundError

I believe this error is occurring because on Windows there is a directory called powershell since the software is still powershell but inside that directory the command is pwsh.exe so that's why its throwing a FileNotFoundError instead of a NotADirectoryError because the path is given as /PowerShell/ in the environment variables (inside which it tries to look for a powershell.exe which it cannot find)

While in MacOS powershell doesnt even exist so its unable to find the powershell directory in the path (since only directories are listed in the path, not direct commands) so it throws a NotADirectoryError.

Thanks for bringing this up, I'll make the function deal with both these errors
