### ISSUE TITLE
[Bug]: Crash: PermissionDenied/"powershell" error on MacOS 14.3.1

### ISSUE THREAD

**Issue by realazthat** [microsoft/autogen#1961]
### Describe the bug

As soon as autogen is imported, the program crashes with a `PermissionDenied` error, for `powershell`. This is not WAI. Reason to think this is blocking significant/all MacOS users?

This is a bug filed on behalf of @brandonisagoon .

### Steps to reproduce

```bash
pip install pyautogen
python -c 'import autogen'
```

Output:

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Brandon/.pyenv/versions/3.12.2/lib/python3.12/site-packages/autogen/__init__.py", line 4, in <module>
    from .agentchat import *
  File "/Users/Brandon/.pyenv/versions/3.12.2/lib/python3.12/site-packages/autogen/agentchat/__init__.py", line 2, in <module>
    from .assistant_agent import AssistantAgent
  File "/Users/Brandon/.pyenv/versions/3.12.2/lib/python3.12/site-packages/autogen/agentchat/assistant_agent.py", line 3, in <module>
    from .conversable_agent import ConversableAgent
  File "/Users/Brandon/.pyenv/versions/3.12.2/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 14, in <module>
    from ..coding.base import CodeExecutor
  File "/Users/Brandon/.pyenv/versions/3.12.2/lib/python3.12/site-packages/autogen/coding/__init__.py", line 3, in <module>
    from .markdown_code_extractor import MarkdownCodeExtractor
  File "/Users/Brandon/.pyenv/versions/3.12.2/lib/python3.12/site-packages/autogen/coding/markdown_code_extractor.py", line 4, in <module>
    from ..code_utils import CODE_BLOCK_PATTERN, UNKNOWN, content_str, infer_lang
  File "/Users/Brandon/.pyenv/versions/3.12.2/lib/python3.12/site-packages/autogen/code_utils.py", line 237, in <module>
    powershell_command = get_powershell_command()
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Brandon/.pyenv/versions/3.12.2/lib/python3.12/site-packages/autogen/code_utils.py", line 218, in get_powershell_command
    result = subprocess.run(["powershell", "$PSVersionTable.PSVersion.Major"], capture_output=True, text=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Brandon/.pyenv/versions/3.12.2/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Brandon/.pyenv/versions/3.12.2/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/Brandon/.pyenv/versions/3.12.2/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'powershell'
```

### Model Used

N/A

### Expected Behavior

Don't crash.

### Screenshots and logs

![image](https://github.com/microsoft/autogen/assets/141522/7f0cb66b-21bd-47d5-becb-dd2e3a4736ee)

### Additional Information

* pyautogen==0.2.17
* MacOS 14.3.1
* Python Version: 3.12.2
* Any other relevant information:

The problem is happening in code_utils.py:

https://github.com/microsoft/autogen/blob/11df53bb3927d33ccfb380ef15874e40db67cceb/autogen/code_utils.py#L218

![image](https://github.com/microsoft/autogen/assets/141522/67717662-688d-423c-a07a-027520bd2f4f)

* `powershell_command` should probably not be a global.
* I dunno why MacOS is throwing a PermissionDenied error, but perhaps that should be caught in the exceptions.

Also reproduced with: 

```bash
python -c 'import subprocess; subprocess.run(["powershell", "$PSVersionTable.PSVersion.Major"], capture_output=True, text=True)'
```

Output:

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Brandon/.pyenv/versions/3.12.2/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Brandon/.pyenv/versions/3.12.2/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/Brandon/.pyenv/versions/3.12.2/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'powershell'
```

**Comment by abhaymathur21** [comment]
Ive tried to fix this in my PR, could you please take a look?

**Comment by brandonisagoon** [comment]
@ekzhu I don't have powershell installed.

**Comment by ekzhu** [comment]
@brandonisagoon are you using mac and encountering this problem without powershell?

**Comment by brandonisagoon** [comment]
@ekzhu yes. It does not produce an error when I run it in sudo. However, I can't do this in a notebook nor do I always want to run autogen in sudo.

**Comment by realazthat** [comment]
> Ive tried to fix this in my PR, could you please take a look?

Was this addressed at OP? If so, I filed this on behalf of @brandonisagoon, I don't have access to a Mac.

**Comment by realazthat** [comment]
> @realazthat I think this probably also has to do with your permission setting for the `powershell` command you installed on MacOS. So this bug affects users with powershell installed but with no permission to run it.

I filed this on behalf of @brandonisagoon .

When we were debugging this on discord, he did not have powershell installed. I am not sure why python subprocess throws a permission error, that seems mysterious.
