### ISSUE TITLE
`ModuleNotFoundError` when following the article: Use AutoGen for Local LLMs

### ISSUE THREAD

**Issue by PyroGenesis** [microsoft/autogen#207]
Hello,

I'm trying to set up AutoGen for Local LLMs by following the instructions here: https://microsoft.github.io/autogen/blog/2023/07/14/Local-LLMs

However, I immediately get stuck with an error when executing the following line
```terminal
python -m fastchat.serve.controller
```

### Error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "~\Documents\Python\autogen-fastchat\FastChat\fastchat\serve\controller.py", line 16, in <module>
    from fastapi import FastAPI, Request
ModuleNotFoundError: No module named 'fastapi'
```

### Result of `pip list`
```
Package                   Version
------------------------- ------------
accelerate                0.23.0
aiofiles                  23.2.1
aiohttp                   3.8.6
aiosignal                 1.3.1
altair                    5.1.2
annotated-types           0.6.0
anyio                     3.7.1
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.0
async-lru                 2.0.4
async-timeout             4.0.3
attrs                     23.1.0
Babel                     2.13.0
backcall                  0.2.0
beautifulsoup4            4.12.2
bleach                    6.1.0
certifi                   2022.12.7
cffi                      1.16.0
charset-normalizer        2.1.1
click                     8.1.7
colorama                  0.4.6
comm                      0.1.4
contourpy                 1.1.1
cycler                    0.12.1
datasets                  2.14.5
debugpy                   1.8.0
decorator                 5.1.1
defusedxml                0.7.1
dill                      0.3.7
diskcache                 5.6.3
dnspython                 2.4.2
email-validator           2.0.0.post2
evaluate                  0.4.0
executing                 2.0.0
fastapi                   0.103.2
fastjsonschema            2.18.1
ffmpy                     0.3.1
filelock                  3.9.0
FLAML                     2.1.1
fonttools                 4.43.1
fqdn                      1.5.1
frozenlist                1.4.0
fschat                    0.2.30
fsspec                    2023.6.0
gradio                    3.47.1
gradio_client             0.6.0
h11                       0.14.0
httpcore                  0.18.0
httptools                 0.6.0
httpx                     0.25.0
huggingface-hub           0.17.3
idna                      3.4
importlib-resources       6.1.0
ipykernel                 6.25.2
ipython                   8.16.1
ipywidgets                8.1.1
isoduration               20.11.0
itsdangerous              2.1.2
jedi                      0.19.1
Jinja2                    3.1.2
jiwer                     3.0.3
joblib                    1.3.2
json5                     0.9.14
jsonpointer               2.4
jsonschema                4.19.1
jsonschema-specifications 2023.7.1
jupyter_client            8.4.0
jupyter_core              5.4.0
jupyter-events            0.7.0
jupyter-lsp               2.2.0
jupyter_server            2.7.3
jupyter_server_terminals  0.4.4
jupyterlab                4.0.6
jupyterlab-pygments       0.2.2
jupyterlab_server         2.25.0
jupyterlab-widgets        3.0.9
jupytext                  1.15.2
kiwisolver                1.4.5
markdown-it-py            3.0.0
markdown2                 2.4.10
MarkupSafe                2.1.2
matplotlib                3.8.0
matplotlib-inline         0.1.6
mdit-py-plugins           0.4.0
mdurl                     0.1.2
mistune                   3.0.2
mpmath                    1.3.0
multidict                 6.0.4
multiprocess              0.70.15
nbclient                  0.8.0
nbconvert                 7.9.2
nbformat                  5.9.2
nest-asyncio              1.5.8
networkx                  3.0
nh3                       0.2.14
notebook_shim             0.2.3
numpy                     1.24.1
openai                    0.28.1
orjson                    3.9.8
overrides                 7.4.0
packaging                 23.2
pandas                    2.1.1
pandocfilters             1.5.0
parso                     0.8.3
peft                      0.5.0
pickleshare               0.7.5
Pillow                    9.3.0
pip                       23.2.1
platformdirs              3.11.0
prometheus-client         0.17.1
prompt-toolkit            3.0.39
protobuf                  4.24.4
psutil                    5.9.5
pure-eval                 0.2.2
pyarrow                   13.0.0
pyautogen                 0.1.10
pycparser                 2.21
pydantic                  1.10.13
pydantic_core             2.10.1
pydub                     0.25.1
Pygments                  2.16.1
pyparsing                 3.1.1
python-dateutil           2.8.2
python-dotenv             1.0.0
python-json-logger        2.0.7
python-multipart          0.0.6
pytz                      2023.3.post1
pywin32                   306
pywinpty                  2.0.12
PyYAML                    6.0.1
pyzmq                     25.1.1
rapidfuzz                 3.4.0
referencing               0.30.2
regex                     2023.10.3
requests                  2.31.0
responses                 0.18.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rich                      13.6.0
rpds-py                   0.10.6
safetensors               0.4.0
scikit-learn              1.3.1
scipy                     1.11.3
semantic-version          2.10.0
Send2Trash                1.8.2
sentencepiece             0.1.99
setuptools                65.5.0
shortuuid                 1.0.11
six                       1.16.0
sniffio                   1.3.0
soupsieve                 2.5
stack-data                0.6.3
starlette                 0.27.0
svgwrite                  1.4.3
sympy                     1.12
termcolor                 2.3.0
terminado                 0.17.1
threadpoolctl             3.2.0
tiktoken                  0.5.1
tinycss2                  1.2.1
tokenizers                0.14.1
toml                      0.10.2
toolz                     0.12.0
torch                     2.1.0+cu118
torchaudio                2.1.0+cu118
torchvision               0.16.0+cu118
tornado                   6.3.3
tqdm                      4.66.1
traitlets                 5.11.2
transformers              4.34.0
types-python-dateutil     2.8.19.14
typing_extensions         4.8.0
tzdata                    2023.3
ujson                     5.8.0
uri-template              1.3.0
urllib3                   1.26.13
uvicorn                   0.23.2
watchfiles                0.20.0
wavedrom                  2.0.3.post3
wcwidth                   0.2.8
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.6.4
websockets                11.0.3
widgetsnbextension        4.0.9
xxhash                    3.4.1
yarl                      1.9.2
```

As you can see, I do have `fastapi` installed but it still gives me the `ModuleNotFoundError` error

**Comment by victordibia** [comment]
@PyroGenesis ,

This looks like a fastchat issue. From the error above, there might be python environment issues (e.g., the python version used to install ). 

- use a virtual env like venv or miniconda. create a python env for your autogen work
- ensure you are correctly building [fastchat from source](https://github.com/lm-sys/FastChat#method-2-from-source) 
- retry running fast chat server
