### ISSUE TITLE
Running "Who should read this paper" TypeError: set.pop() takes no arguments (2 given)

### ISSUE THREAD

**Issue by affibox** [microsoft/autogen#228]
Can anyone please help. I'm starting the "web" script tutorial from this page: https://github.com/microsoft/autogen/blob/main/notebook/agentchat_web_info.ipynb
But after the agent reply's back I run into this error and I have no Idea why or how to fix it:

(autogen) PS C:\Users\affibox\Desktop\affibox\autogen> python .\app.py
user_proxy (to assistant):

    Who should read this paper: https://arxiv.org/abs/2308.08155

--------------------------------------------------------------------------------
assistant (to user_proxy):

To determine who should read a paper, we can look at the title, abstract, and keywords of the paper. However, since I am an AI assistant and cannot browse the web directly, I am unable to access the content of the paper at the provided link. 

To find out who should read the paper, you can follow these steps:

1. Open the link to the paper in a web browser.
2. Read the title, abstract, and keywords of the paper.
3. Based on the information provided, determine the target audience or the specific group of people who would benefit from reading the paper.

If you have any specific questions about the paper or need further assistance, please let me know.

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
Traceback (most recent call last):
  File "C:\Users\affibox\Desktop\affibox\autogen\app.py", line 38, in <module>
    user_proxy.initiate_chat(
  File "C:\Users\affibox\miniconda3\envs\autogen\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 531, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "C:\Users\affibox\miniconda3\envs\autogen\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "C:\Users\affibox\miniconda3\envs\autogen\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 464, in receive
    self.send(reply, sender, silent=silent)
  File "C:\Users\affibox\miniconda3\envs\autogen\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "C:\Users\affibox\miniconda3\envs\autogen\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 462, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\affibox\miniconda3\envs\autogen\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 779, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\affibox\miniconda3\envs\autogen\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 623, in generate_code_execution_reply
    last_n_messages = code_execution_config.pop("last_n_messages", 1)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: set.pop() takes no arguments (2 given)

**Comment by affibox** [comment]
Found the issue: I was an error on my script
