### ISSUE TITLE
[Issue]: TypeError: Completions.create() got an unexpected keyword argument 'headers'

### ISSUE THREAD

**Issue by SaranshSharmaShorthillsAI** [microsoft/autogen#2314]
### Describe the issue

This is the code in which i am facing this error . code is breaking down on this line : "response = chain.run(input_documents=docs, question=query)"

```python
from dotenv import load_dotenv
from PyPDF2 import PdfReader
from langchain.schema import Document
from langchain.document_loaders import PyPDFLoader
import csv
import os
import json
import glob
import openai
import pytesseract
from langchain.text_splitter import (
    RecursiveCharacterTextSplitter,
)
from PIL import Image 
from langchain.document_loaders import PyPDFDirectoryLoader, PyPDFLoader
from langchain.embeddings import SentenceTransformerEmbeddings
from langchain.vectorstores import FAISS
from langchain.chat_models import ChatOpenAI
from langchain.callbacks import get_openai_callback
from langchain.chat_models import AzureChatOpenAI
from langchain.prompts import ChatPromptTemplate
from langchain.chains.question_answering import load_qa_chain
import pickle
import PyPDF2
from langchain.chains import RetrievalQAWithSourcesChain
from models import models_frontier_broadcast as models , specifications_frontier_broadcast
load_dotenv()

azure_openai_endpoint = os.getenv('OPENAI_API_BASE')
os.environ["OPENAI_API_TYPE"] = os.getenv('OPENAI_API_TYPE')
os.environ["OPENAI_API_VERSION"] = os.getenv('OPENAI_API_VERSION')
os.environ["OPENAI_API_BASE"] = azure_openai_endpoint[:-1] if azure_openai_endpoint.endswith('/') else azure_openai_endpoint
os.environ["OPENAI_API_KEY"] = os.getenv('OPENAI_API_KEY')
deployment_name = os.getenv('DEPLOYMENT_NAME')

llm = AzureChatOpenAI(
    model_kwargs={
        "headers": {"User-Id": os.getenv("USER_ID")}
    },
    deployment_name=deployment_name,
    model=os.getenv('MODEL_NAME'),
    temperature=0.0,
)
class VectorDB:
    def __init__(self):
        pass

    def get_pdf_text(self, pdf_path):
        data = PyPDFLoader(pdf_path)
        final_data=data.load()
        return final_data

    def get_text_chunks(self, text):
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=1000, chunk_overlap=200, length_function=len
        )
        chunks = text_splitter.split_documents(text)
        # print(f"Total number of chunks: {len(chunks)}")
        # print(chunks)
        return chunks

    def create_pickles(self, chunks, name):
        store_name = name
        if os.path.exists(f"Pickle/{store_name}.pkl"):
            with open(f"Pickle/{store_name}.pkl", "rb") as f:
                VectorStore = pickle.load(f)

        else:
            embeddings = SentenceTransformerEmbeddings(model_name="all-MiniLM-L6-v2")
            VectorStore = FAISS.from_texts(chunks, embedding=embeddings)
            with open(f"Pickle/{store_name}.pkl", "wb") as f:
                pickle.dump(VectorStore, f)
        return VectorStore


class TableGenerator:
    def generate_table(self, docs, query):
  
        chain = load_qa_chain(llm=llm, chain_type="refine", verbose=True)
        with get_openai_callback() as cb:
            response = chain.run(input_documents=docs, question=query)
        print(cb)
        return response

    def save_to_csv(self, data, file_path):
        with open(file_path, "w", newline="") as csvfile:
            writer = csv.writer(csvfile)
            lines = data.split("\n")
            for line in lines:
                writer.writerow(line.split("|")[1:-1])

    def save_to_text(self, data, file_path):
        with open(file_path, "a") as text_file:
            text_file.write(data)

    def ocr_document_to_text(self,path):
       im = Image.open(path)  
       text=pytesseract.image_to_string(im)
       doc = Document(page_content=text)
       return [doc]

def main(): 
    year = "2024"
    country="India"
    language="English"
    for model, model_names in models.items():
        query1 = f"""Extract all the specifications of SE15-25T
           some of the specifications are manufacturer's Designation , Wheelbase category , WT , Tires , chassis , etc.
          
             """

        path="PDFS/truck.jpg"
        if path:
            q = TableGenerator()
            text=q.ocr_document_to_text(path)
            db = VectorDB()
            text_chunks = db.get_text_chunks(text)
            table = q.generate_table(docs=text_chunks, query=query1)
            print(table)
            q.save_to_csv(table, f"Toyota_Map_Reduce/frontier_Broadcast.csv")
            q.save_to_text(table, f"Toyota_Map_Reduce/frontier_Broadcast.txt")

if __name__ == "__main__":
    main()
```

### Screenshots and logs
```console
Traceback (most recent call last):
  File "/home/shtlp_0071/Desktop/demo_cars/testing_file_refine_chain.py", line 127, in <module>
    main()
  File "/home/shtlp_0071/Desktop/demo_cars/testing_file_refine_chain.py", line 121, in main
    table = q.generate_table(docs=text_chunks, query=query1)
  File "/home/shtlp_0071/Desktop/demo_cars/testing_file_refine_chain.py", line 84, in generate_table
    response = chain.run(input_documents=docs, question=query)
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain_core/_api/deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain/chains/base.py", line 550, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain_core/_api/deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain/chains/base.py", line 378, in __call__
    return self.invoke(
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain/chains/base.py", line 163, in invoke
    raise e
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain/chains/base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain/chains/combine_documents/base.py", line 137, in _call
    output, extra_return_dict = self.combine_docs(
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain/chains/combine_documents/refine.py", line 152, in combine_docs
    res = self.initial_llm_chain.predict(callbacks=callbacks, **inputs)
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain/chains/llm.py", line 293, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain_core/_api/deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain/chains/base.py", line 378, in __call__
    return self.invoke(
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain/chains/base.py", line 163, in invoke
    raise e
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain/chains/base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain/chains/llm.py", line 103, in _call
    response = self.generate([inputs], run_manager=run_manager)
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain/chains/llm.py", line 115, in generate
    return self.llm.generate_prompt(
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 546, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 407, in generate
    raise e
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 397, in generate
    self._generate_with_cache(
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 589, in _generate_with_cache
    result = self._generate(
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 441, in _generate
    response = self.completion_with_retry(
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 356, in completion_with_retry
    return self.client.create(**kwargs)
  File "/home/shtlp_0071/.local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
TypeError: Completions.create() got an unexpected keyword argument 'headers'
```

**Comment by sonichi** [comment]
wrong repo
