### ISSUE TITLE
Read timeout when running Getting Started Example

### ISSUE THREAD

**Issue by anthalasath** [microsoft/autogen#26]
Hi!

First of all, this looks fantastic and I am excited to play with it! Unfortunately, I ran into a problem early on...

I have been trying to run the code example in the "Getting Started" section from [here](https://www.microsoft.com/en-us/research/blog/autogen-enabling-next-generation-large-language-model-applications/)

Here is the stack trace:
```

Traceback (most recent call last):
  File "~\Documents\Dev\autogen_playground\main.py", line 9, in <module>
    user_proxy.initiate_chat(assistant, message="Show me the YTD gain of 10 largest technology companies as of today.")
  File "~\Documents\Dev\autogen_playground\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 521, in initiate_chat     
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "~\Documents\Dev\autogen_playground\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 324, in send
    recipient.receive(message, self, request_reply, silent)
  File "~\Documents\Dev\autogen_playground\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 452, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\Documents\Dev\autogen_playground\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 764, in generate_reply    
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\Documents\Dev\autogen_playground\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 596, in generate_oai_reply    response = oai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\Documents\Dev\autogen_playground\venv\Lib\site-packages\autogen\oai\completion.py", line 801, in create
    return cls._get_response(params, raise_on_ratelimit_or_timeout=raise_on_ratelimit_or_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\Documents\Dev\autogen_playground\venv\Lib\site-packages\autogen\oai\completion.py", line 208, in _get_response
    response = openai_completion.create(request_timeout=request_timeout, **config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\Documents\Dev\autogen_playground\venv\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\Documents\Dev\autogen_playground\venv\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "~\Documents\Dev\autogen_playground\venv\Lib\site-packages\openai\api_requestor.py", line 289, in request
    result = self.request_raw(
             ^^^^^^^^^^^^^^^^^
  File "~\Documents\Dev\autogen_playground\venv\Lib\site-packages\openai\api_requestor.py", line 617, in request_raw
    raise error.Timeout("Request timed out: {}".format(e)) from e
openai.error.Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=60)

```
I am on Windows 10 and have been running the app from a python venv via Powershell in case that matters. The OPENAI_API_KEY environment variable is set to the correct value. I also have a working Internet connection.

Let me know if there is anything I can provide to help more with this issue.

**Comment by anthalasath** [comment]
That fixed it, thank you for the quick reply!

**Comment by AdelElo13** [comment]
this week I have the same problem only this llm_config={"request_timeout": 120} is not a thing anymore
