### ISSUE TITLE
TYPE ERROR GenerativeServiceClient.count_tokens() takes from 1 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by Majboor** [microsoft/autogen#2782]
### Describe the issue

using gemini OAI_CONFIG_LIST,
[
    {
        "model": "gemini-pro",
        "api_key": "key",
        "api_type": "google"
    }
]

code
import os
import autogen
from autogen import ConversableAgent, config_list_from_json

config_list = config_list_from_json(env_or_file="OAI_CONFIG_LIST")
llm_config = {"config_list": config_list, "cache_seed": 42}
user_proxy = autogen.UserProxyAgent(
    name="User_proxy",
    system_message="A human admin.",
    code_execution_config={
        "last_n_messages": 2,
        "work_dir": "groupchat",
        "use_docker": False,
    },  # Please set use_docker=True if docker is available to run the generated code. Using docker is safer than running the generated code directly.
    human_input_mode="TERMINATE",
)
coder = autogen.AssistantAgent(
    name="Coder",
    llm_config=llm_config,
)
pm = autogen.AssistantAgent(
    name="Product_manager",
    system_message="Creative in software product ideas.",
    llm_config=llm_config,
)
groupchat = autogen.GroupChat(agents=[user_proxy, coder, pm], messages=[], max_round=12)
manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config)
user_proxy.initiate_chat(
    manager, message="Find a latest paper about gpt-4 on arxiv and find its potential applications in software."
)

getting error
`terminator@ autogen % python3 testing.py
User_proxy (to chat_manager):

Find a latest paper about gpt-4 on arxiv and find its potential applications in software.

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/terminator/code/autogen/testing.py", line 28, in <module>
    user_proxy.initiate_chat(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 991, in initiate_chat
    self.send(msg2send, recipient, silent=silent)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 632, in send
    recipient.receive(message, self, request_reply, silent)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 792, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 1921, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/autogen/agentchat/groupchat.py", line 664, in run_chat
    speaker = groupchat.select_speaker(speaker, self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/autogen/agentchat/groupchat.py", line 468, in select_speaker
    final, name = selector.generate_oai_reply(messages)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 1287, in generate_oai_reply
    extracted_response = self._generate_oai_reply_from_client(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 1306, in _generate_oai_reply_from_client
    response = llm_client.create(
               ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/autogen/oai/client.py", line 638, in create
    response = client.create(params)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/autogen/oai/gemini.py", line 140, in create
    prompt_tokens = model.count_tokens(chat.history[:-1]).total_tokens
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/google/generativeai/generative_models.py", line 278, in count_tokens
    return self._client.count_tokens(self.model_name, contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GenerativeServiceClient.count_tokens() takes from 1 to 2 positional arguments but 3 were given`

### Steps to reproduce

Python 3.12.3
pip 24.0,
install pyautogen
pip3 install pyautogen
Name: pyautogen
Version: 0.2.25
Summary: Enabling Next-Gen LLM Applications via Multi-Agent Conversation Framework
Home-page: https://github.com/microsoft/autogen
Author: AutoGen
Author-email: auto-gen@outlook.com
License: 
Location: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages
Requires: diskcache, docker, flaml, numpy, openai, pydantic, python-dotenv, termcolor, tiktoken
Required-by: 

run the following code 
import os
import autogen
from autogen import ConversableAgent, config_list_from_json

config_list = config_list_from_json(env_or_file="OAI_CONFIG_LIST")
llm_config = {"config_list": config_list, "cache_seed": 42}
user_proxy = autogen.UserProxyAgent(
    name="User_proxy",
    system_message="A human admin.",
    code_execution_config={
        "last_n_messages": 2,
        "work_dir": "groupchat",
        "use_docker": False,
    },  # Please set use_docker=True if docker is available to run the generated code. Using docker is safer than running the generated code directly.
    human_input_mode="TERMINATE",
)
coder = autogen.AssistantAgent(
    name="Coder",
    llm_config=llm_config,
)
pm = autogen.AssistantAgent(
    name="Product_manager",
    system_message="Creative in software product ideas.",
    llm_config=llm_config,
)
groupchat = autogen.GroupChat(agents=[user_proxy, coder, pm], messages=[], max_round=12)
manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config)
user_proxy.initiate_chat(
    manager, message="Find a latest paper about gpt-4 on arxiv and find its potential applications in software."
)
 

### Additional Information

I am trying to use pyautogen with gemini  but am unable to use the user_proxy.initiate_chat

**Comment by gagb** [comment]
@Majboor -- please re-open if you still have this issue.
