### ISSUE TITLE
[Bug]:  Missing packaging module

### ISSUE THREAD

**Issue by cakriwut** [microsoft/autogen#2783]
### Describe the bug

I follow the installation instruction by running `pip install autogenstudio` then followed by `autogenstudio ui`.
The UI does not launch with error complains missing `packaging` module.

**Resolution**
Run `pip install packaging`

### Steps to reproduce

1. `conda activate autogenstudio`
2. `export AZURE_OPENAI_API_KEY=xxx`
3. `pip install autogenstudio`
4. `autogenstudio ui`

### Model Used

gpt-4

### Expected Behavior

Server should start

**Comment by aaroneden** [comment]
I'm experiencing this as well.  Full error:

Traceback (most recent call last):
  File "/home/autogen/.local/bin/autogenstudio", line 5, in <module>
    from autogenstudio.cli import run
  File "/home/autogen/.local/lib/python3.11/site-packages/autogenstudio/__init__.py", line 1, in <module>
    from .chatmanager import *
  File "/home/autogen/.local/lib/python3.11/site-packages/autogenstudio/chatmanager.py", line 11, in <module>
    from .utils import extract_successful_code_blocks, get_modified_files, summarize_chat_history
  File "/home/autogen/.local/lib/python3.11/site-packages/autogenstudio/utils/__init__.py", line 2, in <module>
    from .utils import *
  File "/home/autogen/.local/lib/python3.11/site-packages/autogenstudio/utils/utils.py", line 8, in <module>
    import autogen
  File "/home/autogen/.local/lib/python3.11/site-packages/autogen/__init__.py", line 3, in <module>
    from .agentchat import *
  File "/home/autogen/.local/lib/python3.11/site-packages/autogen/agentchat/__init__.py", line 2, in <module>
    from .assistant_agent import AssistantAgent
  File "/home/autogen/.local/lib/python3.11/site-packages/autogen/agentchat/assistant_agent.py", line 5, in <module>
    from .conversable_agent import ConversableAgent
  File "/home/autogen/.local/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 19, in <module>
    from ..code_utils import (
  File "/home/autogen/.local/lib/python3.11/site-packages/autogen/code_utils.py", line 15, in <module>
    from autogen import oai
  File "/home/autogen/.local/lib/python3.11/site-packages/autogen/oai/__init__.py", line 2, in <module>
    from autogen.oai.client import ModelClient, OpenAIWrapper
  File "/home/autogen/.local/lib/python3.11/site-packages/autogen/oai/client.py", line 15, in <module>
    from autogen.oai.openai_utils import OAI_PRICE1K, get_key, is_valid_api_key
  File "/home/autogen/.local/lib/python3.11/site-packages/autogen/oai/openai_utils.py", line 14, in <module>
    from packaging.version import parse
ModuleNotFoundError: No module named 'packaging'

**Comment by jackgerrits** [comment]
Can you please try reproing your issue in 0.4 and create a new issue if it is still a problem for you. Thanks!

You find find the migration guide for [0.2 to 0.4 here](https://microsoft.github.io/autogen/stable/user-guide/agentchat-user-guide/migration-guide.html)
