### ISSUE TITLE
"HIGH TRAFFIC" api error when using oai for local LLM (Following article: Use AutoGen for Local LLMs)

### ISSUE THREAD

**Issue by vaibhav-kuchibhotla** [microsoft/autogen#280]
I am following the Use AutoGen for Local LLMs article ([link](https://microsoft.github.io/autogen/blog/2023/07/14/Local-LLMs/#interact-with-model-using-oaicompletion)) to setup a local GPTQ quantized LLM 
- LLM: TheBloke/Llama-2-7B-chat-GPTQ
- Platform: AWS

How to reproduce error:

I was able to successfully run all commands in the attached article up to and including the following with the attached outputs respectively:

- `python -m fastchat.serve.controller`
```
2023-10-18 10:39:52 | INFO | controller | args: Namespace(host='localhost', port=21001, dispatch_method='shortest_queue', ssl=False)
2023-10-18 10:39:52 | ERROR | stderr | INFO:     Started server process [20248]
2023-10-18 10:39:52 | ERROR | stderr | INFO:     Waiting for application startup.
2023-10-18 10:39:52 | ERROR | stderr | INFO:     Application startup complete.
2023-10-18 10:39:52 | ERROR | stderr | INFO:     Uvicorn running on http://localhost:21001 (Press CTRL+C to quit)
2023-10-18 10:42:22 | INFO | controller | Register a new worker: http://localhost:21002
2023-10-18 10:42:22 | INFO | controller | Register done: http://localhost:21002, {'model_names': ['Llama-2-7B-chat-GPTQ'], 'speed': 1, 'queue_length': 0}
2023-10-18 10:42:22 | INFO | stdout | INFO:     127.0.0.1:55580 - "POST /register_worker HTTP/1.1" 200 OK
2023-10-18 10:48:09 | INFO | controller | Register a new worker: http://localhost:21002
2023-10-18 10:48:09 | INFO | controller | Register done: http://localhost:21002, {'model_names': ['Llama-2-7B-chat-GPTQ'], 'speed': 1, 'queue_length': 0}
2023-10-18 10:48:09 | INFO | stdout | INFO:     127.0.0.1:54604 - "POST /register_worker HTTP/1.1" 200 OK
2023-10-18 10:48:53 | INFO | stdout | INFO:     127.0.0.1:47832 - "POST /list_models HTTP/1.1" 200 OK
2023-10-18 10:48:53 | INFO | controller | names: ['http://localhost:21002'], queue_lens: [0.0], ret: http://localhost:21002
2023-10-18 10:48:53 | INFO | stdout | INFO:     127.0.0.1:47842 - "POST /get_worker_address HTTP/1.1" 200 OK
2023-10-18 10:48:54 | INFO | controller | Receive heart beat. http://localhost:21002
2023-10-18 10:48:54 | INFO | stdout | INFO:     127.0.0.1:47850 - "POST /receive_heart_beat HTTP/1.1" 200 OK
2023-10-18 10:49:07 | INFO | stdout | INFO:     127.0.0.1:44476 - "POST /list_models HTTP/1.1" 200 OK
2023-10-18 10:49:07 | INFO | controller | names: ['http://localhost:21002'], queue_lens: [0.0], ret: http://localhost:21002
```

- `python -m fastchat.serve.model_worker --model-path "../huggingface_models/Llama-2-7B-chat-GPTQ"`
```
2023-10-18 10:48:05 | INFO | model_worker | args: Namespace(host='localhost', port=21002, worker_address='http://localhost:21002', controller_address='http://localhost:21001', model_path='../huggingface_models/Llama-2-7B-chat-GPTQ', revision='main', device='cuda', gpus=None, num_gpus=1, max_gpu_memory=None, dtype=None, load_8bit=False, cpu_offloading=False, gptq_ckpt=None, gptq_wbits=16, gptq_groupsize=-1, gptq_act_order=False, awq_ckpt=None, awq_wbits=16, awq_groupsize=-1, enable_exllama=False, exllama_max_seq_len=4096, exllama_gpu_split=None, model_names=None, conv_template=None, embed_in_truncate=False, limit_worker_concurrency=5, stream_interval=2, no_register=False, seed=None)
2023-10-18 10:48:05 | INFO | model_worker | Loading the model ['Llama-2-7B-chat-GPTQ'] on worker 0198b7ca ...
Using pad_token, but it is not set yet.
2023-10-18 10:48:09 | INFO | model_worker | Register to controller
2023-10-18 10:48:09 | ERROR | stderr | INFO:     Started server process [26690]
2023-10-18 10:48:09 | ERROR | stderr | INFO:     Waiting for application startup.
2023-10-18 10:48:09 | ERROR | stderr | INFO:     Application startup complete.
2023-10-18 10:48:09 | ERROR | stderr | INFO:     Uvicorn running on http://localhost:21002 (Press CTRL+C to quit)
2023-10-18 10:48:53 | INFO | stdout | INFO:     127.0.0.1:41708 - "POST /worker_get_conv_template HTTP/1.1" 200 OK
2023-10-18 10:48:53 | INFO | stdout | INFO:     127.0.0.1:41714 - "POST /model_details HTTP/1.1" 200 OK
2023-10-18 10:48:53 | INFO | stdout | INFO:     127.0.0.1:41730 - "POST /count_token HTTP/1.1" 200 OK
2023-10-18 10:48:53 | INFO | stdout | INFO:     127.0.0.1:41736 - "POST /worker_generate HTTP/1.1" 200 OK
2023-10-18 10:48:54 | INFO | model_worker | Send heart beat. Models: ['Llama-2-7B-chat-GPTQ']. Semaphore: Semaphore(value=5, locked=False). call_ct: 1. worker_id: 0198b7ca. 
2023-10-18 10:49:07 | INFO | stdout | INFO:     127.0.0.1:41966 - "POST /model_details HTTP/1.1" 200 OK
2023-10-18 10:49:07 | INFO | stdout | INFO:     127.0.0.1:41974 - "POST /count_token HTTP/1.1" 200 OK
2023-10-18 10:49:07 | INFO | stdout | INFO:     127.0.0.1:41978 - "POST /worker_generate HTTP/1.1" 200 OK
2023-10-18 10:49:17 | INFO | stdout | INFO:     127.0.0.1:33306 - "POST /model_details HTTP/1.1" 200 OK
2023-10-18 10:49:17 | INFO | stdout | INFO:     127.0.0.1:33312 - "POST /count_token HTTP/1.1" 200 OK
2023-10-18 10:49:17 | INFO | stdout | INFO:     127.0.0.1:33318 - "POST /worker_generate HTTP/1.1" 200 OK
```

- `python -m fastchat.serve.openai_api_server --host localhost --port 8000`
```
(/home/ec2-user/SageMaker/conda-envs/textgen) [ec2-user@ip-172-16-80-202 FastChat]$ python3 -m fastchat.serve.openai_api_server --host localhost --port 8000
INFO:     Started server process [27301]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
```

Upon running the following python script (from the article):
```
from autogen import oai

# create a chat completion request
response = oai.ChatCompletion.create(
    config_list=[
        {
            "model": "Llama-2-7B-chat-GPTQ",
            "api_base": "http://localhost:8000/v1",
            "api_type": "open_ai",
            "api_key": "NULL",
        }
    ],
    messages=[{"role": "user", "content": "Hi"}]
    #prompt="Hi"
)
print(response)
```

I get the error below:
```
[autogen.oai.completion: 10-18 10:52:03] {234} INFO - retrying in 10 seconds...
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/conda-envs/textgen/lib/python3.10/site-packages/openai/api_requestor.py", line 413, in handle_error_response
    error_data = resp["error"]
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/conda-envs/textgen/lib/python3.10/site-packages/autogen/oai/completion.py", line 220, in _get_response
    response = openai_completion.create(request_timeout=request_timeout, **config)
  File "/home/ec2-user/SageMaker/conda-envs/textgen/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/ec2-user/SageMaker/conda-envs/textgen/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "/home/ec2-user/SageMaker/conda-envs/textgen/lib/python3.10/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/ec2-user/SageMaker/conda-envs/textgen/lib/python3.10/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/home/ec2-user/SageMaker/conda-envs/textgen/lib/python3.10/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
  File "/home/ec2-user/SageMaker/conda-envs/textgen/lib/python3.10/site-packages/openai/api_requestor.py", line 415, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '{"object":"error","message":"**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\\n\\n(Unrecognized tensor type ID: AutocastCUDA)","code":50001}' (HTTP response code was 400)
```

**Comment by tommy3266** [comment]
I got a same problem , you fix it?

**Comment by ScottXiao233** [comment]
How can I solve this? I run the model locally #296

**Comment by ishaan-jaff** [comment]
Hi @vaibhav-kuchibhotla @ScottXiao233 @singhaki 
LiteLLM now allows you to queue requests. It's built to solve the problem in this issue (would love your feedback if not)

Here's a quick start on using it: Compatible with GPT-4, llama, fastchat (mentioned in this thread) 
docs: https://docs.litellm.ai/docs/routing#queuing-beta 

### Quick Start 

1. Add Redis credentials in a .env file

```python
REDIS_HOST="my-redis-endpoint"
REDIS_PORT="my-redis-port"
REDIS_PASSWORD="my-redis-password" # [OPTIONAL] if self-hosted
REDIS_USERNAME="default" # [OPTIONAL] if self-hosted
```

2. Start litellm server with your model config

```bash
$ litellm --config /path/to/config.yaml --use_queue
```

Here's an example config for `gpt-3.5-turbo`

**config.yaml** (This will load balance between OpenAI + Azure endpoints)
```yaml
model_list: 
  - model_name: gpt-3.5-turbo
    litellm_params: 
      model: gpt-3.5-turbo
      api_key: 
  - model_name: gpt-3.5-turbo
    litellm_params: 
      model: azure/chatgpt-v-2 # actual model name
      api_key: 
      api_version: 2023-07-01-preview
      api_base: https://openai-gpt-4-test-v-1.openai.azure.com/
```

3. Test (in another window) → sends 100 simultaneous requests to the queue 

```bash
$ litellm --test_async --num_requests 100
```


### Available Endpoints
- `/queue/request` - Queues a /chat/completions request. Returns a job id. 
- `/queue/response/{id}` - Returns the status of a job. If completed, returns the response as well. Potential status's are: `queued` and `finished`.

**Comment by thinkall** [comment]
We are closing this issue due to inactivity; please reopen if the problem persists.
