### ISSUE TITLE
[Bug]: Chromadb 0.5.1+ breaks retrieval agent 

### ISSUE THREAD

**Issue by jprosevear** [microsoft/autogen#2960]
### Describe the bug

In https://github.com/chroma-core/chroma/pull/2044 a new field was added in the query result `included` which is an array of strings (not None and not [[]]), so when https://github.com/microsoft/autogen/blob/main/autogen/agentchat/contrib/vectordb/utils.py#L110 tries to data_dict[key][i][j], it dies.

### Model Used

Any

### Expected Behavior

Should skip included key or otherwise protect against it.

### Screenshots and logs

```
models to use:  ['gpt-4']
Accepted file formats for `docs_path`:
['txt', 'json', 'csv', 'tsv', 'md', 'html', 'htm', 'rtf', 'rst', 'jsonl', 'log', 'xml', 'yaml', 'yml', 'pdf']
/Users/jpr/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Trying to create collection.
2024-06-18 12:20:28,983 - autogen.agentchat.contrib.retrieve_user_proxy_agent - INFO - Use the existing collection `autogen-docs`.
2024-06-18 12:20:29,153 - autogen.agentchat.contrib.retrieve_user_proxy_agent - INFO - Found 146 chunks.
Traceback (most recent call last):
  File "/Users/jpr/src/AITools/autogen/rhino.py", line 58, in <module>
    chat_result = ragproxyagent.initiate_chat(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jpr/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 1015, in initiate_chat
    msg2send = message(_chat_info["sender"], _chat_info["recipient"], kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jpr/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/autogen/agentchat/contrib/retrieve_user_proxy_agent.py", line 631, in message_generator
    sender.retrieve_docs(problem, n_results, search_string)
  File "/Users/jpr/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/autogen/agentchat/contrib/retrieve_user_proxy_agent.py", line 562, in retrieve_docs
    results = self._vector_db.retrieve_docs(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jpr/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/autogen/agentchat/contrib/vectordb/chromadb.py", line 260, in retrieve_docs
    results = chroma_results_to_query_results(results)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jpr/.asdf/installs/python/3.12.4/lib/python3.12/site-packages/autogen/agentchat/contrib/vectordb/utils.py", line 111, in chroma_results_to_query_results
    sub_dict[key[:-1]] = data_dict[key][i][j]  # remove 's' in the end from key
                         ~~~~~~~~~~~~~~~~~^^^
IndexError: string index out of range
```

### Additional Information

Downgrading to 0.5.0 works

**Comment by thinkall** [comment]
Thank you @jprosevear for the good catching! Could you help verify if #2971 fixes the issue for you? Thanks.
