### ISSUE TITLE
[Issue][Discussion]: Use of "name" field for messages

### ISSUE THREAD

**Issue by marklysze** [microsoft/autogen#2989]
### Describe the issue

This issue is a place to discuss the impact of not being able to rely on the `name` field on messages and existing, or proposed, solutions to cater for this.

---

The `name` field on messages (which contains the agent's name) is _optionally_ supported by OpenAI for inference, however it's not used (or cannot be included) on messages through other clients (such as local inference or cloud inference through Anthropic, Mistral AI, Together.AI, Groq, etc.).

This creates a hidden challenge for AutoGen developers who may think that their messages have the agent's name associated with them and create workflows/prompts that refer to the name.

My experience with speaker selection on group chat is that without the `name` being available to the LLM, it can be difficult for the LLM to determine the next speaker when the prompt to select the next speaker is dependent on who has spoken already. For example, a speaker selection prompt of "Once A, E, or F have spoken select H to review and provide feedback." would be challenging to adhere to if each message has no `name`.

**It would be great to get your thoughts on what not having `name` impacts (or doesn't) and ideas to solve it!**

---

An initial thought is a simple way to, optionally, include the agent's name at the start of each message, e.g. 
```
dm = ConversableAgent(
    "digital_marketer",
    "add_name_to_messages"=True,
    ...

# Resulting in messages where content is "digital_marketer said: \n Some ideas to ..."
)
```
(one challenge of this approach is that the LLM takes these messages as the format it needs to respond with and its responses all follow that format!)

---

Related issues/PRs:
#2635
#2457

_Note: this issue relates to chat messages and not function/tool messages._

**Comment by yonitjio** [comment]
Please keep the name field. Beside the agent  selection, name field also useful for groupchat history. 

Also, for future proof like multi user chat.

Sure there are other ways, but with name field, it's easier.

As for non openai, imo, if the name field is not used and/or causing issues, it should be handled in the client module logic.

**Comment by marklysze** [comment]
> Please keep the name field. Beside the agent selection, name field also useful for groupchat history i.e., pausing and resuming the group chat.
> 
> Also, for future proof, perhaps something like multi user chat. I have no idea what it's going to be, or how it will differ from groupchat. But having more data is good.
> 
> Sure there are other ways, but with name field, it's easier.
> 
> As for non openai, imo, if the name field is not used and/or causing issues, it should be handled in the client module logic.

Thanks for your thoughts @yonitjio - agreed, the `name` field will stay in the core AutoGen code and I wouldn't think it will change messaging when using OpenAI, for now.

Yes, for non-OpenAI, it requires discussion and hopefully this issue will give us some ideas on that front.

**Comment by JMLX42** [comment]
> The name field on messages (which contains the agent's name) is optionally supported by OpenAI for inference, however it's not used (or cannot be included) on messages through other clients (such as local inference or cloud inference through Anthropic, Mistral AI, Together.AI, Groq, etc.).

> Yes, for non-OpenAI, it requires discussion and hopefully this issue will give us some ideas on that front.

FYI it is making LiteLLM proxy (and thus my `autogen` app) crash:

```yml
version: "3.9"
services:
  litellm:
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000"
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
    command: ["--config", "/app/config.yml", --detailed_debug]
```

```yml
---

model_list:
  - model_name: mistral-large
    litellm_params:
      model: mistral/mistral-large-latest
      api_base: https://api.mistral.ai/v1
      api_key: "os.environ/MISTRAL_API_KEY"

litellm_settings:
  drop_params: true

router_settings:
  fallbacks:
    - { "gpt-4o": ["mistral-large"] }
```

Stacktrace:

```
Traceback (most recent call last):
  File "/path/to/my/project/.venv/lib/python3.12/site-packages/autogen_core/application/_single_threaded_agent_runtime.py", line 385, in _process_publish
    await asyncio.gather(*responses)
  File "/path/to/my/project/.venv/lib/python3.12/site-packages/autogen_core/application/_single_threaded_agent_runtime.py", line 377, in _on_message
    return await agent.on_message(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/my/project/.venv/lib/python3.12/site-packages/autogen_agentchat/teams/_group_chat/_sequential_routed_agent.py", line 49, in on_message
    return await super().on_message(message, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/my/project/.venv/lib/python3.12/site-packages/autogen_core/components/_routed_agent.py", line 468, in on_message
    return await h(self, message, ctx)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/my/project/.venv/lib/python3.12/site-packages/autogen_core/components/_routed_agent.py", line 267, in wrapper
    return_value = await func(self, message, ctx)  # type: ignore
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/my/project/.venv/lib/python3.12/site-packages/autogen_agentchat/teams/_group_chat/_chat_agent_container.py", line 41, in handle_content_request
    async for msg in self._agent.on_messages_stream(self._message_buffer, ctx.cancellation_token):
  File "/path/to/my/project/.venv/lib/python3.12/site-packages/autogen_agentchat/agents/_assistant_agent.py", line 258, in on_messages_stream
    result = await self._model_client.create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/my/project/.venv/lib/python3.12/site-packages/autogen_ext/models/_openai/_openai_client.py", line 488, in create
    if result.usage is not None:
       ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'usage'
```

Two options:

1. Add (optional) support for `name` in LiteLLM: log a warning if not using the OpenAI backend. Use it otherwise.
2. Use a different way to specify names.

For 2., this is how I deal with user names (and other things such as the user role or message date) in [Wally The Wobot](https://gitlab.com/wally-the-wobot/wally/) (It's a GitLab bot based on GitLab's threaded conversations. So very much a multi-user chat. Very similar to the `autogen` situation):

- Message "header" formatting: https://gitlab.com/wally-the-wobot/wally/-/blob/3b662c32f0038811c91df7cc1d2c6f1ee3012aef/wally.py#L134
- Prompt to handle the message "header": https://gitlab.com/wally-the-wobot/wally/-/blob/3b662c32f0038811c91df7cc1d2c6f1ee3012aef/wally.py#L550
