### ISSUE TITLE
Add a flag to enable self-execute in conversable agent?

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/autogen#302]
Continue from #294 

@bonadio has a great example of self-executing function_call agent, which automatically executes a function and returns results when it generates a function_call. Maybe it's worthwhile to leverage this feature into autogen? (maybe someone already asked that but just ask again)

https://gist.github.com/bonadio/96435a1b6ccc32297aa8cc1db7cfc381#file-self_execute_function_agent-py

**Comment by sonichi** [comment]
I'm interested in knowing the performance of the self-executing function_call agent vs. two separate agents. They are not equivalent as the conversation history will be different.

**Comment by ProgramItUp** [comment]
@LittleLittleCloud the code looks interesting but the API has updated.  Any chance you'll be updating the gist?

`~/code/autogen$ python ./self_execute_function_agent.py
user_proxy (to order_assistant):


Was my order delivered?


--------------------------------------------------------------------------------
[autogen.oai.completion: 12-30 11:01:41] {786} WARNING - Completion.create is deprecated in pyautogen v0.2 and openai>=1. The new openai requires initiating a client for inference. Please refer to https://microsoft.github.io/autogen/docs/Use-Cases/enhanced_inference#api-unification
Traceback (most recent call last):
  File "/home/me/code/autogen/./self_execute_function_agent.py", line 165, in <module>
    user_proxy.initiate_chat(
  File "/home/me/code/autogen/autogen/agentchat/conversable_agent.py", line 562, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/home/me/code/autogen/autogen/agentchat/conversable_agent.py", line 360, in send
    recipient.receive(message, self, request_reply, silent)
  File "/home/me/code/autogen/autogen/agentchat/conversable_agent.py", line 493, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/code/autogen/autogen/agentchat/conversable_agent.py", line 968, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/code/autogen/./self_execute_function_agent.py", line 110, in custom_generate_oai_reply
    response = oai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/code/autogen/autogen/oai/completion.py", line 792, in create
    raise ERROR
AssertionError: (Deprecated) The autogen.Completion class requires openai<1 and diskcache.`

**Comment by thinkall** [comment]
We are closing this issue due to inactivity; please reopen if the problem persists.
