### ISSUE TITLE
[Bug]: LlamaIndexConversableAgent sends a coroutine?

### ISSUE THREAD

**Issue by tituslhy** [microsoft/autogen#3208]
### Describe the bug

I created an autogen groupchat using LlamaIndex agents and have adapted the respective agent classes to make the intermediate messages visible on Chainlit. This works when I use Autogen agents but not Autogen-LlamaIndex agents. The error message I got was that a coroutine is being sent instead of a message. There was no error running this on Jupyter Notebooks.

### Steps to reproduce

I define my agent in the utils.py file
```
from llama_index.core.agent import (
    FunctionCallingAgentWorker,
    AgentRunner
)
from llama_index.core.tools.tool_spec.base import BaseToolSpec
from llama_index.tools.tavily_research import TavilyToolSpec

import autogen
from autogen.agentchat.contrib.llamaindex_conversable_agent import (
    LLamaIndexConversableAgent
)
import chainlit as cl

import os
from dotenv import load_dotenv, find_dotenv
_ = load_dotenv(find_dotenv())

llm_config_list = [
    {
        "model": "gemini-1.5-flash",
        "api_type": "google"
    }
]

seed=25

llm_config={"config_list": llm_config_list, "seed": seed}

def get_tavily_tool():
    """Returns the tavily search tool"""
    tavily_tool = TavilyToolSpec(api_key = os.getenv("TAVILY"))
    return tavily_tool.to_tool_list()

def chat_new_message(message, sender):
    cl.run_sync(
        cl.Message(
            content="",
            author=sender.name,
        ).send()
    )
    content = message.get('content')
    cl.run_sync(
        cl.Message(
            content=content,
            author=sender.name,
        ).send()
    )

async def ask_helper(func, **kwargs):
    res = await func(**kwargs).send()
    while not res:
        res = await func(**kwargs).send()
    return res

class ChainlitLLamaIndexConversableAgent(LLamaIndexConversableAgent):
    def send(
        self,
        message: Union[Dict, str],
        recipient: Agent,
        request_reply: Optional[bool] = None,
        silent: Optional[bool] = False,
    ) -> bool:
        if isinstance(message, dict):
            message = message['content']
        cl.run_sync(
            cl.Message(
                content = f"{self.name} *Sending message to '{recipient.name}':*\n\n{message}",
                author=self.name,
            ).send()
        )
        super(ChainlitLLamaIndexConversableAgent, self).send(
            message=message,
            recipient=recipient,
            request_reply=request_reply,
            silent=silent,
        )

class ChainlitUserProxyAgent(UserProxyAgent):
    async def get_human_input(self, prompt: str) -> str:
        if prompt.startswith(
            "Provide feedback to assistant. Press enter to skip and use auto-reply"
        ):
            res = await ask_helper(
                cl.AskActionMessage,
                content="Continue or provide feedback?",
                actions=[
                        cl.Action(
                            name="continue", value="continue", label="✅ Continue"
                        ),
                    cl.Action(
                            name="feedback",
                            value="feedback",
                            label="💬 Provide feedback",
                        ),
                    cl.Action(
                            name="exit",
                            value="exit",
                            label="🔚 Exit Conversation"
                        ),
                ],
            )
            if res.get("value") == "continue":
                return ""
            if res.get("value") == "exit":
                return "exit"

        reply = await ask_helper(
            cl.AskUserMessage, content=prompt, timeout=60)

        return reply["content"].strip()

    def send(
        self,
        message: Union[Dict, str],
        recipient: Agent,
        request_reply: Optional[bool] = None,
        silent: Optional[bool] = False,
    ):
        cl.Message(
            content=f'*Sending message to "{recipient.name}"*:\n\n{message}',
            author="UserProxyAgent",
        ).send()
        super(ChainlitUserProxyAgent, self).send(
            message=message,
            recipient=recipient,
            request_reply=request_reply,
            silent=silent,
        )

def get_agent(llm,
              tools: List[BaseToolSpec],
              agent_name: str,
              agent_description: str,
              system_message: Optional[str] = None,
              human_input_mode: Optional[str] = "NEVER"):
    agent_worker = FunctionCallingAgentWorker.from_tools(
        tools = tools,
        llm = llm,
        verbose = True
    )
    return ChainlitLLamaIndexConversableAgent(
        name = agent_name,
        llama_index_agent = AgentRunner(
            agent_worker = agent_worker
        ),
        system_message = system_message,
        description = agent_description,
        human_input_mode = human_input_mode,
        max_consecutive_auto_reply = 2,
    )
def get_groupchat(llm_config):
       user_proxy = ChainlitUserProxyAgent(
           name="Admin",
           human_input_mode="ALWAYS",
           code_execution_config=False
    )
    research_analyst = get_agent(
        agent_name="Researcher",
        tools = [
            *search_tool,
        ],
        system_message = """You do research online.""",
        agent_description="""This agent helps customers undertake online research.""",
    )
   groupchat = autogen.Groupchat(agents = [user_proxy, research_analyst], messages=[], select_speaker_selection_method="round- 
      robin")
   manager = autogen.GroupChatManager(
        groupchat=groupchat,
        llm_config = llm_config
    )
   return user_proxy, manager, groupchat
```
And then call it out in my main app.py
```
import chainlit as cl
from utils import get_groupchat
import warnings
warnings.filterwarnings('ignore')

@cl.on_chat_start
async def on_chat_start():
    user_proxy, manager, groupchat = get_groupchat()
    
    # manager = 
    cl.user_session.set('user_proxy', user_proxy)
    cl.user_session.set('manager', manager)
    cl.user_session.set('group_chat', groupchat)
    
    msg = cl.Message(
        content="""Hello and welcomel! All our agents have joined this group chat.
        How can we help you today?""",
        author = "User_Proxy"
    )
    await msg.send()

@cl.on_message
async def run_conversation(message: cl.Message):
    CONTEXT = message.content
    MAX_ITER = 20
    manager = cl.user_session.get('manager')
    user_proxy = cl.user_session.get('user_proxy')
    groupchat = cl.user_session.get('group_chat')

    if len(groupchat.messages) == 0:
      message = f"""Do the task based on the user input: {CONTEXT}."""
      await cl.Message(content=f"""Starting agents on task...""").send()
      await cl.make_async(user_proxy.initiate_chat)(manager, message=message)
    elif len(groupchat.messages) < MAX_ITER:
      await cl.make_async(user_proxy.send)(manager, message=CONTEXT)
    elif len(groupchat.messages) == MAX_ITER:  
      await cl.make_async(user_proxy.send)(manager, message="exit")
```

### Model Used

groupchat manager: gemini-1.5-flash
llm for LlamaIndexConversableAgent: claude-3 haiku on AWS Bedrock (I defined my LlamaIndex function calling agent first, then wrapped it in Autogen's LlamaIndexConversableAgent class). 

### Expected Behavior

In Jupyter Notebooks everything works fine, there were no errors - the agent answered my question and I could add follow-ups.

### Screenshots and logs

The first agent was able to send its answer onto Chainlit, but after that I couldn't give my inputs on chainlit because of this error:
```
Next speaker: Admin

Admin (to chat_manager):

2024-07-25 09:20:40 - content must be None, str, or list, but got <class 'coroutine'>
Traceback (most recent call last):
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/chainlit/utils.py", line 44, in wrapper
    return await user_function(**params_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/App/tlim2/Projects/AI-Sandbox/llm/experiments/llamaindex/StockCrew/autogen_app.py", line 33, in run_conversation
    await cl.make_async(user_proxy.initiate_chat)(manager, message=message)
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/asyncer/_main.py", line 358, in wrapper
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/asyncio/tasks.py", line 385, in __wakeup
    future.result()
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 1018, in initiate_chat
    self.send(msg2send, recipient, silent=silent)
  File "/App/tlim2/Projects/AI-Sandbox/llm/experiments/llamaindex/StockCrew/src/autogen/autogen_utils.py", line 137, in send
    super(ChainlitUserProxyAgent, self).send(
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 655, in send
    recipient.receive(message, self, request_reply, silent)
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 818, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 1972, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/autogen/agentchat/groupchat.py", line 1080, in run_chat
    speaker.send(reply, self, request_reply=False, silent=silent)
  File "/App/tlim2/Projects/AI-Sandbox/llm/experiments/llamaindex/StockCrew/src/autogen/autogen_utils.py", line 137, in send
    super(ChainlitUserProxyAgent, self).send(
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 655, in send
    recipient.receive(message, self, request_reply, silent)
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 815, in receive
    self._process_received_message(message, sender, silent)
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 783, in _process_received_message
    self._print_received_message(message, sender)
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/autogen/agentchat/conversable_agent.py", line 742, in _print_received_message
    iostream.print(content_str(content), flush=True)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/App/tlim2/Anaconda3/envs/llamaindex/lib/python3.12/site-packages/autogen/code_utils.py", line 70, in content_str
    raise TypeError(f"content must be None, str, or list, but got {type(content)}")
TypeError: content must be None, str, or list, but got <class 'coroutine'>
```

### Additional Information

pyautogen==0.2.32
llama-index==0.10.56
llama-index-core==0.10.56
llama-index-llms-bedrock-converse==0.1.3
llama-index-tools-tavily-research==0.1.3
tavily-python==0.3.3
google-ai-generativelanguage==0.6.4

**Comment by tituslhy** [comment]
After further investigation I discovered that the bug does not lie with autogen but when deploying autogen onto frontend - coroutine problems from too many async functions.
