### ISSUE TITLE
[Bug]: ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by windowshopr** [microsoft/autogen#3463]
### Describe the bug

```
PS I:\nasty\Python_Projects\LLM\autogen\Studio> autogenstudio ui
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Scripts\autogenstudio.exe\__main__.py", line 4, in <module>
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogenstudio\__init__.py", line 1, in <module>
    from .chatmanager import *
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogenstudio\chatmanager.py", line 11, in <module>
    from .workflowmanager import WorkflowManager
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogenstudio\workflowmanager.py", line 7, in <module>
    import autogen
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\__init__.py", line 3, in <module>
    from .agentchat import *
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\agentchat\__init__.py", line 2, in <module>
    from .assistant_agent import AssistantAgent
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\agentchat\assistant_agent.py", line 5, in <module>
    from .conversable_agent import ConversableAgent
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 19, in <module>
    from ..code_utils import (
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\code_utils.py", line 15, in <module>
    from autogen import oai
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\oai\__init__.py", line 2, in <module>
    from autogen.oai.client import ModelClient, OpenAIWrapper
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\oai\client.py", line 9, in <module>
    from flaml.automl.logger import logger_formatter
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flaml\__init__.py", line 3, in <module>
    from flaml.automl import AutoML, logger_formatter
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flaml\automl\__init__.py", line 1, in <module>
    from flaml.automl.automl import AutoML, size
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flaml\automl\automl.py", line 19, in <module>
    from flaml.automl.ml import train_estimator
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flaml\automl\ml.py", line 11, in <module>
    from flaml.automl.data import group_counts
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flaml\automl\data.py", line 11, in <module>
    from flaml.automl.spark import DataFrame, Series, pd, ps, psDataFrame, psSeries
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flaml\automl\spark\__init__.py", line 31, in <module>
    import pandas as pd
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\compat\__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\compat\numpy\__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\_libs\__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas\_libs\interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

### Additional Information

```
Windows 10
Python 3.11.0
autogenstudio==0.1.5
sqlmodel==0.0.21
numpy==2.1.0
```

**Comment by Hk669** [comment]
@windowshopr can you try updating the sqlmodel to 0.0.22 and check if the issue still exists.

**Comment by windowshopr** [comment]
Nope, same issue

**Comment by Ethan0456** [comment]
@windowshopr I think its related to numpy, try a numpy version less than 2.0.0

**Comment by windowshopr** [comment]
I tried downgrading to `numpy==1.26.4` and got this traceback:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Scripts\autogenstudio.exe\__main__.py", line 4, in <module>
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogenstudio\__init__.py", line 1, in <module>
    from .chatmanager import *
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogenstudio\chatmanager.py", line 11, in <module>
    from .workflowmanager import WorkflowManager
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogenstudio\workflowmanager.py", line 7, in <module>
    import autogen
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\__init__.py", line 3, in <module>
    from .agentchat import *
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\agentchat\__init__.py", line 2, in <module>
    from .assistant_agent import AssistantAgent
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\agentchat\assistant_agent.py", line 5, in <module>       
    from .conversable_agent import ConversableAgent
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 19, in <module>    
    from ..code_utils import (
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\code_utils.py", line 15, in <module>
    from autogen import oai
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\oai\__init__.py", line 2, in <module>
    from autogen.oai.client import ModelClient, OpenAIWrapper
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\oai\client.py", line 9, in <module>
    from flaml.automl.logger import logger_formatter
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flaml\__init__.py", line 3, in <module>
    from flaml.automl import AutoML, logger_formatter
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flaml\automl\__init__.py", line 1, in <module>
    from flaml.automl.automl import AutoML, size
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flaml\automl\automl.py", line 19, in <module>
    from flaml.automl.ml import train_estimator
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flaml\automl\ml.py", line 12, in <module>
    from flaml.automl.model import BaseEstimator, TransformersEstimator
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\flaml\automl\model.py", line 72, in <module>
    from lightgbm import LGBMClassifier, LGBMRanker, LGBMRegressor
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\lightgbm\__init__.py", line 8, in <module>
    from .basic import Booster, Dataset, Sequence, register_logger
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\lightgbm\basic.py", line 20, in <module>
    from .compat import PANDAS_INSTALLED, concat, dt_DataTable, is_dtype_sparse, pd_DataFrame, pd_Series
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\lightgbm\compat.py", line 127, in <module>
    from dask.array import Array as dask_Array
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\dask\array\__init__.py", line 3, in <module>
    from .core import (
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\dask\array\core.py", line 22, in <module>
    from . import chunk
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\dask\array\chunk.py", line 7, in <module>
    from . import numpy_compat as npcompat
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\dask\array\numpy_compat.py", line 21, in <module>
    np.divide(0.4, 1, casting="unsafe", dtype=np.float),
                                              ^^^^^^^^
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\__init__.py", line 338, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
```

I tried downgrading to `numpy==1.19.0` before that deprecation warning, but am getting:

```
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Running from numpy source directory.
      <string>:460: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      Traceback (most recent call last):
        File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\chalu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\chalu\AppData\Local\Temp\pip-build-env-4y54f5x3\overlay\Lib\site-packages\setuptools\build_meta.py", line 373, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\chalu\AppData\Local\Temp\pip-build-env-4y54f5x3\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup          super().run_setup(setup_script=setup_script)
        File "C:\Users\chalu\AppData\Local\Temp\pip-build-env-4y54f5x3\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup          exec(code, locals())
        File "<string>", line 489, in <module>
        File "<string>", line 465, in setup_package
        File "C:\Users\chalu\AppData\Local\Temp\pip-install-y3sctjd3\numpy_f7b5736fd5204583b55b16d856221f1e\numpy\distutils\core.py", line 24, in 
          from numpy.distutils.command import config, config_compiler, \
        File "C:\Users\chalu\AppData\Local\Temp\pip-install-y3sctjd3\numpy_f7b5736fd5204583b55b16d856221f1e\numpy\distutils\command\config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "C:\Users\chalu\AppData\Local\Temp\pip-install-y3sctjd3\numpy_f7b5736fd5204583b55b16d856221f1e\numpy\distutils\mingw32ccompiler.py", 
line 28, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

A quick google search shows it's something to do with setuptools, but I have tried downgrading that to a handful of different versions as well, still nothing.

I think Studio needs to be upgraded to use the latest numpy version, that would be the answer here, but I'm willing to keep trying other suggestions. Thanks!

**Comment by Ethan0456** [comment]
@windowshopr, this might be the possible thing, you can try monkey patching as a short-term solution with numpy==1.26.4, this will define the deprecated np.float
```
np.float = float
```

**Comment by windowshopr** [comment]
`pip install numpy<1.24` fixed the issue, only now I'm getting a compatibility error with Pandas now too. I'll keep going down the rabbit hole of dependencies to get it working. Thanks for the suggestions.
