### ISSUE TITLE
[Bug]: websocket connection timing out when using docker jupyter executor

### ISSUE THREAD

**Issue by ChethanM555** [microsoft/autogen#3477]
### Describe the bug

When using docker executor in the chat, the websocket connection with the executor container times out during long running agent chats. The error returned is often difficult to understand - json.JSONDecodeError, websocket.WebSocketConnectionClosedException, ConnectionAbortedError or some Win error. 
Either the connection should be kept open in a separate thread (getting closed because we are not replying to server's pings) or should be reopened everytime a execution request is being sent.

### Steps to reproduce

1. setup a userproxy agent and code executor agent
2. sleep for 5 mins
3. initiate chat to execute some program like - "what are the first 10 Fibonacci numbers?"
4. The program should error out

### Model Used

gpt4o

### Expected Behavior

Code should get executed properly

### Additional Information

AutoGen - 0.2.33
OS - windows
python - 3.10

**Comment by scriptbotprime** [comment]
Something similar happens with the LocalJupyterServer.
```python
with LocalJupyterServer(
    log_file="log/jupyter_gateway.log", 
    log_level="DEBUG",
) as server:
    with JupyterCodeExecutor(server, output_dir=plots_dir, timeout=60*60) as jce:
        ...
```
Whenever the chat is idle for a while I get this error:
```
Next speaker: executor


>>>>>>>> EXECUTING CODE BLOCK (inferred language is python)...
Traceback (most recent call last):
  File "/projects/SCEA/containers/auto_gen/trexabot.py", line 91, in <module>
    response = user_proxy.initiate_chat(
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 1096, in initiate_chat
    self.send(msg2send, recipient, silent=silent)
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 732, in send
    recipient.receive(message, self, request_reply, silent)
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 896, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 2050, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/autogen/agentchat/groupchat.py", line 1104, in run_chat
    reply = speaker.generate_reply(sender=self)
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 2050, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 1548, in _generate_code_execution_reply_using_executor
    code_result = self._code_executor.execute_code_blocks(code_blocks)
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/autogen/coding/jupyter/jupyter_code_executor.py", line 92, in execute_code_blocks
    self._jupyter_kernel_client.wait_for_ready()
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/autogen/coding/jupyter/jupyter_client.py", line 155, in wait_for_ready
    message_id = self._send_message(content={}, channel="shell", message_type="kernel_info_request")
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/autogen/coding/jupyter/jupyter_client.py", line 141, in _send_message
    self._websocket.send_text(json.dumps(message))
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/websocket/_core.py", line 303, in send_text
    return self.send(text_data, ABNF.OPCODE_TEXT)
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/websocket/_core.py", line 297, in send
    return self.send_frame(frame)
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/websocket/_core.py", line 337, in send_frame
    l = self._send(data)
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/websocket/_core.py", line 559, in _send
    return send(self.sock, data)
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/websocket/_socket.py", line 179, in send
    return _send()
  File "/projects/SCEA/containers/auto_gen/.conda/lib/python3.10/site-packages/websocket/_socket.py", line 156, in _send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

```

**Comment by ekzhu** [comment]
cc @jackgerrits 

Thanks for raising the issue. I have seen this several times before. Would one of you like to submit a PR to fix it?
