### ISSUE TITLE
[Issue]: how autogen support multiple local model.

### ISSUE THREAD

**Issue by lambda7xx** [microsoft/autogen#3504]
### Describe the issue

according to the [Local-LLMs/](https://microsoft.github.io/autogen/blog/2023/07/14/Local-LLMs/), the autogen can support multiple local llm.

my command for fastchat 
First, launch the controller 
```python -m fastchat.serve.controller  ```
Then, launch the multiple model worker(s) 

```
python -m fastchat.serve.multi_model_worker \
    --model-path /data/llama2/Llama-2-7b-chat-hf \
    --model-names Llama-2-7b-chat-hf \
    --model-path /data/llama3/Meta-Llama-3-8B-hf \
    --model-names Meta-Llama-3-8B-hf

```

Finally, launch the RESTful API server

```
python -m fastchat.serve.openai_api_server --host localhost --port 8000
```

the code 
```
from autogen import oai

# create a chat completion request
response = oai.ChatCompletion.create(
    config_list=[
        {
            "model": "Llama-2-7b-chat-hf",
            "base_url": "http://localhost:8000/v1",
            "api_type": "openai",
            "api_key": "NULL",
        },
        {
            "model": "Meta-Llama-3-8B-hf",
            "base_url": "http://localhost:8000/v1",
            "api_type": "openai",
            "api_key": "NULL",
        }
    ],
    messages=[{"role": "user", "content": "Hi"}]
)
print(response)



```

my error is
```

[autogen.oai.completion: 09-11 07:07:20] {788} WARNING - Completion.create is deprecated in pyautogen v0.2 and openai>=1. The new openai requires initiating a client for inference. Please refer to https://microsoft.github.io/autogen/docs/Use-Cases/enhanced_inference#api-unification
Traceback (most recent call last):
  File "/home/xxxx/autogen/infe.py", line 4, in <module>
    response = oai.ChatCompletion.create(
  File "/home/xxxx/autogen/autogen/oai/completion.py", line 794, in create
    raise ERROR
AssertionError: (Deprecated) The autogen.Completion class requires openai<1 and diskcache. 
```

**Comment by yichuan520030910320** [comment]
Facing the same issue, I want to use a different model to serve this group chat, https://github.com/microsoft/autogen/blob/63d3297ffc66120a16e60391af538354a11e5d35/samples/apps/cap/py/demo/AGGroupChatDemo.py#L24, like using SGLang or vLLM on a different port(python -m sglang.launch_server --model-path meta-llama/Meta-Llama-3-8B-Instruct --port 30000) , so do you support this right now? If you do, how can I specify each agent to specific port(like rewrite OAI_CONFIG_LIST)? If not, can you support it? or give me some hints and I will give a PR here.

**Comment by yichuan520030910320** [comment]
Right now the OAI_CONFIG_LIST is sth like this when I only serve one local LLM ->
 [
  {
    "model": "gpt-4",
    "base_url": "http://127.0.0.1:30000/v1",
    "api_key": "NONE"
  }
]
But I want to serve different local LLM(like different fine-tuned model) how can I map them to different agent here? @sonichi @qingyun-wu
