### ISSUE TITLE
[Bug]: autogenstudio fails to start

### ISSUE THREAD

**Issue by stefanstranger** [microsoft/autogen#3548]
### Describe the bug

When running autogenstudio ui from a conda environment I get the following error:
```
flaml.automl is not available. Please install flaml[automl] to enable AutoML functionalities.
Traceback (most recent call last):
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\Scripts\autogenstudio.exe\__main__.py", line 4, in <module>
    from autogenstudio.cli import run
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\site-packages\autogenstudio\__init__.py", line 1, in <module>
    from .chatmanager import *
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\site-packages\autogenstudio\chatmanager.py", line 11, in <module>
    from .workflowmanager import WorkflowManager
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\site-packages\autogenstudio\workflowmanager.py", line 7, in <module>
    import autogen
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\site-packages\autogen\__init__.py", line 9, in <module>
    from .agentchat import *
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\site-packages\autogen\agentchat\__init__.py", line 8, in <module>
    from .assistant_agent import AssistantAgent
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\site-packages\autogen\agentchat\assistant_agent.py", line 11, in <module>
    from .conversable_agent import ConversableAgent
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\site-packages\autogen\agentchat\conversable_agent.py", line 25, in <module>
    from ..code_utils import (
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\site-packages\autogen\code_utils.py", line 23, in <module>
    from autogen import oai
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\site-packages\autogen\oai\__init__.py", line 8, in <module>
    from autogen.oai.client import ModelClient, OpenAIWrapper
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\site-packages\autogen\oai\client.py", line 15, in <module>
    from flaml.automl.logger import logger_formatter
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\site-packages\flaml\automl\__init__.py", line 1, in <module>
    from flaml.automl.automl import AutoML, size
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\site-packages\flaml\automl\automl.py", line 20, in <module>
    from flaml.automl.ml import huggingface_metric_to_mode, sklearn_metric_name_set, spark_metric_name_dict, train_estimator
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\site-packages\flaml\automl\ml.py", line 12, in <module>
    from flaml.automl.model import BaseEstimator, TransformersEstimator
  File "C:\Users\stefstr\AppData\Local\miniconda3\envs\autogenstudio\lib\site-packages\flaml\automl\model.py", line 19, in <module>
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
```

### Steps to reproduce

1. Create a new conda environment with: conda create -n autogenstudio python=3.10
2. Set environment variable: conda env config vars set AZURE_OPENAI_API_KEY=1234566
3. Activate environment: conda activate autogenstudio
4. Install autogenstudio: pip install autogenstudio
5. Start autogenstudio: autogenstudio ui

### Model Used

Azure OpenAI gpt-4o

### Expected Behavior

autogenui should start

### Additional Information

OS: Windows 11
Python version: 3.11 and 3.10

**Comment by martinbel** [comment]
I'm finding the same issue. It seems the flaml dependency broke autogen.

**Comment by jochenvw** [comment]
+1

**Comment by ccran** [comment]
+1

**Comment by stefanstranger** [comment]
Temporary solution is to create a constraints.txt file with the following content:

```txt
flaml==2.2.0
```

run: conda install -c .\constraints.txt autogenstudio

**Comment by martinbel** [comment]
@stefanstranger how would this work with pip?

**Comment by stefanstranger** [comment]
Sorry that was a typo.

Run pip install - c constraints.txt autogen

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jgarnie** [comment]
is there any news about it? still broken and we can not use autogen

**Comment by taitasu555** [comment]
+1

**Comment by victordibia** [comment]
How are you installing it e.g., in a new conda environment?
If you are looking to use the recent version of autogenstudio,  follow the installation instructions here https://github.com/microsoft/autogen/discussions/4208

**Comment by taitasu555** [comment]
temporary solving for pip is added constraints.txt like below
```
flaml==2.2.0

```
and then execute the below command it works for me
```
pip install autogenstudio --constraint constraints.txt         
```

**Comment by taitasu555** [comment]
> How are you installing it e.g., in a new conda environment? If you are looking to use the recent version of autogenstudio, follow the installation instructions here [#4208](https://github.com/microsoft/autogen/discussions/4208)

Thanks! works

**Comment by jackgerrits** [comment]
I believe this is resolved in the latest versions of studio
