### ISSUE TITLE
autogen-magentic-one ModuleNotFoundError: No module named 'autogen_core'

### ISSUE THREAD

**Issue by fahdmirza** [microsoft/autogen#4079]
Hi,
  I am trying to run example for autogen-magentic-one and followed all the steps in your docs but getting following error:

python autogen-magentic-one/examples/example_coder.py --logs_dir ./my_logs
Traceback (most recent call last):
  File "/home/Ubuntu/autogen/python/packages/autogen-magentic-one/examples/example_coder.py", line 10, in <module>
    from autogen_core.application import SingleThreadedAgentRuntime
ModuleNotFoundError: No module named 'autogen_core'

The docs mentioned to run example.py but there is no example.py in the repo. 

I am running this in conda environment. Thanks. 
regards

**Comment by victordibia** [comment]
Hi @fahdmirza,

Following the instructions [here](https://github.com/microsoft/autogen/tree/main/python/packages/autogen-magentic-one#setup-and-usage), ensure you have run the pip install from github main (not pypi).

```python
git clone  https://github.com/microsoft/autogen.git
cd autogen/python/packages/autogen-magentic-one
pip install -e .
```

This should install `autogen_core` and `autogen_ext` which are needed for magentic one.

Please let us know if you have any other issues.

@afourney @husseinmozannar

**Comment by fahdmirza** [comment]
Thanks for update. Unfortunately, still same error. Also where is example.py mentioned in Readme? I am trying to review it for my channel https://www.youtube.com/@fahdmirza and that is why trying to use a representative example. Thanks. 

Fahd

**Comment by ekzhu** [comment]
@fahdmirza  you quite early on this. We are working on the API so be aware of breaking changes coming until this stabilize toward end of Nov.

**Comment by fahdmirza** [comment]
I understand, I just want to have a working demo of it to get a taste for my viewers and intend to cover it again when it matures. Already a big fan of Autogen and have been covering it since last 9 months or so in various videos. I will give it a try again shortly as per above guidelines, thanks.

**Comment by OminousIndustries** [comment]
@fahdmirza - Installation instructions that worked for me after having the same issue can be seen in this video at 17:44 - https://youtu.be/WXyY-c4PYTQ

**Comment by fahdmirza** [comment]
Hi Guys, its working now and the video is live : https://youtu.be/gOzsQ-hX2B0?si=1SnMBjqA_Th1wEnJ  [Magentic Installation](url)

**Comment by faboweb** [comment]
Using uv worked

**Comment by CellCS** [comment]
Issue: 

![Image](https://github.com/user-attachments/assets/04506027-0779-41fe-8389-95a3e418f85a)

Solution Steps:
1. Install 'uv' by referencing [uv installation](https://docs.astral.sh/uv/getting-started/installation/)

```bash
# install uv
curl -LsSf https://astral.sh/uv/install.sh | sh
# add $HOME/.local/bin to your PATH 
source $HOME/.local/bin/env
```

![Image](https://github.com/user-attachments/assets/445af91c-478b-4a4a-b6c5-3eac52ac4ffc)

3. Locate at "autogen/python/" and install all dependencies, 

```bash
uv sync  --all-extras
```

4 issue is solved: .venv is created unser "/autogen/python"

![Image](https://github.com/user-attachments/assets/75393fa1-d2a1-4e25-bf01-bf8bb918d821)

5:  execute example.

```bash
source .venv/bin/activate
cd packages/autogen-magentic-one 
python3 examples/example.py --logs_dir ./my_logs
```

**Comment by EnGassa** [comment]
> We are working on making installation much easier, please bear with us as we finish that.
> 
> For now:
> 
> The example script is here https://github.com/microsoft/autogen/blob/main/python/packages/autogen-magentic-one/examples/example.py
> 
> Make sure you are on the main branch and not staging (previous readme had an error)
> 
> The easiest way to install is with uv:
> 
> git clone  https://github.com/microsoft/autogen.git
> cd autogen/python
> uv sync  --all-extras
> source .venv/bin/activate
> cd packages/autogen-magentic-one
> pip install -e .
> then follow the complete README in https://github.com/microsoft/autogen/blob/main/python/packages/autogen-magentic-one/README.md

This is the way!

**Comment by shane-jumpstep** [comment]
No luck for me on my intel based mac, any updates?

**Comment by shane-jumpstep** [comment]
this is my first exception   File "/Users/shaneblaser/repos/jump_step/test/ms_magentic_one/autogen/python/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/shaneblaser/repos/jump_step/test/ms_magentic_one/autogen/python/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/Users/shaneblaser/repos/jump_step/test/ms_magentic_one/autogen/python/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/Users/shaneblaser/repos/jump_step/test/ms_magentic_one/autogen/python/.venv/lib/python3.11/site-packages/docker/transport/unixconn.py", line 26, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by shane-jumpstep** [comment]
can we just run this in a container?

**Comment by CellCS** [comment]
> this is my first exception File "/Users/shaneblaser/repos/jump_step/test/ms_magentic_one/autogen/python/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen response = self._make_request( ^^^^^^^^^^^^^^^^^^^ File "/Users/shaneblaser/repos/jump_step/test/ms_magentic_one/autogen/python/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request conn.request( File "/Users/shaneblaser/repos/jump_step/test/ms_magentic_one/autogen/python/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 441, in request self.endheaders() File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1281, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1041, in _send_output self.send(msg) File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 979, in send self.connect() File "/Users/shaneblaser/repos/jump_step/test/ms_magentic_one/autogen/python/.venv/lib/python3.11/site-packages/docker/transport/unixconn.py", line 26, in connect sock.connect(self.unix_socket) FileNotFoundError: [Errno 2] No such file or directory

@shane-jumpstep 

would you mind create one py file with following script to test docker env?

```
import docker
client = docker.from_env()
try:
    print(client.version())
except Exception as e:
    print("Error connecting to Docker:", e)
```

**Comment by DamjanRI** [comment]
Does not work on Windows, tried uv solution same thing   File "f:\Autogen\autogen\python\packages\autogen-magentic-one\examples\example.py", line 8, in <module>
    from autogen_core.application import SingleThreadedAgentRuntime
ModuleNotFoundError: No module named 'autogen_core'

**Comment by afourney** [comment]
> Does not work on Windows, tried uv solution same thing File "f:\Autogen\autogen\python\packages\autogen-magentic-one\examples\example.py", line 8, in from autogen_core.application import SingleThreadedAgentRuntime ModuleNotFoundError: No module named 'autogen_core'

We are working to make this easier. We've done most of our development on the WSL environment in Windows. If possible, I would recommend this route. I'm also going to see if we can provide a Docker environment that will make things easier.

**Comment by Mamba04-gif** [comment]
Windows solution:
follow the same steps posted by @CellCS with these changes

1. run powershell as admin and install uv:

`powershell -ExecutionPolicy Bypass -c "pip install uv"`

 2. do this in cmd to activate virutal envirorment:

`.venv\Scripts\activate`

3. do this in cmd to run the code:

`python examples/example.py --logs_dir ./my_logs`

**Comment by CellCS** [comment]
@Mamba04-gif  thanks for your confirmation about solution.

**Comment by shane-jumpstep** [comment]
Thank you

**Comment by jackgerrits** [comment]
@kaelzhang81 what version of uv are you using?

**Comment by DamjanRI** [comment]
Instructions are unclear for windows here are correct one for cmd

cd path_to_autogen\autogen\python
uv sync --all-extras (only First time)
.venv\Scripts\activate (always before usage)
cd packages\autogen-magentic-one\examples

# Specify logs directory
python examples/example.py --logs_dir ./logs

# Enable human-in-the-loop mode
python examples/example.py --logs_dir ./logs --hil_mode

# Save screenshots of browser
python examples/example.py --logs_dir ./logs --save_screenshots

**Comment by vanetreg** [comment]
Windsurf Cascade suggested me to install them separately, in this order (copied):
```
pip install -e autogen-core      # Install core first
pip install -e autogen-ext       # Install extensions second
pip install -e autogen-magentic-one  # Install custom implementation last
```

I did it in WSL. It works this way.

**Comment by MilenAyvazyan** [comment]
![Image](https://github.com/user-attachments/assets/2fa398bf-ce89-4202-84e7-cffca6092615)
Hi, can you help me with this?

**Comment by bluevision918** [comment]
All the packages have been installed successfully in windows machine. But I got error as below:
 python examples/example.py --logs_dir ./logs
C:\Users\lim\Documents\Magentic_One\autogen\python\.venv\Lib\site-packages\pydub\utils.py:300: SyntaxWarning: invalid escape sequence '\('
  m = re.match('([su]([0-9]{1,2})p?) \(([0-9]{1,2}) bit\)$', token)
C:\Users\lim\Documents\Magentic_One\autogen\python\.venv\Lib\site-packages\pydub\utils.py:301: SyntaxWarning: invalid escape sequence '\('
  m2 = re.match('([su]([0-9]{1,2})p?)( \(default\))?$', token)
C:\Users\lim\Documents\Magentic_One\autogen\python\.venv\Lib\site-packages\pydub\utils.py:310: SyntaxWarning: invalid escape sequence '\('
  elif re.match('(flt)p?( \(default\))?$', token):
C:\Users\lim\Documents\Magentic_One\autogen\python\.venv\Lib\site-packages\pydub\utils.py:314: SyntaxWarning: invalid escape sequence '\('
  elif re.match('(dbl)p?( \(default\))?$', token):
Traceback (most recent call last):
  File "C:\Users\lim\Documents\Magentic_One\autogen\python\packages\autogen-magentic-one\examples\example.py", line 115, in <module>
    asyncio.run(main(args.logs_dir, args.hil_mode, args.save_screenshots))
  File "C:\Users\lim\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\lim\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lim\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\asyncio\base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\lim\Documents\Magentic_One\autogen\python\packages\autogen-magentic-one\examples\example.py", line 83, in main
    await actual_surfer.init(
  File "C:\Users\lim\Documents\Magentic_One\autogen\python\packages\autogen-magentic-one\src\autogen_magentic_one\agents\multimodal_web_surfer\multimodal_web_surfer.py", line 158, in init
    browser = await self._playwright.chromium.launch(**launch_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lim\Documents\Magentic_One\autogen\python\.venv\Lib\site-packages\playwright\async_api\_generated.py", line 14398, in launch
    await self._impl_obj.launch(
  File "C:\Users\lim\Documents\Magentic_One\autogen\python\.venv\Lib\site-packages\playwright\_impl\_browser_type.py", line 95, in launch
    Browser, from_channel(await self._channel.send("launch", params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lim\Documents\Magentic_One\autogen\python\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lim\Documents\Magentic_One\autogen\python\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at C:\Users\lim\AppData\Local\ms-playwright\chromium-1140\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x00000202F2C01760>
Traceback (most recent call last):
  File "C:\Users\lim\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\asyncio\base_subprocess.py", line 126, in __del__
  File "C:\Users\lim\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Users\lim\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\asyncio\proactor_events.py", line 109, in close
  File "C:\Users\lim\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\asyncio\base_events.py", line 794, in call_soon
  File "C:\Users\lim\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\asyncio\base_events.py", line 540, in _check_closed
RuntimeError: Event loop is closed

**Comment by MilenAyvazyan** [comment]
![Image](https://github.com/user-attachments/assets/f301f9f7-a643-467d-a638-7eba3140f89b)
Hi, Can you help me with this?)
