### ISSUE TITLE
Sqlite3 errors in docker container on macbook pro m2 apple silicon

### ISSUE THREAD

**Issue by jeffbiocode** [microsoft/autogen#415]
Traceback (most recent call last):
  File "/workspaces/autogen/test/marketingteam.py", line 62, in <module>
    project_lead.initiate_chat(
  File "/workspaces/autogen/autogen/agentchat/conversable_agent.py", line 531, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/workspaces/autogen/autogen/agentchat/conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "/workspaces/autogen/autogen/agentchat/conversable_agent.py", line 462, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "/workspaces/autogen/autogen/agentchat/conversable_agent.py", line 781, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/workspaces/autogen/autogen/agentchat/groupchat.py", line 164, in run_chat
    reply = speaker.generate_reply(sender=self)
  File "/workspaces/autogen/autogen/agentchat/conversable_agent.py", line 781, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/workspaces/autogen/autogen/agentchat/conversable_agent.py", line 606, in generate_oai_reply
    response = oai.ChatCompletion.create(
  File "/workspaces/autogen/autogen/oai/completion.py", line 803, in create
    response = cls.create(
  File "/workspaces/autogen/autogen/oai/completion.py", line 834, in create
    return cls._get_response(params, raise_on_ratelimit_or_timeout=raise_on_ratelimit_or_timeout)
  File "/workspaces/autogen/autogen/oai/completion.py", line 272, in _get_response
    cls._cache.set(key, response)
  File "/home/vscode/.local/lib/python3.10/site-packages/diskcache/core.py", line 796, in set
    with self._transact(retry, filename) as (sql, cleanup):
  File "/usr/local/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/vscode/.local/lib/python3.10/site-packages/diskcache/core.py", line 744, in _transact
    sql('COMMIT')
sqlite3.OperationalError: disk I/O error

When doing a group chat it runs for a round or two and then throws at this error

**Comment by thinkall** [comment]
Are you running the code inside a docker container? Would it work in local OS? The error shows diskcache doesn't work in your environment.
