### ISSUE TITLE
Ubuntu 24 is able to run Magentic One, but every time in the end it gives me this error.

### ISSUE THREAD

**Issue by ghosert** [microsoft/autogen#4162]
### What happened?

I followed the doc to setup everything for Magentic One and run it with this sample:

╭─  gmk-ubuntu   ~/autogen/python/packages/autogen-magentic-one                                                                                                                                                                             
╰─ python examples/example.py --logs_dir ./my_logs

it works well but in the end of the session, it reports this error:

No agent selected.
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7c0f158d7f60>
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/usr/lib/python3.12/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/usr/lib/python3.12/asyncio/unix_events.py", line 767, in close
    self.write_eof()
  File "/usr/lib/python3.12/asyncio/unix_events.py", line 753, in write_eof
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
    self._check_closed()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

### What did you expect to happen?

No error should be reported like above

### How can we reproduce it (as minimally and precisely as possible)?

as mentioned in the above.

### AutoGen version

Latest in the main branch

### Which package was this bug in

Magentic One

### Model used

gpt-4

### Python version

3.12

### Operating system

Ubuntu 24

**Comment by afourney** [comment]
Hmm. Thanks for the report. @jackgerrits any idea? This looks like a runtime thing.

**Comment by husseinmozannar** [comment]
Yes I have seen this error before and discussed it with @ekzhu , I believe it is Python version issue with 3.12, but not sure how to fix

**Comment by ekzhu** [comment]
The base worker agent has a dangling background task running when the program exits.

**Comment by dominicdev** [comment]
fix for this?

**Comment by husseinmozannar** [comment]
Not yet, but the rewrite of MagenticOne on AgentChat should resolve this. We expect this to be fully out in the next few weeks or sooner.

**Comment by illusions-LYY** [comment]
> Not yet, but the rewrite of MagenticOne on AgentChat should resolve this. We expect this to be fully out in the next few weeks or sooner.

The issue still exists in Python 3.12 + AutoGen 0.5.6.
