### ISSUE TITLE
autogenstudio ui start fails with ImportError

### ISSUE THREAD

**Issue by maxjeblick** [microsoft/autogen#4245]
### What happened?

Running `autogenstudio ui --port 8081` fails with the following ImportError:

```
INFO:     Will watch for changes in these directories: ['/home/max/PycharmProjects/autogen/python/packages/autogen-studio/frontend']
INFO:     Uvicorn running on http://127.0.0.1:8081 (Press CTRL+C to quit)
INFO:     Started reloader process [588123] using WatchFiles
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/max/PycharmProjects/autogen/python/.venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/home/max/PycharmProjects/autogen/python/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/max/PycharmProjects/autogen/python/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/max/PycharmProjects/autogen/python/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/max/PycharmProjects/autogen/python/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/max/PycharmProjects/autogen/python/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/max/PycharmProjects/autogen/python/packages/autogen-studio/autogenstudio/web/app.py", line 11, in <module>
    from .routes import sessions, runs, teams, agents, models, tools, ws
  File "/home/max/PycharmProjects/autogen/python/packages/autogen-studio/autogenstudio/web/routes/sessions.py", line 4, in <module>
    from ..deps import get_db
  File "/home/max/PycharmProjects/autogen/python/packages/autogen-studio/autogenstudio/web/deps.py", line 8, in <module>
    from .managers.connection import WebSocketManager
  File "/home/max/PycharmProjects/autogen/python/packages/autogen-studio/autogenstudio/web/managers/__init__.py", line 1, in <module>
    from .connection import WebSocketManager
  File "/home/max/PycharmProjects/autogen/python/packages/autogen-studio/autogenstudio/web/managers/connection.py", line 12, in <module>
    from autogen_agentchat.messages import InnerMessage, ChatMessage, TextMessage
ImportError: cannot import name 'InnerMessage' from 'autogen_agentchat.messages' (/home/max/PycharmProjects/autogen/python/packages/autogen-agentchat/src/autogen_agentchat/messages.py)
```

Looking at https://github.com/microsoft/autogen/blob/main/python/packages/autogen-agentchat/src/autogen_agentchat/messages.py, the imported class  'InnerMessage' is missing

### What did you expect to happen?

Command runs without error

### How can we reproduce it (as minimally and precisely as possible)?

Run `connections.py` with `autogen_agentchat.messages` import pointing to https://github.com/microsoft/autogen/blob/main/python/packages/autogen-agentchat/src/autogen_agentchat/messages.py

### AutoGen version

fa1d08005e9eb010f3ff662601b0f7a29e40c937

### Which package was this bug in

AutoGen Studio

### Model used

NA

### Python version

Python3.10

### Operating system

Ubuntu 22.04

**Comment by victordibia** [comment]
Thanks! 
This is due to a recent refactor on `AgentChat`.
Are you working from the dev release on pypi or from source?

I will try to fix this with a new dev release now.

@ekzhu .

**Comment by victordibia** [comment]
Pushed a fix, let me know if there are still issues.

**Comment by maxjeblick** [comment]
Thanks a lot for the vert fast reply, the issue is no longer present!
