### ISSUE TITLE
NO AGENT SELECTED

### ISSUE THREAD

**Issue by genregod** [microsoft/autogen#4441]
### What happened?

While going and running magentik one in the command terminal I got a trace back error that said no agent selected followed by the following trace back error which it said value error: IO operation on closed pipe.

---------------------------------------------------------------------------
[2024-12-01T04:00:43.388354], Orchestrator (termination condition):

No agent selected.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020728B94680>
Traceback (most recent call last):
  File "C:\Users\south\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\south\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\south\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000020728B6AE80>
Traceback (most recent call last):
  File "C:\Users\south\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_subprocess.py", line 125, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\south\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_subprocess.py", line 70, in __repr__
    info.append(f'stdin={stdin.pipe}')
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\south\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\south\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe

### What did you expect to happen?

I had expected it to continue utilizing the multi agent system to go and actually fulfill the task I'd given it and instead I was met with this error twice

### How can we reproduce it (as minimally and precisely as possible)?

Tesunsure of reproduction

### AutoGen version

0.0.1

### Which package was this bug in

Magentic One

### Model used

GPT-4O-LATEST

### Python version

3.11.9

### Operating system

windows 11 Pro 23H2

### Any additional info you think would be helpful for fixing this bug

Unsure as of yet what's would be helpful in fixing the bug just notating it in the issues list as it occurs.

**Comment by husseinmozannar** [comment]
related to #4237 , #4338, #4162 

The orchestrator finished it's work correctly but just at termination there is a bug we are fixing with the port of Magentic-one to agentchat soon
