### ISSUE TITLE
ResourceWarning: unclosed transport when importing web_surfer

### ISSUE THREAD

**Issue by rickyloynd-microsoft** [microsoft/autogen#4821]
### What happened?

The attached (extremely simple) script invokes `OpenAIChatCompletionClient` and gets an appropriate response.

But on app shutdown a warning about "unclosed transport" is printed. As noted in the code, the warning disappears if the unused web_surfer import line is removed.

```
(ag3) rdlrdl@riloynd6:~/repos2/autogen/python/packages/autogen-ext/samples$ python warning_repro.py
Function calls again,
In endless looping layers—
Code within the code.
/home/rdlrdl/miniconda3/envs/ag3/lib/python3.10/asyncio/selector_events.py:710: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=6>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

[warning_repro.txt](https://github.com/user-attachments/files/18256499/warning_repro.txt)

```python
import asyncio
from autogen_ext.models.openai import OpenAIChatCompletionClient
from autogen_core.models import UserMessage

# The following import line leads to a warning about 'unclosed transport' on shutdown.
from autogen_ext.agents.web_surfer._utils import message_content_to_str

# The following line will do it too.
# from autogen_ext.agents.web_surfer import MultimodalWebSurfer


async def quick_test():
    client = OpenAIChatCompletionClient(
        model="gpt-4o-2024-08-06",
        api_key="")
    user_message = UserMessage(content="Write a haiku about recursion in programming.", source="user")
    response = await client.create([user_message])
    return response.content


if __name__ == "__main__":
    content = asyncio.run(quick_test())
    print(content)

```

### What did you expect to happen?

Same behavior but without the warning.

### How can we reproduce it (as minimally and precisely as possible)?

Install the following in a virtual environment:
```
pip install -e autogen-core      
pip install -e autogen-agentchat
pip install -e autogen-ext[openai]
pip install -e autogen-ext[web-surfer]
```
 
Run the attached code (after renaming the extension to .py, and supplying an api_key).

### AutoGen version

0.4.0.dev11

### Which package was this bug in

Core

### Model used

gpt-4o-2024-08-06

### Python version

3.10

### Operating system

WSL2

**Comment by brendanfoxen** [comment]
I'm having the exact same issue:

.pyenv/versions/3.10.13/lib/python3.10/asyncio/selector_events.py:710: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=10>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)

Using Autogen 0.4.2
Python 3.10

**Comment by madlogos** [comment]
Yes, I met exactly the same problem with websurfer, autogen 0.4.5 (python 3.10)

```
C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_utils.py:112: ResourceWarning: unclosed <PipeHandle handle=3012>
  _warn(f"unclosed {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000121B56C0790>
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x00000121B56A2C20>
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 125, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_subprocess.py", line 70, in __repr__
    info.append(f'stdin={stdin.pipe}')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py:1072: ResourceWarning: subprocess 41452 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_utils.py:112: ResourceWarning: unclosed <PipeHandle handle=2884>
  _warn(f"unclosed {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000121B56C0790>
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
```

**Comment by ekzhu** [comment]
@afourney  have you seen this on Windows?

**Comment by afourney** [comment]
I've traced it to this:

```python
import asyncio
from autogen_ext.models.openai import OpenAIChatCompletionClient
from autogen_core.models import UserMessage

# The following line will raise the error
import markitdown

async def quick_test():
    client = OpenAIChatCompletionClient(model="gpt-4o-2024-08-06")
    user_message = UserMessage(content="Write a haiku about recursion in programming.", source="user")
    response = await client.create([user_message])
    return response.content

if __name__ == "__main__":
    content = asyncio.run(quick_test())
    print(content)
```

Investigating further.

**Comment by afourney** [comment]
New minimal example:

```
import asyncio
from autogen_ext.models.openai import OpenAIChatCompletionClient
from autogen_core.models import UserMessage

# The following lines will do it too.
from warnings import resetwarnings
resetwarnings()


async def quick_test():
    client = OpenAIChatCompletionClient(model="gpt-4o-2024-08-06")
    user_message = UserMessage(content="Write a haiku about recursion in programming.", source="user")
    response = await client.create([user_message])
    return response.content


if __name__ == "__main__":
    content = asyncio.run(quick_test())
    print(content)
```

@jackgerrits @ekzhu How do you want to approach this? It seems the AutoGen framework has always had this issue, but somewhere, in some package, warnings were being suppressed by filters.

**Comment by ekzhu** [comment]
I think we never close our model clients. Added close:

```python
import asyncio
from autogen_ext.models.openai import OpenAIChatCompletionClient
from autogen_core.models import UserMessage

# The following lines will do it too.
from warnings import resetwarnings
resetwarnings()


async def quick_test():
    client = OpenAIChatCompletionClient(model="gpt-4o-2024-08-06")
    user_message = UserMessage(content="Write a haiku about recursion in programming.", source="user")
    response = await client.create([user_message])
    await client._client.close()
    return response.content


if __name__ == "__main__":
    content = asyncio.run(quick_test())
    print(content)
```

The output is 😆 

```
Code loops on itself,  
Layers unfold in the depths,  
Elegant design.
```

**Comment by afourney** [comment]
> I think we never close our model clients. Added close:
> 
> import asyncio
> from autogen_ext.models.openai import OpenAIChatCompletionClient
> from autogen_core.models import UserMessage
> 
> # The following lines will do it too.
> from warnings import resetwarnings
> resetwarnings()
> 
> 
> async def quick_test():
>     client = OpenAIChatCompletionClient(model="gpt-4o-2024-08-06")
>     user_message = UserMessage(content="Write a haiku about recursion in programming.", source="user")
>     response = await client.create([user_message])
>     await client._client.close()
>     return response.content
> 
> 
> if __name__ == "__main__":
>     content = asyncio.run(quick_test())
>     print(content)
> The output is 😆
> 
> ```
> Code loops on itself,  
> Layers unfold in the depths,  
> Elegant design.
> ```

Indeed. Related: https://github.com/openai/openai-python/issues/140

**Comment by afourney** [comment]
MarkItDown 0.0.2 will avoid resetting the warnings filters (https://github.com/microsoft/markitdown/pull/1101), and I will update WebSurfer here when it ships. The underlying problem still needs to be fixed. Namely, our model clients will need to be updated to include a close() command.

**Comment by ekzhu** [comment]
The patch is released: https://github.com/microsoft/autogen/releases/tag/python-v0.4.8.2
