### ISSUE TITLE
Custom Qdrant Embeddings Not Working

### ISSUE THREAD

**Issue by kdcokenny** [microsoft/autogen#533]
Code:
```python
# %%
%pip install -q pyautogen qdrant-client fastembed
%pip install -q chromadb pypdf # required by autogen for some reason

# %%
from qdrant_client import QdrantClient

host = "host_url"

client = QdrantClient(host=host, api_key="...")

# %%
config_list = [
    {
        'model': 'gpt-3.5-turbo',
        'api_key': '...',
    },
]

# %%
import autogen

autogen.ChatCompletion.start_logging()

# %%
from autogen.agentchat.contrib.qdrant_retrieve_user_proxy_agent import QdrantRetrieveUserProxyAgent

ragproxyagent = QdrantRetrieveUserProxyAgent(
    name="ragproxyagent",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    retrieve_config={
        "task": "qa",
        "chunk_token_size": 2000,
        "model": config_list[0]["model"],
        "client": client,
        "embedding_model": "BAAI/bge-base-en-v1.5",
        "collection_name": "test_collection",
    },
)

# %%
from autogen.agentchat.contrib.retrieve_assistant_agent import RetrieveAssistantAgent

assistant = RetrieveAssistantAgent(
    name="assistant", 
    system_message="You are a helpful assistant.",
    llm_config={
        "request_timeout": 600,
        "seed": 42,
        "config_list": config_list,
    },
)

# %%
assistant.reset()

qa_problem = "What is AutoGen?"
ragproxyagent.initiate_chat(assistant, problem=qa_problem)
```

Error:
```zsh
---------------------------------------------------------------------------
UnexpectedResponse                        Traceback (most recent call last)
/home/kenny/workspace/elapse/packages/research/notebooks/autogen-rag.ipynb Cell 7 line 4
      [1](vscode-notebook-cell://wsl%2Bubuntu/home/kenny/workspace/elapse/packages/research/notebooks/autogen-rag.ipynb#W5sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0) assistant.reset()
      [3](vscode-notebook-cell://wsl%2Bubuntu/home/kenny/workspace/elapse/packages/research/notebooks/autogen-rag.ipynb#W5sdnNjb2RlLXJlbW90ZQ%3D%3D?line=2) qa_problem = "What is AutoGen?"
----> [4](vscode-notebook-cell://wsl%2Bubuntu/home/kenny/workspace/elapse/packages/research/notebooks/autogen-rag.ipynb#W5sdnNjb2RlLXJlbW90ZQ%3D%3D?line=3) ragproxyagent.initiate_chat(assistant, problem=qa_problem)

File [~/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:531](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:531), in ConversableAgent.initiate_chat(self, recipient, clear_history, silent, **context)
    [517](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:517) """Initiate a chat with the recipient agent.
    [518](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:518) 
    [519](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:519) Reset the consecutive auto reply counter.
ref='~/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:0'>0</a>;32m   (...)
    [528](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:528)         "message" needs to be provided if the `generate_init_message` method is not overridden.
    [529](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:529) """
    [530](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:530) self._prepare_chat(recipient, clear_history)
--> [531](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py:531) self.send(self.generate_init_message(**context), recipient, silent=silent)

File [~/.local/lib/python3.10/site-packages/autogen/agentchat/contrib/retrieve_user_proxy_agent.py:404](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/contrib/retrieve_user_proxy_agent.py:404), in RetrieveUserProxyAgent.generate_init_message(self, problem, n_results, search_string)
    [393](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/contrib/retrieve_user_proxy_agent.py:393) """Generate an initial message with the given problem and prompt.
    [394](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/contrib/retrieve_user_proxy_agent.py:394) 
    [395](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/contrib/retrieve_user_proxy_agent.py:395) Args:
ref='~/.local/lib/python3.10/site-packages/autogen/agentchat/contrib/retrieve_user_proxy_agent.py:0'>0</a>;32m   (...)
    [401](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/contrib/retrieve_user_proxy_agent.py:401)     str: the generated prompt ready to be sent to the assistant agent.
    [402](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/contrib/retrieve_user_proxy_agent.py:402) """
    [403](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/autogen/agentchat/contrib/retrieve_user_proxy_agent.py:403) self._reset()
...
---> [97](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/kenny/workspace/elapse/packages/research/notebooks/~/.local/lib/python3.10/site-packages/qdrant_client/http/api_client.py:97) raise UnexpectedResponse.for_response(response)

UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Wrong input: Vector params for fast-bge-small-en are not specified in config"},"time":0.000019818}'
```

It seems like it uses `fast-bge-small-en` No matter what I set it to.

**Comment by kdcokenny** [comment]
So I noticed this:
```python
    if client is None:
        client = QdrantClient(**qdrant_client_options)
        client.set_model(embedding_model)
    ```

Which is weird because it only sets the embedding model if the client is none. I modified this and got a similar error, but progress is being made.
```zsh
UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Wrong input: Vector params for fast-bge-base-en-v1.5 are not specified in config"},"time":0.000018212}'
```

**Comment by kdcokenny** [comment]
Alright, so the issue was not with this implementation, it was with how I added the documentation to qdrant. 

Seems to use fastembed it's a requirement to use their new .add command and set the model with client.set_model().

This is what it looks like in the qdrant dashboard:
![image](https://github.com/microsoft/autogen/assets/99611484/833cd01f-a4d0-4a96-bb36-372b155c037e)

I will leave this issue open for now in case someone would like to use this as an opportunity for documentation specification. But if not, and you don't think it is necessary, this may be closed.

**Comment by sonichi** [comment]
@Anush008 is the contributor of the qdrant feature. Assigning this issue to @Anush008

**Comment by Anush008** [comment]
Hey @sonichi, from https://github.com/microsoft/autogen/issues/533#issuecomment-1793281817, the issue seems to have been resolved.

**Comment by pebeid** [comment]
I'm still seeing the issue. I reverted to using the names in `qdrant_client/qdrant_fastembed.py`

```
datasource: {'id': '65cb12a366e6eaac7dad5fe3', 'model': 'BAAI/bge-small-en-v1.5'}
Successfully connected to Qdrant. Collections: collections=[CollectionDescription(name='65c9a796d49e3e22ee68060e'), CollectionDescription(name='65c9ae88d49e3e22ee68064c'), CollectionDescription(name='65cb0ae1b59e5604d7a5b280'), CollectionDescription(name='65c4283aa02ed274fd18a2a1'), CollectionDescription(name='65c99c4dd49e3e22ee6805fe'), CollectionDescription(name='65cb12a366e6eaac7dad5fe3'), CollectionDescription(name='65c9c33ca8e43ebf9c259bac'), CollectionDescription(name='65c9ac74d49e3e22ee68062f'), CollectionDescription(name='65c30bf754671384a4ffe5a5'), CollectionDescription(name='65c9a9abd49e3e22ee68061c')]
docs_path is not provided in retrieve_config. Will raise ValueError if the collection `65cb12a366e6eaac7dad5fe3` doesn't exist. Set docs_path to None to suppress this warning.
query qdant 65cb12a366e6eaac7dad5fe3 BAAI/bge-small-en-v1.5
query_qdrant method BAAI/bge-small-en-v1.5
query_qdrant method*2* BAAI/bge-small-en-v1.5
QdrantFastembedMixin BAAI/bge-small-en-v1.5
_get_or_init_model BAAI/bge-small-en-v1.5
initial embedding_models {}
_get_or_init_model - model IS supported!
with added embedding_models {'BAAI/bge-small-en-v1.5': <fastembed.embedding.DefaultEmbedding object at 0x000002438973ECB0>}
query_batch BAAI/bge-small-en-v1.5
_get_or_init_model BAAI/bge-small-en-v1.5
initial embedding_models {'BAAI/bge-small-en-v1.5': <fastembed.embedding.DefaultEmbedding object at 0x000002438973ECB0>}
ERROR:root:Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Wrong input: Vector params for fast-bge-small-en-v1.5 are not specified in config"},"time":0.001431009}'
Traceback (most recent call last):
  File "C:\Users\Ebeid\Repositories\Projects\agentcloud\agent-backend\src\agents\base.py", line 59, in new_rag_execution
    build_chat.run_chat()
  File "C:\Users\Ebeid\Repositories\Projects\agentcloud\agent-backend\src\build\build_group.py", line 168, in run_chat
    return user_proxy.initiate_chat(
  File "C:\Users\User\App\lib\site-packages\autogen\agentchat\conversable_agent.py", line 826, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "C:\Users\User\App\lib\site-packages\autogen\agentchat\contrib\retrieve_user_proxy_agent.py", line 494, in generate_init_message
    self.retrieve_docs(problem, n_results, search_string)
  File "C:\Users\User\App\lib\site-packages\autogen\agentchat\contrib\qdrant_retrieve_user_proxy_agent.py", line 148, in retrieve_docs
    results = query_qdrant(
  File "C:\Users\User\App\lib\site-packages\autogen\agentchat\contrib\qdrant_retrieve_user_proxy_agent.py", line 305, in query_qdrant
    results = client.query_batch(
  File "C:\Users\User\App\lib\site-packages\qdrant_client\qdrant_fastembed.py", line 429, in query_batch
    for response in self.search_batch(
  File "C:\Users\User\App\lib\site-packages\qdrant_client\qdrant_client.py", line 241, in search_batch
    return self._client.search_batch(
  File "C:\Users\User\App\lib\site-packages\qdrant_client\qdrant_remote.py", line 369, in search_batch
    http_res: List[List[models.ScoredPoint]] = self.http.points_api.search_batch_points(
  File "C:\Users\User\App\lib\site-packages\qdrant_client\http\api\points_api.py", line 1354, in search_batch_points
    return self._build_for_search_batch_points(
  File "C:\Users\User\App\lib\site-packages\qdrant_client\http\api\points_api.py", line 568, in _build_for_search_batch_points
    return self.api_client.request(
  File "C:\Users\User\App\lib\site-packages\qdrant_client\http\api_client.py", line 74, in request
    return self.send(request, type_)
  File "C:\Users\User\App\lib\site-packages\qdrant_client\http\api_client.py", line 97, in send
    raise UnexpectedResponse.for_response(response)
qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Wrong input: Vector params for fast-bge-small-en-v1.5 are not specified in config"},"time":0.001431009}'
```

![image](https://github.com/microsoft/autogen/assets/48051935/e6c013c0-8e00-4e1f-be5c-d026ea6ec29f)
![image](https://github.com/microsoft/autogen/assets/48051935/79f69104-9ef1-4bcb-a12f-93ccdef4541b)

**Comment by Anush008** [comment]
@pebeid, can you do `QdrantClient#get_collection()` and share the response here?

**Comment by Anush008** [comment]
@pebeid, from your first screenshot, your vector in Qdrant is named `BAAI/bge-small-en-v1.5`. Should be `fast-bge-small-en-v1.5`.

**Comment by Anush008** [comment]
Similar to https://github.com/microsoft/autogen/issues/533#issuecomment-1793281817.

**Comment by pebeid** [comment]
@Anush008 I tried that as well got this:
```
ERROR:root:Unsupported embedding model: fast-bge-small-en-v1.5. Supported models: {'BAAI/bge-base-en': (768, <Distance.COSINE: 'Cosine'>), 'sentence-transformers/all-MiniLM-L6-v2': (384, <Distance.COSINE: 'Cosine'>), 'BAAI/bge-small-en': (384, <Distance.COSINE: 'Cosine'>), 'BAAI/bge-small-en-v1.5': (384, <Distance.COSINE: 'Cosine'>), 'BAAI/bge-base-en-v1.5': (768, <Distance.COSINE: 'Cosine'>), 'intfloat/multilingual-e5-large': (1024, <Distance.COSINE: 'Cosine'>)}
Traceback (most recent call last):
  File "C:\Users\User\App\agentcloud\agent-backend\src\agents\base.py", line 59, in new_rag_execution
    build_chat.run_chat()
  File "C:\Users\User\App\agentcloud\agent-backend\src\build\build_group.py", line 168, in run_chat
    return user_proxy.initiate_chat(
  File "C:\Users\User\App\lib\site-packages\autogen\agentchat\conversable_agent.py", line 826, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "C:\Users\User\App\lib\site-packages\autogen\agentchat\contrib\retrieve_user_proxy_agent.py", line 494, in generate_init_message
    self.retrieve_docs(problem, n_results, search_string)
  File "C:\Users\User\App\lib\site-packages\autogen\agentchat\contrib\qdrant_retrieve_user_proxy_agent.py", line 148, in retrieve_docs
    results = query_qdrant(
  File "C:\Users\User\App\lib\site-packages\autogen\agentchat\contrib\qdrant_retrieve_user_proxy_agent.py", line 303, in query_qdrant
    client.set_model(embedding_model)
  File "C:\Users\User\App\lib\site-packages\qdrant_client\qdrant_fastembed.py", line 59, in set_model
    self._get_or_init_model(
  File "C:\Users\User\App\lib\site-packages\qdrant_client\qdrant_fastembed.py", line 104, in _get_or_init_model
    raise ValueError(
ValueError: Unsupported embedding model: fast-bge-small-en-v1.5. Supported models: {'BAAI/bge-base-en': (768, <Distance.COSINE: 'Cosine'>), 'sentence-transformers/all-MiniLM-L6-v2': (384, <Distance.COSINE: 'Cosine'>), 'BAAI/bge-small-en': (384, <Distance.COSINE: 'Cosine'>), 'BAAI/bge-small-en-v1.5': (384, <Distance.COSINE: 'Cosine'>), 'BAAI/bge-base-en-v1.5': (768, <Distance.COSINE: 'Cosine'>), 'intfloat/multilingual-e5-large': (1024, <Distance.COSINE: 'Cosine'>)}
```

**Comment by Anush008** [comment]
You're calling `set_model("fast-bge-small-en-v1.5")`? Which should be `set_model(BAAI/bge-small-en-v1.5)`.

The name of the vector in the collection is to be updated. You can try deleting the collection and creating it again.

Assign the model with `QdrantClient#set_model("BAAI/bge-small-en-v1.5")` before passing it to Autogen.

**Comment by pebeid** [comment]
I just tried it a different way and it worked:
1. embed document using `fast-bge-small-en-v1.5`
2. query using `BAAI/bge-small-en-v1.5`

@Anush008 set_model(BAAI/bge-small-en-v1.5)

Here is what the log looks like now

```
datasource: {'id': '65cb0ae1b59e5604d7a5b280', 'model': 'BAAI/bge-small-en-v1.5'}
Successfully connected to Qdrant. Collections: collections=[CollectionDescription(name='65c9a796d49e3e22ee68060e'), CollectionDescription(name='65c9ae88d49e3e22ee68064c'), CollectionDescription(name='65cb0ae1b59e5604d7a5b280'), CollectionDescription(name='65c4283aa02ed274fd18a2a1'), CollectionDescription(name='65c99c4dd49e3e22ee6805fe'), CollectionDescription(name='65cb12a366e6eaac7dad5fe3'), CollectionDescription(name='65c9c33ca8e43ebf9c259bac'), CollectionDescription(name='65c9ac74d49e3e22ee68062f'), CollectionDescription(name='65c30bf754671384a4ffe5a5'), CollectionDescription(name='65c9a9abd49e3e22ee68061c')]
docs_path is not provided in retrieve_config. Will raise ValueError if the collection `65cb0ae1b59e5604d7a5b280` doesn't exist. Set docs_path to None to suppress this warning.
query qdant 65cb0ae1b59e5604d7a5b280 BAAI/bge-small-en-v1.5
query_qdrant method BAAI/bge-small-en-v1.5
query_qdrant method*2* BAAI/bge-small-en-v1.5
QdrantFastembedMixin BAAI/bge-small-en-v1.5
_get_or_init_model BAAI/bge-small-en-v1.5
initial embedding_models {}
_get_or_init_model - model IS supported!
with added embedding_models {'BAAI/bge-small-en-v1.5': <fastembed.embedding.DefaultEmbedding object at 0x00000294ED30A440>}
query_batch BAAI/bge-small-en-v1.5
_get_or_init_model BAAI/bge-small-en-v1.5
initial embedding_models {'BAAI/bge-small-en-v1.5': <fastembed.embedding.DefaultEmbedding object at 0x00000294ED30A440>}
qdrant search results {'ids': [['bdc24cb8-c493-4316-975f-573b4e5cf508', '3abcb041-dd6a-4481-9785-5fa47ad3ae1d',
....
, ['00%0', '00%0', '00%0', '00%0', '00%0', '02%0', '03%0', '06%0', '06%0', '01%0', '01%0', '70', '08%0', '05%0', '05%0', '05%0', '00% and 0', '09%0', '09%0', '21%0'], ['00%0', '00%0', '00%0', '00%0', '00%0', '06%0', '06%0', '08%0', '09%0', '09%0', '01%0', '01%0', '70', '02%0', 'com/MemberDirect for details', 'com/MemberDirect for details', '05%0', '05%0', '05%0', '03%0'], ['com/pds or by calling 1300 300 273', '06%0', '06%0', '05%0', '05%0', '05%0', '02%0', '09%0', '09%0', '00%0', '00%0', '00%0', '00%0', '00%0', 'com/tmd\n\nDid you know', '08%0', '01%0', '01%0', '03%0', ' Not all fees are relevant to you']]}
Adding doc_id bdc24cb8-c493-4316-975f-573b4e5cf508 to context.
Adding doc_id 3abcb041-dd6a-4481-9785-5fa47ad3ae1d to context.
Adding doc_id a8f88095-edbf-4b55-b7ef-4fe58ec9c490 to context.
Adding doc_id 13110d64-b6cc-4854-b84b-e2650f424792 to context.
Adding doc_id 33af3a19-3693-423c-a837-2fc7b5695830 to context.
Adding doc_id 929dd5d0-6cec-4c2c-8b65-d6cd07cda33f to context.
Adding doc_id 4a31d774-71be-4c5c-9003-736b69d8ee86 to context.
Adding doc_id c55ccef8-6be2-4b80-90ea-f219a4034be3 to context.
Adding doc_id 9f592983-4df2-4fc8-8451-58f34557d402 to context.
Adding doc_id c9754ada-7523-4e85-acf3-03741e509bad to context.
Adding doc_id 0c63c004-7d61-4f33-81a2-4e83053281e4 to context.
Adding doc_id c221fe01-9190-49ec-be49-03a89d9ab13a to context.
Adding doc_id 8cd68b91-89bd-4377-b116-7664e7ba9b09 to context.
Adding doc_id d8800597-18cf-4629-934b-94823d7e8cc5 to context.
Adding doc_id 3d11b569-909e-4c24-9656-7377353de809 to context.
Adding doc_id ac0f36a8-a359-4021-960d-27b0fa6ce0ab to context.
Adding doc_id 08e7cca9-391e-420d-8a1f-9ff127e2c7fa to context.
Adding doc_id 0cb63f7c-acce-4874-a572-e2c2a30dfe2d to context.
Adding doc_id 941fbebe-df4c-4bd9-a246-ad41e08442c3 to context.
Adding doc_id 295c0cab-33c6-406f-b4e9-9b16f93c18a9 to context.
Custom input function...
```

That's good but also weird in why it should work that way!

**Comment by sgvarsh** [comment]
@pebeid I am facing same issue, can you describe how you mentioned 2 different models  for query vs adding docs. I am having problem in querying.
