### ISSUE TITLE
f"***** Suggested function call: {message['function_call'].get('name','(No function name found)')} *****"

### ISSUE THREAD

**Issue by darvsum** [microsoft/autogen#568]
```
from autogen import AssistantAgent, UserProxyAgent, oai
config_list=[
    {
        "model": "gpt-4",
        "api_base": "http://127.0.0.1:8000",  #litellm compatible endpoint   or  "http://127.0.0.1:8000/v1"  # no litellm 
        "api_type": "open_ai",
        "api_key": "NULL", # just a placeholder
    }
]

response = oai.Completion.create(config_list=config_list, prompt="Hi")
print(response) # works fine

llm_config={
    "config_list": config_list,
}

assistant = AssistantAgent("assistant", llm_config=llm_config)
user_proxy = UserProxyAgent("user_proxy")
user_proxy.initiate_chat(assistant, message="Python implements a bubble algorithm and gives a specific example.", config_list=config_list)
```
## Using models chatglm3-6b and qwen-14b, you can answer after executing the above code, but an error is reported.
The error message is as follows:

{
  "id": "chatcmpl-1460ec961c24c0ac2eea9ac1",
  "object": "chat.completion",
  "created": 1699252068,
  "model": "gpt-4",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "Hello! How can I help you today? Is there something on your mind that you would like to talk about or ask me a question? I'm here to assist, so feel free to ask me anything.",
        "name": null,
        "functions": null,
        "function_call": null
      },
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 20,
    "total_tokens": 62,
    "completion_tokens": 42
  },
  "cost": 0.00312,
  "config_id": 0,
  "pass_filter": true
}
user_proxy (to assistant):

python impelments a bubble algorithm and gives a specific example。

--------------------------------------------------------------------------------
assistant (to user_proxy):

```python
# Filename: bubble_sort.py

def bubble_sort(arr):
    n = len(arr)
    # Traverse through all array elements
    for i in range(n-1):
        # Last i elements are already in place
        for j in range(0, n-i-1):
            # traverse the array from 0 to n-i-1
            # Swap if the element found is greater than the next element
            if arr[j] > arr[j+1] :
                arr[j], arr[j+1] = arr[j+1], arr[j]

# Test the function
arr = [64, 34, 25, 12, 22, 11, 90]
bubble_sort(arr)
 
print ("Sorted array is:")
for i in range(len(arr)):
    print ("%d" %arr[i]),
```

This is a Python implementation of the Bubble Sort algorithm. It takes an array `arr` as input and sorts it in ascending order using the bubble sort algorithm. In each iteration, it compares adjacent elements and swaps them if they are in the wrong order. This process is repeated until the entire array is sorted.
For example, consider the input array `[64, 34, 25, 12, 22, 11, 90]`. After running the Bubble Sort algorithm on this array, the sorted array will be `[11, 12, 22, 25, 34, 64, 90]`.
Note that Bubble Sort has a time complexity of O(n^2), which makes it inefficient for large datasets. However, it is simple to understand and implement, making it a good choice for small datasets or educational purposes.
To run this script, save it as `bubble_sort.py` and then execute the following command in the terminal:
```bash
python bubble_sort.py
```

It will output the sorted array `[11, 12, 22, 25, 34, 64, 90]`.
Traceback (most recent call last):
  File "/tools/codes/test-agent/examples/react_demo4.py", line 338, in <module>
    test_autogen3()
  File "/tools/codes/test-agent/examples/react_demo4.py", line 334, in test_autogen3
    user_proxy.initiate_chat(assistant, config_list=config_list, message="python impelments a bubble algorithm and gives a specific example。")
  File "/root/anaconda3/envs/test-agent/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 531, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/root/anaconda3/envs/test-agent/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "/root/anaconda3/envs/test-agent/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 464, in receive
    self.send(reply, sender, silent=silent)
  File "/root/anaconda3/envs/test-agent/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "/root/anaconda3/envs/test-agent/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 459, in receive
    self._process_received_message(message, sender, silent)
  File "/root/anaconda3/envs/test-agent/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 428, in _process_received_message
    self._print_received_message(message, sender)
  File "/root/anaconda3/envs/test-agent/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 408, in _print_received_message
    func_print = f"***** Suggested function Call: {message['function_call'].get('name', '(No function name found)')} *****"
AttributeError: 'NoneType' object has no attribute 'get'

Process finished with exit code 1

**Comment by loyalty-fox** [comment]
I also encountered this problem, have you solved it?

**Comment by HAL9KKK** [comment]
I have the same issue, I see the option "Silent" if True can avoid to print out the messange and so do not execute this piece of code that generate the issue...
but I do not know where to put the option "silent": True

**Comment by loyalty-fox** [comment]
> I have the same issue, I see the option "Silent" if True can avoid to print out the messange and so do not execute this piece of code that generate the issue... but I do not know where to put the option "silent": True

I've tried this approach but it didn't work. This condition is located in .your_env/autogen/agentchat/conversable_agent line 408
I found that the cause of the error was that the function_call'name in the message received by the previous assistant_agent was NULL, so the "get" function could not be executed.
I tried to change the above judgment condition to "if message['function_call'] is not None:". Although this statement was skipped, a new similar error still appeared below. The error message is as follows:
```
Traceback (most recent call last):
  File "/home/algo05/res/test_CH/agent/autogen/test/test3_human_input.py", line 45, in <module>
    user_proxy.initiate_chat(assistant,message=task1,clear_history = True)
  File "/home/algo05/anaconda3/envs/agent_ch/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 531, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/home/algo05/anaconda3/envs/agent_ch/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "/home/algo05/anaconda3/envs/agent_ch/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 464, in receive
    self.send(reply, sender, silent=silent)
  File "/home/algo05/anaconda3/envs/agent_ch/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "/home/algo05/anaconda3/envs/agent_ch/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 462, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "/home/algo05/anaconda3/envs/agent_ch/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 781, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/home/algo05/anaconda3/envs/agent_ch/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 660, in generate_function_call_reply
    _, func_return = self.execute_function(message["function_call"])
  File "/home/algo05/anaconda3/envs/agent_ch/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 972, in execute_function
func_name = func_call.get("name", "")
AttributeError: 'NoneType' object has no attribute 'get'
```
I suspect that the root cause is that uer_agent received irregular information or the program executed to the wrong place.
The original test program can be executed directly using the openai key, but I cannot see the specific content of the message from the assistant received by the user_agent in the middle; and this kind of program involving server communication cannot work properly when I debug it. Enter the corresponding function. I am not very good at debugging this kind of program. So I couldn't see what normal conditions should be like.

**Comment by loyalty-fox** [comment]
> I have the same issue, I see the option "Silent" if True can avoid to print out the messange and so do not execute this piece of code that generate the issue... but I do not know where to put the option "silent": True

The silent is located in line 514. it seems to be used only to decide whether to print the messages for this conversation.

**Comment by HAL9KKK** [comment]
you are right @loyalty-fox, I found where to put "silent", in:

`user_proxy.initiate_chat(
    assistant,
    message="""what is the distance from the Earth to the Moon?""",
    silent=True,
)`

Then it skip the print out code but it want to execute the code with the function call null

```
File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\agentchat\conversable_agent.py:972, in ConversableAgent.execute_function(self, func_call)
    959 def execute_function(self, func_call):
    960     """Execute a function call and return the result.
    961 
    962     Override this function to modify the way to execute a function call.
   (...)
    970         result_dict: a dictionary with keys "name", "role", and "content". Value of "role" is "function".
    971     """
--> 972     func_name = func_call.get("name", "")
    973     func = self._function_map.get(func_name, None)
    975     is_exec_success = False

AttributeError: 'NoneType' object has no attribute 'get'
```
So at the end the "Silent" work around is not working.

We could try to compare the full message received from the User-Proxy by the Assistant with real OpenAI Key and without (using our local LLM)

**Comment by loyalty-fox** [comment]
> you are right @loyalty-fox, I found where to put "silent", in:
> 
> `user_proxy.initiate_chat( assistant, message="""what is the distance from the Earth to the Moon?""", silent=True, )`
> 
> Then it skip the print out code but it want to execute the code with the function call null
> 
> ```
> File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\autogen\agentchat\conversable_agent.py:972, in ConversableAgent.execute_function(self, func_call)
>     959 def execute_function(self, func_call):
>     960     """Execute a function call and return the result.
>     961 
>     962     Override this function to modify the way to execute a function call.
>    (...)
>     970         result_dict: a dictionary with keys "name", "role", and "content". Value of "role" is "function".
>     971     """
> --> 972     func_name = func_call.get("name", "")
>     973     func = self._function_map.get(func_name, None)
>     975     is_exec_success = False
> 
> AttributeError: 'NoneType' object has no attribute 'get'
> ```
> 
> So at the end the "Silent" work around is not working.
> 
> We could try to compare the full message received from the User-Proxy by the Assistant with real OpenAI Key and without (using our local LLM)
Yes,@HAL9KKK,  I have just been trying to compare the openai key with the local LLM, and print the message information through the print function in the py file.
I found that the root of the problem is that the message sent to user_agent by user_agent in the send function contains two key-value pairs (function_call and name) that are None.
Just now I found a solution:
Add the following code below convertable_agent.py line 276 to delete the two key-value pairs:
```
> line 276   message = self._message_to_dict(message)
if "name" in message and message["name"] is None:
    message.pop("name")
if "function_call" in message and message["function_call"] is None:
    message.pop("function_call")
```
This method works for me, you can try it

**Comment by HAL9KKK** [comment]
Fantasti work @loyalty-fox !!!!!
Yes it is working for me as well 

I have noticed, it never execute the code anyway, maybe is another problem, not realated with this one...
Always use python to install the missing libraries instead of bash, and so, it never complete the task

```
>>>>>>>> EXECUTING CODE BLOCK 0 (inferred language is python)...
user_proxy (to assistant):

exitcode: 1 (execution failed)
Code output: 
  File "", line 1
    pip install requests
        ^^^^^^^
SyntaxError: invalid syntax
```

**Comment by loyalty-fox** [comment]
> Fantasti work @loyalty-fox !!!!! Yes it is working for me as well
> 
> I have noticed, it never execute the code anyway, maybe is another problem, not realated with this one... Always use python to install the missing libraries instead of bash, and so, it never complete the task
> 
> ```
> >>>>>>>> EXECUTING CODE BLOCK 0 (inferred language is python)...
> user_proxy (to assistant):
> 
> exitcode: 1 (execution failed)
> Code output: 
>   File "", line 1
>     pip install requests
>         ^^^^^^^
> SyntaxError: invalid syntax
> ```

I seem to have encountered similar problems when using openai key, so I guess the user_agent doesn't have the permission to perform pip installation of the environment package. Maybe you can manually install the corresponding package in the relevant environment or try not to have assistant generate code to install environment packages

**Comment by thinkall** [comment]
Closing this issue due to inactivity. If you have further questions, please open a new issue or join the discussion in AutoGen Discord server: https://discord.com/invite/Yb5gwGVkE5
