### ISSUE TITLE
Error occurred while processing message: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

### ISSUE THREAD

**Issue by ruifengma** [microsoft/autogen#805]
Hi, I start the autogenra ui successfully and I setting the proxy agent with no LLM model and remain the system message same as default. For the assistant agent I use self-host Mistral-7b, I gave the model name and base url, for the api_key, I gave "null".  When I start to send the message and this error come up. How can I deal with this? Thanks

**Comment by hiteshsom** [comment]
I am getting similar error too.

My code
```
config_list = [
    {
    "model": "<path>\mistral-7b-instruct-v0.1.Q6_K.gguf",
    "api-base": "http://127.0.0.1:8000/v1",
    "api-type": "open_ai",
    "api-key": "sk-abc"
    }
]

llm_config = {"config_list": config_list, "seed": 10}

<My agents>

manager = GroupChatManager(groupchat=group_chat, llm_config=llm_config)
user_proxy.initiate_chat(manager, message="Hello, How are you ?")
```



```
Traceback (most recent call last):
  File "<project_path>\gen_ai_chatbot_server\autogen_file.py", line 115, in <module>
    user_proxy.initiate_chat(manager, message="Hello, How are you ?")
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\autogen\agentchat\conversable_agent.py", line 531, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\autogen\agentchat\conversable_agent.py", line 334, in send      
    recipient.receive(message, self, request_reply, silent)
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\autogen\agentchat\conversable_agent.py", line 462, in receive   
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\autogen\agentchat\conversable_agent.py", line 779, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\autogen\agentchat\groupchat.py", line 127, in run_chat
    speaker = groupchat.select_speaker(speaker, self)
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\autogen\agentchat\groupchat.py", line 56, in select_speaker     
    final, name = selector.generate_oai_reply(
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\autogen\agentchat\conversable_agent.py", line 606, in generate_oai_reply
    response = oai.ChatCompletion.create(
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\autogen\oai\completion.py", line 789, in create
    response = cls.create(
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\autogen\oai\completion.py", line 820, in create
    return cls._get_response(params, raise_on_ratelimit_or_timeout=raise_on_ratelimit_or_timeout)
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\autogen\oai\completion.py", line 210, in _get_response
    response = openai_completion.create(request_timeout=request_timeout, **config)
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create    
    return super().create(*args, **kwargs)
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 151, in create
    ) = cls.__prepare_create_request(
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 108, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\openai\api_requestor.py", line 139, in __init__
    self.api_key = key or util.default_api_key()
  File "<project_path>\gen_ai_chatbot_server\gen_ai_chatbot_server_venv\lib\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment var
iable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <project_path>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
```

**Comment by victordibia** [comment]
@ruifengma ,

> The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable 

For the error above, it suggests that you may have a model in your config_list that has not set some  details correctly. Can you confirm that you have set the `base_url` and not `api_base`. 


Also, please try the latest version of autogenra as this has extended the UI to allow for modifying the models.

```python
pip install -U autogenra
```



![Image](https://github.com/microsoft/autogen/assets/1547007/7ab47aa8-13b7-4174-a216-11077667bc6d)



```python

config_list = [
    {
    "model": "<path>\mistral-7b-instruct-v0.1.Q6_K.gguf",
    "base_url": "http://127.0.0.1:8000/v1",
    "api-type": "open_ai",
    "api-key": "sk-abc"
    }
]

llm_config = {"config_list": config_list, "seed": 10}

<My agents>

manager = GroupChatManager(groupchat=group_chat, llm_config=llm_config)
user_proxy.initiate_chat(manager, message="Hello, How are you ?")
```

**Comment by ruifengma** [comment]
> @ruifengma ,
> 
> > The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
> 
> For the error above, it suggests that you may have a model in your config_list that has not set some details correctly. Can you confirm that you have set the `base_url` and not `api_base`.
> 
> Also, please try the latest version of autogenra as this has extended the UI to allow for modifying the models.
> 
> ```python
> pip install -U autogenra
> ```
> 
> ![Image](https://private-user-images.githubusercontent.com/1547007/286740708-7ab47aa8-13b7-4174-a216-11077667bc6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMDk0NjQsIm5iZiI6MTcwMTMwOTE2NCwicGF0aCI6Ii8xNTQ3MDA3LzI4Njc0MDcwOC03YWI0N2FhOC0xM2I3LTQxNzQtYTIxNi0xMTA3NzY2N2JjNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMDE1MjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc2OTc3NTFlZTZkYWU5ODgzMzhiYWViNzc0MzMyYzY2ZDIzYzhkNmM3ZDQ5NTAwMTQyNjIzYjlkM2MwYTY0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LKtzYiNFjpw2wH_3lRYxnadnHlVuLYN56aHvYnyREf8)
> 
> ```python
> config_list = [
>     {
>     "model": "<path>\mistral-7b-instruct-v0.1.Q6_K.gguf",
>     "base_url": "http://127.0.0.1:8000/v1",
>     "api-type": "open_ai",
>     "api-key": "sk-abc"
>     }
> ]
> 
> llm_config = {"config_list": config_list, "seed": 10}
> 
> <My agents>
> 
> manager = GroupChatManager(groupchat=group_chat, llm_config=llm_config)
> user_proxy.initiate_chat(manager, message="Hello, How are you ?")
> ```

Thanks @victordibia for the reply, I solve the issue by assigning the proxy agent an LLM as well. If I delete all the models for proxy agent and leave it a blank, then this error comes up. If I assign a model to proxy agent, then it works. The question is that, I saw the examples which autogen supports proxy agent without LLM and only assistant with LLM and I tried this setting before. Besides, I saw your ui which model settings are totally Blank (different from mine)

**Comment by tamuraPol** [comment]
This is a helpful article

**Comment by srishino** [comment]
Hi all, I am having the same error and having a similar set. I have set up pyautogen(version-0.2.2) am using oobaboga webui for hosting my local LLM(mistral-7b-instruct). It runs fine when i query using user_proxy agent. Now I am developing a function tool following - https://github.com/microsoft/autogen/blob/main/notebook/agentchat_function_call.ipynb and that throws an error. My code is as follows:                                                                                                                                           
`import autogen


config_list = [
    {
        "model": "model path/model name",
        "base_url": "http://127.0.0.1:5000/v1",
        #"api_type": "open_ai",
        "api_key": "sk-111111111111111111111111111111111111111111111111", # just a placeholder
    }
]
#same code from the above link
chatbot = autogen.AssistantAgent(
    name="chatbot",
    system_message="For coding tasks, only use the functions you have been provided with. Reply TERMINATE when the task is done.",
    llm_config=config_list,
)

# create a UserProxyAgent instance named "user_proxy"
user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    is_termination_msg=lambda x: x.get("content", "") and x.get("content", "").rstrip().endswith("TERMINATE"),
    human_input_mode="NEVER",
    max_consecutive_auto_reply=10,
    code_execution_config={"work_dir": "coding"},
    llm_config=config_list
)

# define functions according to the function description
from IPython import get_ipython
from typing_extensions import Annotated


@user_proxy.register_for_execution()
@chatbot.register_for_llm(name="python", description="run cell in ipython and return the execution result.")
def exec_python(cell: Annotated[str, "Valid Python cell to execute."]) -> str:
    ipython = get_ipython()
    result = ipython.run_cell(cell)
    log = str(result.result)
    if result.error_before_exec is not None:
        log += f"\n{result.error_before_exec}"
    if result.error_in_exec is not None:
        log += f"\n{result.error_in_exec}"
    return log


@user_proxy.register_for_execution()
@chatbot.register_for_llm(name="sh", description="run a shell script and return the execution result.")
def exec_sh(script: Annotated[str, "Valid Python cell to execute."]) -> str:
    return user_proxy.execute_code_blocks([("sh", script)])


# start the conversation
user_proxy.initiate_chat(
    chatbot,
    message="Draw two agents chatting with each other with an example dialog. Don't add plt.show().",
)  `                                                                                                                                                                                            
 Please help me solve this, thanks!

**Comment by victordibia** [comment]
Closing this due to inactivity.

References

- [AutoGen studio](https://github.com/microsoft/autogen/tree/autogenstudio/samples/apps/autogen-studio) is the emerging reference example of using AutoGen with a web interface. 
- Roadmap for AutoGen Studio is here #737

**Comment by mynewstart** [comment]
> > [@ruifengma](https://github.com/ruifengma) ,
> > > The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
> > 
> > 
> > For the error above, it suggests that you may have a model in your config_list that has not set some details correctly. Can you confirm that you have set the `base_url` and not `api_base`.
> > Also, please try the latest version of autogenra as this has extended the UI to allow for modifying the models.
> > pip install -U autogenra
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![Image](https://private-user-images.githubusercontent.com/1547007/286740708-7ab47aa8-13b7-4174-a216-11077667bc6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMDk0NjQsIm5iZiI6MTcwMTMwOTE2NCwicGF0aCI6Ii8xNTQ3MDA3LzI4Njc0MDcwOC03YWI0N2FhOC0xM2I3LTQxNzQtYTIxNi0xMTA3NzY2N2JjNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMzBUMDE1MjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc2OTc3NTFlZTZkYWU5ODgzMzhiYWViNzc0MzMyYzY2ZDIzYzhkNmM3ZDQ5NTAwMTQyNjIzYjlkM2MwYTY0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LKtzYiNFjpw2wH_3lRYxnadnHlVuLYN56aHvYnyREf8)
> > config_list = [
> >     {
> >     "model": "<path>\mistral-7b-instruct-v0.1.Q6_K.gguf",
> >     "base_url": "http://127.0.0.1:8000/v1",
> >     "api-type": "open_ai",
> >     "api-key": "sk-abc"
> >     }
> > ]
> > 
> > llm_config = {"config_list": config_list, "seed": 10}
> > 
> > <My agents>
> > 
> > manager = GroupChatManager(groupchat=group_chat, llm_config=llm_config)
> > user_proxy.initiate_chat(manager, message="Hello, How are you ?")
> 
> Thanks [@victordibia](https://github.com/victordibia) for the reply, I solve the issue by assigning the proxy agent an LLM as well. If I delete all the models for proxy agent and leave it a blank, then this error comes up. If I assign a model to proxy agent, then it works. The question is that, I saw the examples which autogen supports proxy agent without LLM and only assistant with LLM and I tried this setting before. Besides, I saw your ui which model settings are totally Blank (different from mine)

I found the same issue, do you know why?
