### ISSUE TITLE
[Issue]: Function calling is not working 

### ISSUE THREAD

**Issue by PriyaBrataSen** [microsoft/autogen#993]
### Describe the issue

I want to run a function that will get an article and recommend some applications based on the article. It is running without function call but i get an error when i am using a function to that. Please help me with some suggestions. What am i doing wrong?

### Steps to reproduce

Step1: I created the following function 

import requests
from bs4 import BeautifulSoup
from dateutil.parser import parse
def article(topic):
    # Set the URL for arXiv API
    url = f"https://export.arxiv.org/api/query?search_query=all:{topic}&sortBy=lastUpdatedDate&sortOrder=descending"

    # Send GET request to the URL
    response = requests.get(url, verify=False)

    # Parse the response content with BeautifulSoup
    soup = BeautifulSoup(response.content, "xml")

    # Find the latest paper
    latest_paper = soup.find('entry')

    # Extract and print details of the latest paper
    title = latest_paper.title.text
    abstract = latest_paper.summary.text
    published_date = parse(latest_paper.published.text).date()
    print(f"Title: {title}\nPublished on: {published_date}\nAbstract: {abstract}")
if __name__=='__main__':
    article('Autogen')

Step 2:

after that i am creating my autogen scripts

import autogen
from scrap import article

config_list = autogen.config_list_from_json(env_or_file="OAI_CONFIG_LIST")

llm_config = {"config_list": config_list, 
            #   "cache_seed": 41,
            "functions":[
                {
                    "name": "article",
                    "description": "Gets the topic of the article and returns the article content",
                    "parameters":{
                        "type":"object",
                        "properties":{
                            "topic":{
                                "type":"string",
                                "description":"The topic of the article"
                            }
                        }
                    }
                }
            ],
            "timeout":120

}

coder = autogen.AssistantAgent(
    name="Coder",
    llm_config=llm_config
)

user_proxy = autogen.UserProxyAgent(
   name="User_proxy",
   system_message="A human admin.",
   code_execution_config={"last_n_messages": 2, "work_dir": "groupchat"},
   human_input_mode="ALWAYS",
   function_map={"article":article}
)

user_proxy.initiate_chat(coder, message="Find a latest paper about Autogen on arxiv using bs4 and requests.Once completed,find its potential applications in business based on the papaer.")

Step 3; When i run it i get this error 

Find a latest paper about Autogen on arxiv using bs4 and requests.Once completed,find its potential applications in business based on the papaer.

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\app.py", line 50, in <module>
    user_proxy.initiate_chat(coder, message="Find a latest paper about Autogen on arxiv using bs4 and requests.Once completed,find its potential applications in business based on the papaer.")
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 540, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 340, in send
    recipient.receive(message, self, request_reply, silent)
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 471, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 883, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 615, in generate_oai_reply
    response = client.create(
               ^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\oai\client.py", line 242, in create
    response = completions.create(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\_utils\_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\resources\chat\completions.py", line 556, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\_base_client.py", line 1055, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\_base_client.py", line 834, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\_base_client.py", line 877, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'Unrecognized request argument supplied: functions', 'type': 'invalid_request_error', 'param': None, 'code': None}}

### Additional Information

Autogen: 0.2.0b3
Operating System: Windows
Python : 3.11.3

I am using azure openai. Below is my configure list

    {
        "model": "gpt-4-8k",
        "api_key": xxx",
        "base_url": "https://agr-dev-openai.openai.azure.com/",
        "api_type": "azure",
        "api_version":"2023-03-15-preview"
    }

**Comment by rickyloynd-microsoft** [comment]
`pyautogen==0.2.2` fixed a bug with function calling.

**Comment by PriyaBrataSen** [comment]
Hello Sir, thank you for your reply. i installed 0.2.2 and still getting the following error. Is it because i am using azure openai? 


Find a latest paper about Autogen on arxiv using bs4 and requests.Once completed,find its potential applications in business based on the papaer.

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\app.py", line 42, in <module>
    user_proxy.initiate_chat(coder, message="Find a latest paper about Autogen on arxiv using bs4 and requests.Once completed,find its potential applications in business based on the papaer.")
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 556, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 354, in send
    recipient.receive(message, self, request_reply, silent)
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 487, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 962, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 631, in generate_oai_reply
    response = client.create(
               ^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\oai\client.py", line 260, in create
    response = self._completions_create(client, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\oai\client.py", line 346, in _completions_create
    response = completions.create(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\_utils\_utils.py", line 303, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\resources\chat\completions.py", line 604, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\_base_client.py", line 1088, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\_base_client.py", line 853, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\_base_client.py", line 930, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'Unrecognized request argument supplied: functions', 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by rickyloynd-microsoft** [comment]
Does your azure openai model work on a very simple autogen example like `https://github.com/microsoft/autogen/blob/main/samples/simple_chat.py` ?

**Comment by PriyaBrataSen** [comment]
yes sir, i am able to run it. below is the output


agent (to user):

How can I help you today?

--------------------------------------------------------------------------------
Provide feedback to agent. Press enter to skip and use auto-reply, or type 'exit' to end the conversation: create a python code to sort a dataframe by date column
user (to agent):

create a python code to sort a dataframe by date column

--------------------------------------------------------------------------------

>>>>>>>> USING AUTO REPLY...
agent (to user):

Sure, below is a simple Python code using pandas to sort a dataframe by a date column. I am assuming that the date column is formatted appropriately as dates, and we're using ascending order in this case:

```python
import pandas as pd

# Assuming df is your DataFrame and 'date' is your column
df['date'] = pd.to_datetime(df['date'])  # This line is necessary if your date column is not already in datetime format
df = df.sort_values(by='date')

# Print the sorted DataFrame
print(df)
```
This should give you a sorted dataframe by date in ascending order. If you want them in descending order, just add `ascending=False` like so:

```python
df = df.sort_values(by='date', ascending=False)
```

--------------------------------------------------------------------------------
Provide feedback to agent. Press enter to skip and use auto-reply, or type 'exit' to end the conversation:

**Comment by rickyloynd-microsoft** [comment]
Thanks, that narrows it down to function calling. @kevin666aa

**Comment by PriyaBrataSen** [comment]
I now created a simple function inside autogen code and ran. it gave the same issue


``
import autogen
from scrap import article

config_list = autogen.config_list_from_json(env_or_file="OAI_CONFIG_LIST")


def statement():
    print('Please print out the statement')

llm_config = {"config_list": config_list, 
            #   "cache_seed": 41,
            "functions":[
                {
                    "name": "statement",
                    "description": "printing out a statement",
                    "parameters":{
                        "type":"object",
                        "properties":{
                            "topic":{
                                "type":"",
                                "description":""
                            }
                        }
                    }
                }
            ],
            "timeout":120

}

coder = autogen.AssistantAgent(
    name="Coder",
    llm_config=llm_config
)


user_proxy = autogen.UserProxyAgent(
   name="User_proxy",
   system_message="A human admin.",
   code_execution_config={"last_n_messages": 2, "work_dir": "groupchat"},
   human_input_mode="ALWAYS",
   function_map={"article":statement}
)


user_proxy.initiate_chat(coder, message="run the function and print out the statement")
"


error:

User_proxy (to Coder):

run the function and print out the statement

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\app.py", line 46, in <module>
    user_proxy.initiate_chat(coder, message="run the function and print out the statement")
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 556, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 354, in send
    recipient.receive(message, self, request_reply, silent)
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 487, in receive      
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 962, in generate_reply    
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 631, in generate_oai_reply
    response = client.create(
               ^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\oai\client.py", line 260, in create
    response = self._completions_create(client, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\autogen\oai\client.py", line 346, in _completions_create  
    response = completions.create(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\_utils\_utils.py", line 303, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\resources\chat\completions.py", line 604, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\_base_client.py", line 1088, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\_base_client.py", line 853, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\PSen\OneDrive - Ashley Furniture Industries, Inc\autogen\venv\Lib\site-packages\openai\_base_client.py", line 930, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'Unrecognized request argument supplied: functions', 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by kevin666aa** [comment]
https://stackoverflow.com/questions/76757194/why-do-i-get-the-error-unrecognized-request-argument-supplied-functions-when

It seems that you should switch you azure preview version. 
@PriyaBrataSen Can you try this to see if it solves the problem?

**Comment by PriyaBrataSen** [comment]
Hello Sir, yesss ! After changing the api_version, it ran. Thanks a lot for taking the time and fix this problem. I will keep finding the uses cases where i can apply it. thanks  a lot @rickyloynd-microsoft @kevin666aa

**Comment by ruifengma** [comment]
Function calling is not working when I use self-deployed model with fastchat such as 'Mistral', but it is working when I use GPT.

**Comment by rickyloynd-microsoft** [comment]
Many on our [Discord channel](https://discord.gg/pAbnFJrkgZ) have been using Mistral, so you might try asking there.
